### ISSUE TITLE
Wrap zold node functionality in a docker container 

### ISSUE THREAD

**Issue by biboran** [zold-io/zold#100]
Running a `zold node` as a `gem` may be error prone and platform dependent. Wrapping `zold node` functionality in a docker container would minimize the amount of errors imposed by package manager and simplify the deployment of the node.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@biboran[/z](https://www.0crat.com/u/biboran) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C91QJT4CF) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#100](https://github.com/yegor256/zold/issues/100) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#100](https://github.com/yegor256/zold/issues/100); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@biboran it's done, check the README file

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#100` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
