### ISSUE TITLE
score.rb and farm.rb rewrite in C++

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#105]
Let's rewrite score calculation module in C++. Our current implementation, even though it's multi-threaded, is using only a single CPU core, due to Ruby limitations: https://stackoverflow.com/questions/26579532/ruby-how-to-thread-across-cores-processors

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@f43f3117-ffb6-49af-a877-faeef88d2faa, thread: pool-1479-thread-1
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: yegor256/zold#105, Action: `labeled`

**Comment by 0crat** [comment]
Job [#105](https://github.com/yegor256/zold/issues/105) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#105](https://github.com/yegor256/zold/issues/105); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by oltdaniel** [comment]
@yegor256 This will solve the issue with the slow front and timeouts as well, since the worker threads block the CPU totally.

**Comment by yegor256** [comment]
@oltdaniel indeed it will, but we have to merge this code somehow :( Now it breaks the build

**Comment by oltdaniel** [comment]
@yegor256 I will check the conflicts and may find a solution.

**Comment by yegor256** [comment]
@oltdaniel thanks!

**Comment by yegor256** [comment]
@yegor256 will be done [here](https://github.com/zold-io/zold-score/issues/2)

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#105` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
