### ISSUE TITLE
Shouldn't stuff like rubocop & cucumber be in development dependencies in gemspec?

### ISSUE THREAD

**Issue by inem** [zold-io/zold#107]

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@inem[/z](https://www.0crat.com/u/inem) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C91QJT4CF) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#107](https://github.com/zold-io/zold/issues/107) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Thanks for your contribution, @inem[/z](https://www.0crat.com/u/inem)! If you would be a member of [the project](https://www.0crat.com/p/CAZPZR9FS), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#107](https://github.com/zold-io/zold/issues/107), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#107` already assigned to @oltdaniel, can't assign to @oltdaniel

**Comment by 0crat** [comment]
@oltdaniel[/z](https://www.0crat.com/u/oltdaniel) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The job [#107](https://github.com/zold-io/zold/issues/107) assigned to @sergeykutsko[/z](https://www.0crat.com/u/sergeykutsko), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/abd22c9d-dfa8-40af-a990-3b9cc9156025); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by SergeyKutsko** [comment]
@yegor256 @oltdaniel It is not clear why

  s.add_runtime_dependency 'rubocop', '0.58.1' # has to stay here for Heroku
  s.add_runtime_dependency 'rubocop-rspec', '~>1.27' # has to stay here for Heroku
s.add_runtime_dependency 'cucumber', '~>3.1' 

has to stay here for Heroku

**Comment by SergeyKutsko** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/zold-io/zold/issues/107#issuecomment-432921610))

@SergeyKutsko The impediment for [#107](https://github.com/zold-io/zold/issues/107) was registered successfully by @sergeykutsko[/z](https://www.0crat.com/u/sergeykutsko)

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @sergeykutsko[/z](https://www.0crat.com/u/sergeykutsko), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#107](https://github.com/zold-io/zold/issues/107) is now out of scope

**Comment by ypshenychka** [comment]
@SergeyKutsko As far as there was no work done by you in this ticket, I should mark it as of "bad" quality, since the actual performer of the PR is not assigned anymore. Agree?

**Comment by SergeyKutsko** [comment]
no, because here is solutuon that already proposed.

вс, 4 нояб. 2018 г., 19:38 Yuliya Bodak <notifications@github.com>:

**Comment by SergeyKutsko** [comment]
Somebody said it is should not be here, but architect said it should be
here, so ticket is no sence.

вс, 4 нояб. 2018 г., 19:44 Sergey Kutsko <kutsko86@gmail.com>:

**Comment by SergeyKutsko** [comment]
no

вс, 4 нояб. 2018 г., 19:44 Sergey Kutsko <kutsko86@gmail.com>:

**Comment by SergeyKutsko** [comment]
Somebody said it is should not be here, but architect said it should be
here, so ticket is no sence.

вс, 4 нояб. 2018 г., 19:38 Yuliya Bodak <notifications@github.com>:

**Comment by ypshenychka** [comment]
@SergeyKutsko But there is no work done by you, for which you should be paid in this ticket. All work was done by @oltdaniel but since he is not assigned here anymore, I have to mark ticket as "bad".

**Comment by SergeyKutsko** [comment]
lol.

**Comment by SergeyKutsko** [comment]
this tiket no sence. Https://github.com/zold-io/zold/issues/502

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
