### ISSUE TITLE
Proof of work paragraph

### ISSUE THREAD

**Issue by amihaiemil** [zold-io/zold#112]
In the whitepaper, at the "Proof of work" section, there is the following paragraph:

```
If and when for any reason some data gets corrupted, the amount of CPU power a part of
the network decides to invest into its nonces calculation would be smaller
than what the other part of the network invests into legal data
```

Are you sure you understood Nakamoto's paper correctly? Who says that, if some data is correupted, the amount of invested CPU power is smaller? Why is that, why couldn't it be higher? Let's say the node could take more time/power to realize that its data is corrupted and doesn't lead to a valid result. 

Again, I'm no expert, I'm just saying that paragraph seems to lack some details.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C91QJT4CF) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@amihaiemil  I believe it's fixed. If you have any further questions, please submit to zold-io/papers repo.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#112` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
