### ISSUE TITLE
Digest::Base cannot be directly inherited in Ruby

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#113]
```
ERROR: RuntimeError: Digest::Base cannot be directly inherited in Ruby /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/score.rb:102:in `digest'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/score.rb:102:in `hexdigest'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/score.rb:102:in `block in hash'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/score.rb:101:in `each'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/score.rb:101:in `reduce'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/score.rb:101:in `hash'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/score.rb:177:in `valid?'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/score.rb:159:in `block in next'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/score.rb:153:in `loop'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/score.rb:153:in `next'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/node/farm.rb:85:in `block (4 levels) in start'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/node/farm.rb:69:in `loop'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/node/farm.rb:69:in `block (3 levels) in start'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/verbose_thread.rb:35:in `run'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/node/farm.rb:67:in `block (2 levels) in start'
ERROR: RuntimeError: Digest::Base cannot be directly inherited in Ruby /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/score.rb:102:in `digest'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/score.rb:102:in `hexdigest'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/score.rb:102:in `block in hash'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/score.rb:101:in `each'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/score.rb:101:in `reduce'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/score.rb:101:in `hash'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/score.rb:177:in `valid?'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/score.rb:159:in `block in next'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/score.rb:153:in `loop'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/score.rb:153:in `next'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/node/farm.rb:85:in `block (4 levels) in start'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/node/farm.rb:69:in `loop'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/node/farm.rb:69:in `block (3 levels) in start'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/verbose_thread.rb:35:in `run'
 /var/lib/gems/2.3.0/gems/zold-0.10.12/lib/zold/node/farm.rb:67:in `block (2 levels) in start'
```

**Comment by 0crat** [comment]
Job [#113](https://github.com/yegor256/zold/issues/113) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#113](https://github.com/yegor256/zold/issues/113); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job [#113](https://github.com/zold-io/zold/issues/113) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @oltdaniel

**Comment by 0crat** [comment]
> @0crat assign @oltdaniel ([here](https://github.com/zold-io/zold/issues/113#issuecomment-394838473))

@yegor256 The job [#113](https://github.com/zold-io/zold/issues/113) assigned to @oltdaniel[/z](https://www.0crat.com/u/oltdaniel), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1561969848); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@oltdaniel[/z](https://www.0crat.com/u/oltdaniel) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The job [#113](https://github.com/zold-io/zold/issues/113) assigned to @mulev[/z](https://www.0crat.com/u/mulev), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1651862352); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@mulev[/z](https://www.0crat.com/u/mulev) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @mulev[/z](https://www.0crat.com/u/mulev) resigned from [#113](https://github.com/zold-io/zold/issues/113), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @mulev[/z](https://www.0crat.com/u/mulev)

**Comment by 0crat** [comment]
The job [#113](https://github.com/zold-io/zold/issues/113) assigned to @sandiks[/z](https://www.0crat.com/u/sandiks), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1760725030); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
The job [#113](https://github.com/zold-io/zold/issues/113) assigned to @botanicus[/z](https://www.0crat.com/u/botanicus), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1761389599); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @yegor256[/z](https://www.0crat.com/u/yegor256) (its creator); I won't close the order; please, re-open it and ask @yegor256[/z](https://www.0crat.com/u/yegor256) to close it

**Comment by botanicus** [comment]
@yegor256 please ^

**Comment by yegor256** [comment]
@botanicus thanks!

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c4dd5905-aef7-4ef2-a527-aa92a00b7272, thread: AsyncFlush-3
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:zold-io/zold#113] declared for identity constraint of element "verbosity".
```

[0.23.6](https://github.com/zerocracy/farm): CID: [1791334931](https://www.0crat.com/CAZPZR9FS/1791334931), Type: "Close job", Author: "yegor256"

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @botanicus[/z](https://www.0crat.com/u/botanicus), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#113](https://github.com/zold-io/zold/issues/113) is now out of scope

**Comment by botanicus** [comment]
@yegor256 _The job #113 is now out of scope_.(^) Is this a problem?

**Comment by yegor256** [comment]
@botanicus this is how it should be. The job is closed. Now it will be validated by our QA and paid.

**Comment by botanicus** [comment]
@ypshenychka https://github.com/zold-io/zold/pull/294

**Comment by ypshenychka** [comment]
@botanicus thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
