### ISSUE TITLE
Remote command is not working

### ISSUE THREAD

**Issue by g4s8** [zold-io/zold#116]
`zold --help` shows:
```
Available commands:
    remote command [options]
      Manage remote nodes
```
but command `remote` is not working or not documented:
```
$ zold remote
ERROR: Unknown command '' (RuntimeError)
$ zold remote help
ERROR: Unknown command 'help' (RuntimeError)
$ zold remote list
ERROR: Unknown command 'list' (RuntimeError)
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C91QJT4CF) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@g4s8 try `zold remote --help`

**Comment by 0crat** [comment]
Job [#116](https://github.com/yegor256/zold/issues/116) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@yegor256 thanks, it's working

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by g4s8** [comment]
@yegor256 maybe it's better to show this message (`try zold remote --help`) instead of `RuntimeError`?

**Comment by 0crat** [comment]
The job [#116](https://github.com/yegor256/zold/issues/116) is now out of scope

**Comment by yegor256** [comment]
@g4s8 fixed in d0e304b

**Comment by g4s8** [comment]
@yegor256 thanks

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
