### ISSUE TITLE
.rubocop.yml:35-38: Let's get rid of this and find a way...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/zold#125]
The puzzle `64-220d800a` from #64 has to be resolved:

https://github.com/zold-io/zold/blob/d0e304b2142bc0e2e03a9a64a444c90144015762/.rubocop.yml#L35-L38

The puzzle was created by Yegor Bugayenko on 02-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
I'm not managing `zold-io/zold` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) I'm not managing this repo, remove the [webhook](https://github.com/zold-io/zold/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `zold-io/zold` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Job [#125](https://github.com/zold-io/zold/issues/125) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#125](https://github.com/zold-io/zold/issues/125) assigned to @ilyaumanets[/z](https://www.0crat.com/u/ilyaumanets), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1561134158); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `64-220d800a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ilyaumanets[/z](https://www.0crat.com/u/ilyaumanets), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#125](https://github.com/zold-io/zold/issues/125) is now out of scope

**Comment by ypshenychka** [comment]
@IlyaUmanets According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Ticket must have references to all pull requests where the problem was actually fixed.

Please reference the correpsonding PR in this issue, so everyone's aware in which pull request the problem was solved.

**Comment by ypshenychka** [comment]
@IlyaUmanets ping

**Comment by ypshenychka** [comment]
@IlyaUmanets Please consider my above [remark](https://github.com/zold-io/zold/issues/125#issuecomment-394810875).

**Comment by ypshenychka** [comment]
@IlyaUmanets You won't be paid fot this job unless you make appropriate corrections by referring the PR here.

**Comment by ypshenychka** [comment]
@yegor256 Please advise about quality here. I don't see any PR and @IlyaUmanets doesn't repsond to my messages.

**Comment by ypshenychka** [comment]
@yegor256 ping

**Comment by ypshenychka** [comment]
@yegor256 any advice here? bad or acceptable?

**Comment by yegor256** [comment]
@ypshenychka it's acceptable, I believe

**Comment by ypshenychka** [comment]
@yegor256 Thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @ilyaumanets[/z](https://www.0crat.com/u/ilyaumanets)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
