### ISSUE TITLE
redeploy

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#126]
Let's release from a new repo.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) I'm not managing this repo, remove the [webhook](https://github.com/zold-io/zold/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `zold-io/zold` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release, tag is `0.10.18`

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
