### ISSUE TITLE
Wallet.open() instead of find()

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#129]
Let's change the way we manage a wallet. Instead of `wallet.find()` let's do:

```ruby
wallet.open do
  # manipulate the wallet
end
```

This will make it possible in the future to keep wallets in the database, see #60

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#129](https://github.com/zold-io/zold/issues/129), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
The job [#129](https://github.com/zold-io/zold/issues/129) assigned to @tsuhachev[/z](https://www.0crat.com/u/tsuhachev), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/2ba49736-7542-4e83-b6da-9b1025e76eec); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@tsuhachev[/z](https://www.0crat.com/u/tsuhachev) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by tsuhachev** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/zold-io/zold/issues/129#issuecomment-435899782))

@tsuhachev The impediment for [#129](https://github.com/zold-io/zold/issues/129) was registered successfully by @tsuhachev[/z](https://www.0crat.com/u/tsuhachev)

**Comment by tsuhachev** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/zold/issues/129#issuecomment-438343902))

@tsuhachev The user @tsuhachev[/z](https://www.0crat.com/u/tsuhachev) resigned from [#129](https://github.com/zold-io/zold/issues/129), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @tsuhachev[/z](https://www.0crat.com/u/tsuhachev)

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#129` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#129](https://github.com/zold-io/zold/issues/129) is now out of scope
