### ISSUE TITLE
UPGRADE

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#130]
Let's make it possible to upgrade a wallet to a higher/current version:

```
$ zold upgrade aaaabbbbccccdddd
```

Let's create a directory with "upgrades", which will be `.rb` scripts/classes to modify a wallet file.

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#130](https://github.com/zold-io/zold/issues/130), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by yegor256** [comment]
done already

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#130` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#130](https://github.com/zold-io/zold/issues/130) is now out of scope
