### ISSUE TITLE
ping back before adding to remotes

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#132]
At the moment, inside `front.rb/before` we add all incoming nodes to the list of remotes, if their score is good enough. This is not safe, since some of them may be not available online, even though may connect to us. Let's do a callback to make sure the node is online. Let's make it the functionality `zold remote add` does by default. When it's called, it validates the node, by pinging it. 

We should have an ability to skip this by using `--skip-ping`.

**Comment by 0crat** [comment]
Job [#132](https://github.com/zold-io/zold/issues/132) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @vl3

**Comment by 0crat** [comment]
> @0crat assign @vl3 ([here](https://github.com/zold-io/zold/issues/132#issuecomment-397369119))

@yegor256 The job [#132](https://github.com/zold-io/zold/issues/132) assigned to @vl3[/z](https://www.0crat.com/u/vl3), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1651727567); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@vl3[/z](https://www.0crat.com/u/vl3) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.39`

**Comment by yegor256** [comment]
@vl3 I made a temporary fix, but it only checks the `/version` URL and it's not tested. Let's make sure it is covered by test and checks `/`, validating the JSON and the presence of the "score" in it.

**Comment by 0crat** [comment]
The user @vl3[/z](https://www.0crat.com/u/vl3) resigned from [#132](https://github.com/zold-io/zold/issues/132), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @vl3[/z](https://www.0crat.com/u/vl3)

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#132](https://github.com/zold-io/zold/issues/132), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#132` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#132](https://github.com/zold-io/zold/issues/132) is now out of scope
