### ISSUE TITLE
there is no unit test for regular update

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#133]
There is a regular update thread in `node.rb`, which we don't test anyhow. We don't know whether it works or not. Let's create a test.

**Comment by 0crat** [comment]
Job [#133](https://github.com/zold-io/zold/issues/133) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#133` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#133](https://github.com/zold-io/zold/issues/133) is now out of scope
