### ISSUE TITLE
version "0.10.17" does not auto-update and add itself to remotes list

### ISSUE THREAD

**Issue by ajdevy** [zold-io/zold#135]
Since yesterday 2 June Morning (GMT) I upped a node with the following data, which is still alive:

```
{
  "version": "0.10.17",
  "score": {
    "value": 0,
    "host": "46.23.36.72",
    "port": 4096,
    "invoice": "kBfuZFUb@dd3db33775ae3db3",
    "time": "2018-06-03T07:02:01Z",
    "suffixes": [

    ],
    "strength": 6,
    "hash": null,
    "minutes": 0
  },
  "pid": 3700,
  "cpus": 4,
  "uptime": "10:02:20 up 22:42,  1 user,  load average: 1.06, 1.11, 1.12",
  "wallets": 1,
  "remotes": 2,
  "farm": {
    "threads": 4,
    "scores": 2848,
    "best": 4
  },
  "date": "2018-06-03T07:02:21+00:00",
  "hours_alive": 0.01,
  "home": "https://www.zold.io"
}
```

The node did not auto-update and add itself to the remotes list. Remotes at the time of issue creation: 

```
"all": [
    {
      "host": "b1.zold.io",
      "port": 80,
      "score": 0,
      "errors": 0,
      "home": "http://b1.zold.io/"
    },
    {
      "host": "b2.zold.io",
      "port": 4096,
      "score": 0,
      "errors": 0,
      "home": "http://b2.zold.io:4096/"
    },
    {
      "host": "127.0.0.1",
      "port": 4096,
      "score": 0,
      "errors": 0,
      "home": "http://127.0.0.1:4096/"
    },
    {
      "host": "66.70.202.35",
      "port": 4096,
      "score": 0,
      "errors": 0,
      "home": "http://66.70.202.35:4096/"
    },
    {
      "host": "138.201.231.23",
      "port": 4096,
      "score": 0,
      "errors": 0,
      "home": "http://138.201.231.23:4096/"
    }
  ]
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ajdevy[/z](https://www.0crat.com/u/ajdevy) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@ajdevy how do you start it? Can you show command line text?

**Comment by ajdevy** [comment]
the command is started from crontab @reboot entry
"/usr/local/bin/zold node --trace --verbose --invoice=dd3db33775ae3db3 --host=46.23.36.72 --dir=/home/n0n3/"

**Comment by ajdevy** [comment]
@yegor256

**Comment by yegor256** [comment]
@ajdevy this issue has been resolved, try version 0.13.12 and check the latest README

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#135` is not assigned, can't get performer
