### ISSUE TITLE
front - show wallet balance

### ISSUE THREAD

**Issue by oltdaniel** [zold-io/zold#136]
Show at `/wallet/:wallet_id:/balance` to current held amount of Zold for the wallet.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#136](https://github.com/zold-io/zold/issues/136) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @oltdaniel[/z](https://www.0crat.com/u/oltdaniel)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#136](https://github.com/zold-io/zold/issues/136); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by byzantime** [comment]
Looks like this been implemented:  https://github.com/zold-io/zold/commit/51b2b8c3b4421007a38e18f7012dd57889b02c05

**Comment by yegor256** [comment]
@oltdaniel @byzantime yes, it works: http://b2.zold.io:4096/wallet/912ecc24b32dbe74/balance

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#136` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#136](https://github.com/zold-io/zold/issues/136) is now out of scope
