### ISSUE TITLE
front - get all wallets loaded by the node

### ISSUE THREAD

**Issue by oltdaniel** [zold-io/zold#137]
Show every wallet in a list at `/wallets`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@oltdaniel there could be (and will be) thousands of them. I don't think we should show their full list here. What this is for?

**Comment by oltdaniel** [comment]
@yegor256 An idea for ranking the addresses, or make it easier for third parties to generate address lists.

**Comment by 0crat** [comment]
Job [#137](https://github.com/zold-io/zold/issues/137) is now in scope, role is `DEV`

**Comment by yegor256** [comment]
@oltdaniel let's show the first 256 and then stop.

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @oltdaniel[/z](https://www.0crat.com/u/oltdaniel)

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#137](https://github.com/zold-io/zold/issues/137), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
The score of @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) -270 is too low and will be reset: +270 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by yegor256** [comment]
@oltdaniel that would be a very time/space/traffic consuming operation. We won't do that.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#137` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#137](https://github.com/zold-io/zold/issues/137) is now out of scope
