### ISSUE TITLE
51% attack - attacker can delete transactions

### ISSUE THREAD

**Issue by oltdaniel** [zold-io/zold#138]
If the attacker owns 51% of the network power, he can delete transactions from the wallets, without signing them with the encryption keys.

**Solution 1:**
Refuse changes to the wallet, if the pushed content is smaller than the one on the node.

**Solution 2:**
Refuse changes, if the `sha256` hash of the wallet, signed by the owner, is different to the current calculated one by the node.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@oltdaniel let's implement the first solution

**Comment by 0crat** [comment]
Job [#138](https://github.com/zold-io/zold/issues/138) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @oltdaniel[/z](https://www.0crat.com/u/oltdaniel)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#138](https://github.com/zold-io/zold/issues/138); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@0crat assign @mulev

**Comment by 0crat** [comment]
> @0crat assign @mulev ([here](https://github.com/zold-io/zold/issues/138#issuecomment-394455550))

@yegor256 The job [#138](https://github.com/zold-io/zold/issues/138) assigned to @mulev[/z](https://www.0crat.com/u/mulev), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1551856147); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by vizotov** [comment]
The chosen solution will prevent "double spending" transactions resolution. Nodes with conflicting transactions will stay in a inconsistent state.
IMO, 51% attacker can change data. There is no solutions on it.

**Comment by 0crat** [comment]
@mulev[/z](https://www.0crat.com/u/mulev) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @mulev[/z](https://www.0crat.com/u/mulev) resigned from [#138](https://github.com/zold-io/zold/issues/138), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @mulev[/z](https://www.0crat.com/u/mulev)

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#138](https://github.com/zold-io/zold/issues/138), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#138](https://github.com/zold-io/zold/issues/138) assigned to @babbarkrishan[/z](https://www.0crat.com/u/babbarkrishan), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/2dfdaf45-dbf2-42ee-b512-6e19063fddf2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The job [#138](https://github.com/zold-io/zold/issues/138) assigned to @baybatu[/z](https://www.0crat.com/u/baybatu), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/8b4614db-2d60-4686-8844-eaa3a08d19d3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@baybatu[/z](https://www.0crat.com/u/baybatu) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@oltdaniel this is not possible anymore, thanks to the `--legacy` option

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/zold/issues/138#issuecomment-476266345))

@yegor256 The user @baybatu[/z](https://www.0crat.com/u/baybatu) resigned from [#138](https://github.com/zold-io/zold/issues/138), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#138` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#138](https://github.com/zold-io/zold/issues/138) is now out of scope
