### ISSUE TITLE
Remotes.iterate should track slow performance

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#139]
Let's track the speed of operations in `Remotes.iterate`. If a remote takes longer than 16 seconds -- it's an error, let's record it.

**Comment by 0crat** [comment]
Job [#139](https://github.com/zold-io/zold/issues/139) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @mulev

**Comment by 0crat** [comment]
> @0crat assign @mulev ([here](https://github.com/zold-io/zold/issues/139#issuecomment-394455500))

@yegor256 The job [#139](https://github.com/zold-io/zold/issues/139) assigned to @mulev[/z](https://www.0crat.com/u/mulev), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1551856137); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@mulev[/z](https://www.0crat.com/u/mulev) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @mulev[/z](https://www.0crat.com/u/mulev) resigned from [#139](https://github.com/zold-io/zold/issues/139), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @mulev[/z](https://www.0crat.com/u/mulev)

**Comment by yegor256** [comment]
@0crat assign @pbenety

**Comment by 0crat** [comment]
> @0crat assign @pbenety ([here](https://github.com/zold-io/zold/issues/139#issuecomment-397402455))

@yegor256 The job [#139](https://github.com/zold-io/zold/issues/139) assigned to @pbenety[/z](https://www.0crat.com/u/pbenety), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1651882311); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@pbenety[/z](https://www.0crat.com/u/pbenety) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by pbenety** [comment]
@0crat waiting for review #273

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@9798703e-08c9-4be4-bbc6-c3d809a0890c, thread: pool-34-thread-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: 98c60ca0aa2e/9min/0/2/true/false by <disposed>
```

[0.22.31](https://github.com/zerocracy/farm): Issue: zold-io/zold#139, Comment: 399246033

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@9798703e-08c9-4be4-bbc6-c3d809a0890c, thread: pool-34-thread-1
com.zerocracy.radars.github.ReSafe[82] java.io.IOException: java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: 98c60ca0aa2e/9min/0/2/true/false by <disposed>
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: 98c60ca0aa2e/9min/0/2/true/false by <disposed>
```

[0.22.31](https://github.com/zerocracy/farm): Issue: zold-io/zold#139, Action: `created`

**Comment by pbenety** [comment]
@0crat waiting for review #273

**Comment by 0crat** [comment]
> @0crat waiting for review #273 ([here](https://github.com/zold-io/zold/issues/139#issuecomment-399279719))

@pbenety The impediment for [#139](https://github.com/zold-io/zold/issues/139) was registered successfully by @pbenety[/z](https://www.0crat.com/u/pbenety)

**Comment by pbenety** [comment]
@yegor256 please close this issue. The PR #273 was merged.

**Comment by yegor256** [comment]
@pbenety thanks!

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +38 point(s) just awarded to @pbenety[/z](https://www.0crat.com/u/pbenety)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
