### ISSUE TITLE
all scores are zero in /remotes

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#142]
For some reason all remote nodes have zero scores in http://b2.zold.io:4096/remotes

**Comment by 0crat** [comment]
Job [#142](https://github.com/zold-io/zold/issues/142) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
It's a normal temporal situation

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#142` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#142](https://github.com/zold-io/zold/issues/142) is now out of scope
