### ISSUE TITLE
Random awards to nodes

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#143]
Let's introduce a new background thread, which will _every hour_ go through the list of remote nodes and pick a random one. Then, it will download its score. If the score is above 16, it will send 1 ZLD to its invoice. The details of the payment will sound like: `Node keeping alive reward:  4.4.4.4:4096`.

Then, when the same invoice is found, we should check the history of transactions within the last 24 hours and if a similar payment to the same invoice already exists, we should not pay again.

Thus, a node will receive 1 ZLD per day as a maximum.

Of course, all of this should happen only if a private key of the paying wallet exists in `config.yml` (this will happen only in one node: b1.zold.io).

**Comment by 0crat** [comment]
Job [#143](https://github.com/zold-io/zold/issues/143) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @ilyaumanets

**Comment by 0crat** [comment]
> @0crat assign @ilyaumanets ([here](https://github.com/zold-io/zold/issues/143#issuecomment-394676504))

@yegor256 The job [#143](https://github.com/zold-io/zold/issues/143) assigned to @ilyaumanets[/z](https://www.0crat.com/u/ilyaumanets), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1561138251); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@assign me

**Comment by yegor256** [comment]
@rultor release, tag is `0.11.17`

**Comment by yegor256** [comment]
@rultor release, tag is `0.11.18`

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ilyaumanets[/z](https://www.0crat.com/u/ilyaumanets), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#143](https://github.com/zold-io/zold/issues/143) is now out of scope

**Comment by ypshenychka** [comment]
@yegor256 According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
1. >Problem reporter and problem solver are two different persons
2. >Ticket must have references to all pull requests where the problem was actually fixed

You solve the problem you reported though another person is assigned to do it. And you didn't reference any PR here. Quality here will be bad since the assigned person haven't done any work here.

Please confirm you'll try to follow the rules next time.

**Comment by ypshenychka** [comment]
@yegor256 Ping

**Comment by ypshenychka** [comment]
@yegor256 Please consider my above [remark](https://github.com/zold-io/zold/issues/143#issuecomment-396029912).

**Comment by yegor256** [comment]
@ypshenychka yes, I completed that. The quality is bad here

**Comment by ypshenychka** [comment]
@yegor256 Thank you!

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
