### ISSUE TITLE
It would be better to use scriyt instead of sha256 for PoW

### ISSUE THREAD

**Issue by vizotov** [zold-io/zold#144]
It would be better to use *scriyt* instead of *sha256*, because it is much more difficult to make mining parallel. This will avoid a hard division into miners and users, as happened in Bitcoin. For example, scrypt is used in Litecoin.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@vizotov[/z](https://www.0crat.com/u/vizotov) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@vizotov sha256 is much more difficult or scriyt? Can you please provide a link to prove this point. A very good point, actually.

**Comment by vizotov** [comment]
It contains the sha256 algorithm as a stage. I think it's not much more complicated computationally, but as I understand the scrypt requires a lot of RAM, so it's harder for it to create specialized hardware that speeds up computations by parallelizing. Therefore, mining is available on "normal" hardware.
https://en.wikipedia.org/wiki/Scrypt

**Comment by yegor256** [comment]
@vizotov this ticket belongs to this repo now: https://github.com/zold-io/zold-score Please, re-submit it there.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#144` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
