### ISSUE TITLE
raise if host name is localhost

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#146]
Very often people make a mistake when they start a node, not providing the `--host` argument or simply providing `--host=127.0.0.1`. Let's check the `host` name in `node.rb` and raise an exception if it's `localhost` or `127.0.0.1`.

**Comment by yegor256** [comment]
@0crat assign @oltdaniel

**Comment by 0crat** [comment]
Job [#146](https://github.com/zold-io/zold/issues/146) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
> @0crat assign @oltdaniel  ([here](https://github.com/zold-io/zold/issues/146#issuecomment-394712372))

@yegor256 The job [#146](https://github.com/zold-io/zold/issues/146) assigned to @oltdaniel[/z](https://www.0crat.com/u/oltdaniel), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1561344811); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@oltdaniel[/z](https://www.0crat.com/u/oltdaniel) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/zold/issues/146#issuecomment-397003359))

@yegor256 Job `gh:zold-io/zold#146` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#146` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#146](https://github.com/zold-io/zold/issues/146) is now out of scope
