### ISSUE TITLE
'zold create' should generate new key pair for each wallet.

### ISSUE THREAD

**Issue by DronMDF** [zold-io/zold#147]
Use one key for several wallet is strange...

```
@@ -1,5 +1,5 @@
 zold
 0.10.19
-e982fb2fc5da5d78
+67c19c300cdecc12
 MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzuE1nVoXtYJg...
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dronmdf[/z](https://www.0crat.com/u/dronmdf) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@DronMDF well, it's up to the user what keys to use. For me it's convenient to have same keys for all my wallets. It's out of our control. We give user all necessary instruments to either switch keys or use the same pair.

**Comment by DronMDF** [comment]
There are options, then ok.
Sorry.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
