### ISSUE TITLE
Wrong b2.zold.io:4096 score

### ISSUE THREAD

**Issue by DronMDF** [zold-io/zold#148]
```
$ zold fetch e982fb2fc5da5d78
b1.zold.io:80 returned 424b/0 of e982fb2fc5da5d78 (0.10.19) in 0.18s
b2.zold.io:4096: Expired score 21/6: 2018-06-04T07:40:38Z b2.zold.io 4096 gldU1M1g@00000000000ff1ce 20aee1d 536302 3223a7 33175f7 108a156 1eb4dde 1aa7b11 357b7e 2a8f9b 6cbeba 599771 903655 54f5e4 145ffae 421b8 178773 6fc601 5bb1ae a28f50 1a8731 4bd152

dron@mdf-work:~/zold$ echo -n '2018-06-04T07:40:38Z b2.zold.io 4096 gldU1M1g@00000000000ff1ce 20aee1d' | sha256sum
95e18a8bb53b95588e8ee978df5ed5cc7fb5b1d9225a3ac515206122f0000004  -
```
....25a3ac515206122f**0000004** <--

If try to check next - I do not see zeros at all

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dronmdf[/z](https://www.0crat.com/u/dronmdf) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by DronMDF** [comment]
```ruby
    def hash
      raise 'Score has zero value, there is no hash' if @suffixes.empty?
      @suffixes.reduce(prefix) do |pfx, suffix|
        Digest::SHA256.hexdigest(pfx + ' ' + suffix)[0, 63]
      end
    end
```
Why [0, 63]?
Second square braces arg - is length.
hash has 64 bytes.

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @dronmdf[/z](https://www.0crat.com/u/dronmdf)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@DronMDF fixed in c9e80aa

**Comment by yegor256** [comment]
@rultor release, tag is `0.11.10`

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#148](https://github.com/zold-io/zold/issues/148) is now out of scope
