### ISSUE TITLE
background threads are not stable

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#155]
I assume that sometimes our background threads (like the one that does `remote update`) fail and stop. We have to find a better more safe way to run background processes and make sure they never stop. Let's investigate and maybe use some existing Ruby gem for that.

**Comment by yegor256** [comment]
@0crat assign @oltdaniel

**Comment by 0crat** [comment]
> @0crat assign @oltdaniel  ([here](https://github.com/zold-io/zold/issues/155#issuecomment-395012214))

@yegor256 The job [#155](https://github.com/zold-io/zold/issues/155) assigned to @oltdaniel[/z](https://www.0crat.com/u/oltdaniel), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1570951123); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@oltdaniel[/z](https://www.0crat.com/u/oltdaniel) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @oltdaniel[/z](https://www.0crat.com/u/oltdaniel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#155](https://github.com/zold-io/zold/issues/155) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
