### ISSUE TITLE
/wallet/ID/pull

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#157]
Let's add a new entry point, which will do the `pull` of the wallet and immediately return 202. The operation must be executed in a background thread. Let's make sure those thread don't conflict and are synchronized somehow.

**Comment by 0crat** [comment]
Job [#157](https://github.com/zold-io/zold/issues/157) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by DronMDF** [comment]
GET /wallet/ID not suitable for this purpose?

**Comment by yegor256** [comment]
@DronMDF `/wallet/ID` will return 404 is the wallet is not available in the node.

**Comment by DronMDF** [comment]
@yegor256 This command for inter-node synchronization? 
For what it can be necessary?
Let the client connect to another node.
Nodes in the background are synchronized themselves.

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#157](https://github.com/zold-io/zold/issues/157), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by yegor256** [comment]
@DronMDF you are right, we don't need this

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#157` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#157](https://github.com/zold-io/zold/issues/157) is now out of scope
