### ISSUE TITLE
/wallet/ID/txns

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#158]
Let's add a new JSON RESTful API entry point, which will return wallet transactions. Query arguments:

  * `prefix`: if specified, we should return only those that have this prefix
  * `id_start`: the ID to start from (inclusive)
  * `id_finish`: the ID to finish at (exclusive)
  * `time_start`: the ISO8601 time to start from (inclusive)
  * `time_finish`: the ISO8601 time to finish at (exclusive)

If the wallet is absent we should return 404.

**Comment by 0crat** [comment]
Job [#158](https://github.com/zold-io/zold/issues/158) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#158](https://github.com/zold-io/zold/issues/158), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
The job [#158](https://github.com/zold-io/zold/issues/158) assigned to @vl3[/z](https://www.0crat.com/u/vl3), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/8172c0ae-6774-43ff-8c29-a4c08db5348b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@vl3[/z](https://www.0crat.com/u/vl3) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@vl3 this is done already

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/zold/issues/158#issuecomment-476267279))

@yegor256 The user @vl3[/z](https://www.0crat.com/u/vl3) resigned from [#158](https://github.com/zold-io/zold/issues/158), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#158` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#158](https://github.com/zold-io/zold/issues/158) is now out of scope
