### ISSUE TITLE
Add instructions for Debian to INSTALL.md

### ISSUE THREAD

**Issue by byzantime** [zold-io/zold#159]
There should be instructions for installing Zold on Debian.

The instructions for Ubuntu / AWS don't adequately cover installation on Debian.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@byzantime[/z](https://www.0crat.com/u/byzantime) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@byzantime can you please submit a pull request?

**Comment by byzantime** [comment]
@yegor256 absolutely.  Was going to submit a PR but thought maybe I need to create an issue first.

**Comment by byzantime** [comment]
PR adding instructions merged.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
