### ISSUE TITLE
File extension for wallets

### ISSUE THREAD

**Issue by llorllale** [zold-io/zold#164]
It is best if we assign a standard file extension to wallet files, like `.z` (my favorite), or maybe `.zold`.

**Motivation**
Standardizing filename extensions is a standard practice and is widespread. Users and developers alike have the expectation that applications load by default only files with extensions that they recognize. 

Imagine for example the `WalletsInDir` example documented in the README for the [java-api](https://github.com/zold-io/java-api): the user just happened to have some random README.txt file in the same directory as his wallets then some error is likely to be thrown later on as the files are iterated and parsed.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#164](https://github.com/zold-io/zold/issues/164) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by yegor256** [comment]
@0crat assign @pbenety

**Comment by 0crat** [comment]
> @0crat assign @pbenety ([here](https://github.com/zold-io/zold/issues/164#issuecomment-397402362))

@yegor256 The job [#164](https://github.com/zold-io/zold/issues/164) assigned to @pbenety[/z](https://www.0crat.com/u/pbenety), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1651881255); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@pbenety[/z](https://www.0crat.com/u/pbenety) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by pbenety** [comment]
@0crat waiting for review #282

**Comment by 0crat** [comment]
> @0crat waiting for review #282 ([here](https://github.com/zold-io/zold/issues/164#issuecomment-399573438))

@pbenety The impediment for [#164](https://github.com/zold-io/zold/issues/164) was registered successfully by @pbenety[/z](https://www.0crat.com/u/pbenety)

**Comment by pbenety** [comment]
@llorllale please close this isssue. The PR #282 was merged.

**Comment by llorllale** [comment]
@pbenety thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @pbenety[/z](https://www.0crat.com/u/pbenety), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#164](https://github.com/zold-io/zold/issues/164) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +38 point(s) just awarded to @pbenety[/z](https://www.0crat.com/u/pbenety)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
