### ISSUE TITLE
RuntimeError when attempting to run node

### ISSUE THREAD

**Issue by byzantime** [zold-io/zold#168]
When running the following command I received a RuntimeError.  Running on Debian 9.4 x64.  Not much else to go on unfortunately.
```
$ zold --trace --verbose --invoice=ceda7c5ff887de31 --host=46.101.148.53
ERROR: A command required, try --help (RuntimeError)
/var/lib/gems/2.3.0/gems/zold-0.10.21/bin/zold:112:in `<top (required)>'
/usr/local/bin/zold:23:in `load'
/usr/local/bin/zold:23:in `<main>'
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@byzantime[/z](https://www.0crat.com/u/byzantime) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by byzantime** [comment]
Looks like it's due to incorrect syntax.  Created a PR to address.

**Comment by yegor256** [comment]
@byzantime thanks, the PR has been merged

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#168` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
