### ISSUE TITLE
Ruby version 2.5.1 is not valid

### ISSUE THREAD

**Issue by DronMDF** [zold-io/zold#170]
In [How to use](https://github.com/zold-io/zold#how-to-use) write 2.3+.

```
$ bundle update
Your Ruby version is 2.5.1, but your Gemfile specified 2.3.3
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dronmdf[/z](https://www.0crat.com/u/dronmdf) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@DronMDF fixed in aaffc4c thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#170` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by DronMDF** [comment]
@yegor256 sHaving problems?
