### ISSUE TITLE
ignore itself on push

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#172]
Node should ignore itself on push

**Comment by yegor256** [comment]
@rultor release, tag is `0.11.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.11.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.11.4`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#172` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
