### ISSUE TITLE
http.rb must be reactive

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#176]
At the moment we are spending a lot of time on waiting for remote nodes. Instead, we should make `http.rb` reactive. See also #81

**Comment by 0crat** [comment]
Job [#176](https://github.com/zold-io/zold/issues/176) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#176](https://github.com/zold-io/zold/issues/176), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/zold-io/zold/issues/176#issuecomment-409238122))

@KuxaBeast Job `gh:zold-io/zold#176` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#176](https://github.com/zold-io/zold/issues/176) assigned to @mulev[/z](https://www.0crat.com/u/mulev), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/2561009977); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by emilianodellacasa** [comment]
@0crat wait - this issue seems to be assigned to two different users, opening an issue

**Comment by 0crat** [comment]
> @0crat wait - this issue seems to be assigned to two different users, opening an issue ([here](https://github.com/zold-io/zold/issues/176#issuecomment-422699207))

@emilianodellacasa The impediment for [#176](https://github.com/zold-io/zold/issues/176) was registered successfully by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zold-io/zold/issues/176#issuecomment-422711052))

@g4s8 This is what I know about this job in [CAZPZR9FS](https://www.0crat.com/p/CAZPZR9FS), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#176](https://github.com/zold-io/zold/issues/176) is [in scope](http://www.zerocracy.com/policy.html#14) for 3mon
  * The role is `DEV`
  * The job is assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) for [16hr](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) will get 50% of their hourly rate for this job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
    * @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa): User was resigned from the ticket
    * @kuxabeast[/z](https://www.0crat.com/u/kuxabeast): User was resigned from the ticket
    * @mulev[/z](https://www.0crat.com/u/mulev): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CAZPZR9FS?q=%7Bjob%3A%27gh%3Azold-io%2Fzold%23176%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by emilianodellacasa** [comment]
@yegor256 What does it mean to make "http.rb more reactive"? Is it something related to its speed and performance or do you have something specific in mind?

**Comment by yegor256** [comment]
@emilianodellacasa would be great to make it work like this:

```
Http.new().get() do |res|
  # process the result in a new thread
end
```

I'm not sure whether we need it now though...

**Comment by emilianodellacasa** [comment]
@yegor256 If you think this issue is not needed anymore we can close it, I won't mind

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#176` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#176](https://github.com/zold-io/zold/issues/176) is now out of scope
