### ISSUE TITLE
wallets comparison is broken

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#184]
Logs:

```
Wallet 25d46e810279a448 is new: 768b != 768b
Wallet 2bd06ac0103ac090 is new: 768b != 768b
Accepted 2bd06ac0103ac090 in 0.18s and modified nothing (this is most likely a bug!)
Accepted 25d46e810279a448 in 0.22s and modified nothing (this is most likely a bug!)
Wallet 2bd06ac0103ac090 is new: 768b != 768b
Wallet 6facc8f1ca3e04f1 is new: 768b != 768b
```

I tried to fix this in #183, but the problem is still there

**Comment by 0crat** [comment]
Job [#184](https://github.com/zold-io/zold/issues/184) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#184` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#184](https://github.com/zold-io/zold/issues/184) is now out of scope
