### ISSUE TITLE
zold taxes show/debt doesn't not work (Wrong number of args for Wallets::find)

### ISSUE THREAD

**Issue by DronMDF** [zold-io/zold#188]
```
$ zold --verbose --trace taxes debt
ERROR: At least one wallet ID is required (RuntimeError)
/var/lib/gems/2.5.0/gems/zold-0.11.14/lib/zold/commands/taxes.rb:71:in `run'
/var/lib/gems/2.5.0/gems/zold-0.11.14/bin/zold:163:in `<top (required)>'
/usr/local/bin/zold:23:in `load'
/usr/local/bin/zold:23:in `<main>'

$ zold --verbose --trace taxes debt cc53e22229564de6 
ERROR: wrong number of arguments (given 2, expected 1) (ArgumentError)
/var/lib/gems/2.5.0/gems/zold-0.11.14/lib/zold/wallets.rb:58:in `find'
/var/lib/gems/2.5.0/gems/zold-0.11.14/lib/zold/commands/taxes.rb:73:in `block in run'
/var/lib/gems/2.5.0/gems/zold-0.11.14/lib/zold/commands/taxes.rb:72:in `each'
/var/lib/gems/2.5.0/gems/zold-0.11.14/lib/zold/commands/taxes.rb:72:in `run'
/var/lib/gems/2.5.0/gems/zold-0.11.14/bin/zold:163:in `<top (required)>'
/usr/local/bin/zold:23:in `load'
/usr/local/bin/zold:23:in `<main>'
```
I think 'pay' command broken too...

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dronmdf[/z](https://www.0crat.com/u/dronmdf) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
The job [#188](https://github.com/zold-io/zold/issues/188) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1601686330); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#188` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @dronmdf[/z](https://www.0crat.com/u/dronmdf)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@DronMDF fixed in 863145e

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#188](https://github.com/zold-io/zold/issues/188) is now out of scope
