### ISSUE TITLE
test redeployment

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#197]
Let's properly test the redeployment mechanism

**Comment by yegor256** [comment]
@rultor release, tag is `0.13`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.0`

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#197` is not assigned, can't get performer
