### ISSUE TITLE
zold taxes show still doesn't work

### ISSUE THREAD

**Issue by DronMDF** [zold-io/zold#198]
zold version is 0.12.1
zold taxes debt fixed by #188 

```
$ zold --verbose --trace taxes show ff96a73c5d6a7a30
ERROR: wrong number of arguments (given 2, expected 1) (ArgumentError)
/var/lib/gems/2.5.0/gems/zold-0.12.1/lib/zold/wallets.rb:58:in `find'
/var/lib/gems/2.5.0/gems/zold-0.12.1/lib/zold/commands/taxes.rb:68:in `block in run'
/var/lib/gems/2.5.0/gems/zold-0.12.1/lib/zold/commands/taxes.rb:67:in `each'
/var/lib/gems/2.5.0/gems/zold-0.12.1/lib/zold/commands/taxes.rb:67:in `run'
/var/lib/gems/2.5.0/gems/zold-0.12.1/bin/zold:163:in `<top (required)>'
/usr/local/bin/zold:23:in `load'
/usr/local/bin/zold:23:in `<main>'
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dronmdf[/z](https://www.0crat.com/u/dronmdf) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.1`

**Comment by yegor256** [comment]
@DronMDF fixed

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#198` is not assigned, can't get performer
