### ISSUE TITLE
clean up the list of semaphores in Entrance

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#199]
The list of them will grow with the growing amount of wallets processed. Let's clean up the map regularly to avoid its size to grow over 1024.

**Comment by 0crat** [comment]
Job [#199](https://github.com/zold-io/zold/issues/199) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @pbenety

**Comment by 0crat** [comment]
> @0crat assign @pbenety ([here](https://github.com/zold-io/zold/issues/199#issuecomment-397401339))

@yegor256 The job [#199](https://github.com/zold-io/zold/issues/199) assigned to @pbenety[/z](https://www.0crat.com/u/pbenety), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1651877061); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@pbenety[/z](https://www.0crat.com/u/pbenety) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by pbenety** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/zold/issues/199#issuecomment-399710204))

@pbenety The user @pbenety[/z](https://www.0crat.com/u/pbenety) resigned from [#199](https://github.com/zold-io/zold/issues/199), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @pbenety[/z](https://www.0crat.com/u/pbenety)

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#199](https://github.com/zold-io/zold/issues/199), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
The job [#199](https://github.com/zold-io/zold/issues/199) assigned to @baybatu[/z](https://www.0crat.com/u/baybatu), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/2050651426); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@baybatu[/z](https://www.0crat.com/u/baybatu) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/zold/issues/199#issuecomment-440249002))

@yegor256 The user @baybatu[/z](https://www.0crat.com/u/baybatu) resigned from [#199](https://github.com/zold-io/zold/issues/199), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#199` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#199](https://github.com/zold-io/zold/issues/199) is now out of scope
