### ISSUE TITLE
Farm threads can't exit and cause the process to wait

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#206]
Farm threads are staying in a waiting mode for too long

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.7`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.7`

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#206` is not assigned, can't get performer
