### ISSUE TITLE
metronome dies if there is an exception

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#208]
Let's fix it

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.8`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.8`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.8`

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#208` is not assigned, can't get performer
