### ISSUE TITLE
bonus payment is broken

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#210]
Let's test properly

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.10`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.11`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.11`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.11`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.11`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.11`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.11`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.11`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.11`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.11`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#210` is not assigned, can't get performer
