### ISSUE TITLE
Remotes::Remote must un-error on success

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#211]
At the moment we call `error` if something happens with the remote node. Let's do `unerror()` if there are no accidents/exceptions. Also, that `unerror` must not lower the number below zero.

**Comment by 0crat** [comment]
Job [#211](https://github.com/zold-io/zold/issues/211) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @pbenety

**Comment by 0crat** [comment]
> @0crat assign @pbenety ([here](https://github.com/zold-io/zold/issues/211#issuecomment-397401291))

@yegor256 The job [#211](https://github.com/zold-io/zold/issues/211) assigned to @pbenety[/z](https://www.0crat.com/u/pbenety), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1651877042); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@pbenety[/z](https://www.0crat.com/u/pbenety) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by pbenety** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/zold/issues/211#issuecomment-399710209))

@pbenety The user @pbenety[/z](https://www.0crat.com/u/pbenety) resigned from [#211](https://github.com/zold-io/zold/issues/211), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @pbenety[/z](https://www.0crat.com/u/pbenety)

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#211](https://github.com/zold-io/zold/issues/211), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
The score of @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) -315 is too low and will be reset: +315 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
The job [#211](https://github.com/zold-io/zold/issues/211) assigned to @oltdaniel[/z](https://www.0crat.com/u/oltdaniel), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/2070935550); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by oltdaniel** [comment]
@yegor256 `unerror` is lowering the `errors` counter or is a totally new information of the remote in the remotes list?

**Comment by oltdaniel** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@oltdaniel just decrement the errors counters by one. That's all `unerror()` should do.

**Comment by 0crat** [comment]
The job [#211](https://github.com/zold-io/zold/issues/211) assigned to @lastk[/z](https://www.0crat.com/u/lastk), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/52797ebe-422e-4feb-a9dc-e1ff43d5e79e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@lastk[/z](https://www.0crat.com/u/lastk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by lastk** [comment]
I'm assuming wich every operation in `remotes` should trigger `unerror` if no errors occurred.

**Comment by lastk** [comment]
@yegor256 can you close this issue ?

**Comment by yegor256** [comment]
@lastk thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @lastk[/z](https://www.0crat.com/u/lastk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#211](https://github.com/zold-io/zold/issues/211) is now out of scope

**Comment by ypshenychka** [comment]
@lastk According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to.

Please correct your [message](https://github.com/zold-io/zold/issues/211#issuecomment-450062858) by indicating an addressee in the beginning.

**Comment by ypshenychka** [comment]
@lastk I see you made some changes. Thank you. It would be helful if you notify me next time, so I could process ticket.

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @lastk[/z](https://www.0crat.com/u/lastk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
