### ISSUE TITLE
Failed to build zold gem in Windows (extconf.rb failed)

### ISSUE THREAD

**Issue by Dereek69** [zold-io/zold#213]
Hi, i'm trying to get a node running on windows 10 64 bit.
I installed Ruby with [RubyInstaller](https://www.ruby-lang.org/en/documentation/installation/#rubyinstaller), downloaded and installed [RubyGems](https://rubygems.org/pages/download) with `ruby setup.rb` , tried to install zold gem with `gem install --no-ri --no-rdoc zold`

This is the Powershell output when i try it
>PS C:\Users\deree> gem install --no-ri --no-rdoc zold
Temporarily enhancing PATH for MSYS/MINGW...
Installing required msys2 packages: mingw-w64-x86_64-openssl
warning: mingw-w64-x86_64-openssl-1.0.2.o-1 is up to date and it will be ignored
Building native extensions. This could take a while...
ERROR:  Error installing zold:
        ERROR: Failed to build gem native extension.
    current directory: F:/Program Files/Ruby24-x64/lib/ruby/gems/2.4.0/gems/openssl-2.1.1/ext/openssl
"F:/Program Files/Ruby24-x64/bin/ruby.exe" -r ./siteconf20180612-13988-1i2505g.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=F:/Program Files/Ruby24-x64/bin/$(RUBY_BASE_NAME)
        --with-openssl-dir
        --without-openssl-dir
        --with-openssl-include
        --without-openssl-include=${openssl-dir}/include
        --with-openssl-lib
        --without-openssl-lib=${openssl-dir}/lib
        --with-kerberos-dir
        --without-kerberos-dir
        --with-kerberos-include
        --without-kerberos-include=${kerberos-dir}/include
        --with-kerberos-lib
        --without-kerberos-lib=${kerberos-dir}/lib
F:/Program Files/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from F:/Program Files/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:572:in `block in try_compile'
        from F:/Program Files/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:525:in `with_werror'
        from F:/Program Files/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:572:in `try_compile'
        from F:/Program Files/Ruby24-x64/lib/ruby/gems/2.4.0/gems/openssl-2.1.1/ext/openssl/deprecation.rb:5:in `deprecated_warning_flag'
        from extconf.rb:23:in `<main>'
To see why this extension failed to compile, please check the mkmf.log which can be found here:
  F:/Program Files/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/openssl-2.1.1/mkmf.log
extconf failed, exit code 1
Gem files will remain installed in F:/Program Files/Ruby24-x64/lib/ruby/gems/2.4.0/gems/openssl-2.1.1 for inspection.
Results logged to F:/Program Files/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/openssl-2.1.1/gem_make.out

And this is the content of mkmf.log file
> ===OpenSSL for Ruby configurator ===
"x86_64-w64-mingw32-gcc -o conftest.exe -I"F:/Program Files/Ruby24-x64/include/ruby-2.4.0/x64-mingw32" -I"F:/Program Files/Ruby24-x64/include/ruby-2.4.0"/ruby/backward -I"F:/Program Files/Ruby24-x64/include/ruby-2.4.0" -I. -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64  -march=x86-64 -mtune=generic -O2 -pipe conftest.c  -L. -L"F:/Program Files/Ruby24-x64/lib" -L. -pipe     -lx64-msvcrt-ruby240  -lgmp -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
F:/Program Files/Ruby24-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find F:/Program: No such file or directory
F:/Program Files/Ruby24-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find Files/Ruby24-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/lib/../lib/default-manifest.o: No such file or directory
collect2.exe: error: ld returned 1 exit status
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: int main(int argc, char **argv)
6: {
7:   return 0;
8: }
/* end */

I probably need some dependencies but i dont know how to get them or where to find them.
Thank you very much for any help :)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dereek69[/z](https://www.0crat.com/u/dereek69) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by Dereek69** [comment]
Found the problem and solved.
The install directory had a space in it and that caused the program to fail. Installed ruby in F:\Ruby instead of F:\Program Files\Ruby and it worked

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#213` is not assigned, can't get performer
