### ISSUE TITLE
test_front.rb:71-73: The test is skipped because it...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/zold#214]
The puzzle `212-37109e23` from #212 has to be resolved:

https://github.com/zold-io/zold/blob/9c31794f0300777312d1afe873798079ccb0aab1/test/node/test_front.rb#L71-L73

The puzzle was created by Yegor Bugayenko on 12-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#214](https://github.com/zold-io/zold/issues/214) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#214](https://github.com/zold-io/zold/issues/214), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
The job [#214](https://github.com/zold-io/zold/issues/214) assigned to @oltdaniel[/z](https://www.0crat.com/u/oltdaniel), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/2070955903); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by oltdaniel** [comment]
@0crat wait - cannot be done without solving #422

**Comment by 0crat** [comment]
> @0crat wait - cannot be done without solving #422 ([here](https://github.com/zold-io/zold/issues/214#issuecomment-408651411))

@oltdaniel The impediment for [#214](https://github.com/zold-io/zold/issues/214) was registered successfully by @oltdaniel[/z](https://www.0crat.com/u/oltdaniel)

**Comment by 0pdd** [comment]
The puzzle `212-37109e23` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@b01ef9f0-234e-4047-95fb-3e1710cd0ddf, thread: pool-21-thread-1
java.lang.NumberFormatException[65] java.lang.NumberFormatException: For input string: "2018-08-04T17:09:10.888Z"
```

[0.29.2](https://github.com/zerocracy/farm): Issue: zold-io/zold#214, Action: `closed`

**Comment by 0crat** [comment]
The job [#214](https://github.com/zold-io/zold/issues/214) is now out of scope

**Comment by 0crat** [comment]
@oltdaniel[/z](https://www.0crat.com/u/oltdaniel) resigned from [#214](https://github.com/zold-io/zold/issues/214), since the job is not in scope anymore
