### ISSUE TITLE
Can't read RSA key (Windows)

### ISSUE THREAD

**Issue by Dereek69** [zold-io/zold#219]
The gem was installed correctly, the rsa key was generated under `C:\Users\deree\.ssh\id_rsa.pub`
I get this error when i try to generate a wallet
The system is Windows 10 64bit

> F:\Flavio\Download\PGRM Installer\Programmi\Bitcoin\zold>zold --verbose --trace create --public-key C:\Users\deree\.ssh\id_rsa.pub
Load key "C:/Users/deree/AppData/Local/Temp/20180613-9852-1ik32qb": invalid format
ERROR: Can't read RSA key (Neither PUB key nor PRIV key: header too long):  (RuntimeError)
F:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/zold-0.13.16/lib/zold/key.rb:86:in 'rescue in rsa'
F:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/zold-0.13.16/lib/zold/key.rb:83:in 'rsa'
F:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/zold-0.13.16/lib/zold/key.rb:58:in 'to_s'
F:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/zold-0.13.16/lib/zold/key.rb:62:in 'to_pub'
F:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/zold-0.13.16/lib/zold/wallet.rb:82:in 'init'
F:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/zold-0.13.16/lib/zold/commands/create.rb:63:in 'create'
F:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/zold-0.13.16/lib/zold/commands/create.rb:55:in 'run'
F:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/zold-0.13.16/bin/zold:140:in '<top (required)>'
F:/Ruby24-x64/bin/zold:23:in 'load'
F:/Ruby24-x64/bin/zold:23:in '\<main>'

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dereek69[/z](https://www.0crat.com/u/dereek69) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@Dereek69 can you please attach your `id_rsa.pub` file here? It's a public key, don't worry about security.

**Comment by 0crat** [comment]
Job [#219](https://github.com/zold-io/zold/issues/219) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Thanks for your contribution, @dereek69[/z](https://www.0crat.com/u/dereek69)! If you would be a member of [the project](https://www.0crat.com/p/CAZPZR9FS), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by Dereek69** [comment]
[id_rsa.zip](https://github.com/zold-io/zold/files/2099333/id_rsa.zip)

**Comment by yegor256** [comment]
@0crat assign @vl3

**Comment by 0crat** [comment]
> @0crat assign @vl3 ([here](https://github.com/zold-io/zold/issues/219#issuecomment-397368757))

@yegor256 The job [#219](https://github.com/zold-io/zold/issues/219) assigned to @vl3[/z](https://www.0crat.com/u/vl3), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1651726494); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@vl3[/z](https://www.0crat.com/u/vl3) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @vl3[/z](https://www.0crat.com/u/vl3) resigned from [#219](https://github.com/zold-io/zold/issues/219), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @vl3[/z](https://www.0crat.com/u/vl3)

**Comment by yegor256** [comment]
@0crat assign @mgrassotti

**Comment by 0crat** [comment]
> @0crat assign @mgrassotti ([here](https://github.com/zold-io/zold/issues/219#issuecomment-400777791))

@yegor256 The job [#219](https://github.com/zold-io/zold/issues/219) assigned to @mgrassotti[/z](https://www.0crat.com/u/mgrassotti), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1781809000); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @mgrassotti[/z](https://www.0crat.com/u/mgrassotti) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@mgrassotti[/z](https://www.0crat.com/u/mgrassotti) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by mgrassotti** [comment]
Hi @Dereek69 I tried to recreate the issue on a Windows 10 machine, but I can't.
The command `zold --verbose --trace create --public-key .ssh/id_rsa.pub` seems to work fine for me.

Can I ask how did you generated the ssh keys?
I would recommend the following steps:
1. Download & Install Git for Windows (https://gitforwindows.org/)

2. Add the path to `ssh-keygen` to your `PATH` environment variable:
    - Open the command prompt 
    - type `$ path=%PATH%;c:\Program Files\Git\usr\bin`

3. launch `$ ssh-keygen -t rsa -b 4096` to generate your keys, as indicated in https://github.com/zold-io/zold/blob/master/README.md

4. launch `$ zold --verbose --trace create --public-key .ssh\id_rsa.pub` from your current user directory

You should receive a message like this: 
```
345678asdqwe123sadjas
Wallet 345678asdqwe123sadjas created at C:/Users/<user_name>

**Comment by mgrassotti** [comment]
Hi @Dereek69, could you please either comment or close the ticket? Thanks

**Comment by 0crat** [comment]
The user @mgrassotti[/z](https://www.0crat.com/u/mgrassotti) resigned from [#219](https://github.com/zold-io/zold/issues/219), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @mgrassotti[/z](https://www.0crat.com/u/mgrassotti)

**Comment by KuxaBeast** [comment]
Hello @Dereek69, is this issue still actual? I tried to recreate this exception with no luck, just like @mgrassotti did. If you are still experiencing this problem try to thoroughly repeat installation steps just like @mgrassotti mentioned above. Reply or close the issue, please.

**Comment by yegor256** [comment]
@Dereek69 I'm closing this. If you see the problem again, please open a new one

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @kuxabeast[/z](https://www.0crat.com/u/kuxabeast), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#219](https://github.com/zold-io/zold/issues/219) is now out of scope

**Comment by ypshenychka** [comment]
@KuxaBeast I will have to mark this ticket as "bad quality", as it was closed without a solution provided.

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)
