### ISSUE TITLE
Zold::Invoice should do Zold::Pull first, if the wallet is absent

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#220]
`Zold::Invoice` should do `Zold::Pull` first, if the wallet is absent

**Comment by 0crat** [comment]
Job [#220](https://github.com/zold-io/zold/issues/220) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @vl3

**Comment by 0crat** [comment]
> @0crat assign @vl3 ([here](https://github.com/zold-io/zold/issues/220#issuecomment-397368694))

@yegor256 The job [#220](https://github.com/zold-io/zold/issues/220) assigned to @vl3[/z](https://www.0crat.com/u/vl3), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1651726491); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@vl3[/z](https://www.0crat.com/u/vl3) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @vl3[/z](https://www.0crat.com/u/vl3) resigned from [#220](https://github.com/zold-io/zold/issues/220), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @vl3[/z](https://www.0crat.com/u/vl3)

**Comment by yegor256** [comment]
@0crat assign @ledestin

**Comment by 0crat** [comment]
> @0crat assign @ledestin ([here](https://github.com/zold-io/zold/issues/220#issuecomment-400292475))

@yegor256 The job [#220](https://github.com/zold-io/zold/issues/220) assigned to @ledestin[/z](https://www.0crat.com/u/ledestin), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1771250670); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@ledestin[/z](https://www.0crat.com/u/ledestin) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by ledestin** [comment]
@yegor256 I want to do `Pull.new(...).run`, but it requires `remotes` and `copies` that aren't passed to `Invoice`. Are there globals or should I require them for `Invoice`?

**Comment by yegor256** [comment]
@ledestin global variables are evil, we don't have at all. Of course, you should add them to the constructor.

**Comment by ledestin** [comment]
@yegor256 Filed a bug https://github.com/zold-io/zold/pull/319/commits/19c78029d1bc725b2ee5dafc9e3c8effb020ba57

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/zold-io/zold/issues/220#issuecomment-402403781))

@ledestin The impediment for [#220](https://github.com/zold-io/zold/issues/220) was registered successfully by @ledestin[/z](https://www.0crat.com/u/ledestin)

**Comment by yegor256** [comment]
@ledestin thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ledestin[/z](https://www.0crat.com/u/ledestin), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#220](https://github.com/zold-io/zold/issues/220) is now out of scope

**Comment by ypshenychka** [comment]
@ledestin According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Ticket must have references to all pull requests where the problem was actually fixed

Please add a reference to corresponding PR.

**Comment by ledestin** [comment]
@ypshenychka sorry, no longer interested

**Comment by ypshenychka** [comment]
@ledestin Are you not interested in getting paid for this?

**Comment by ledestin** [comment]
@ypshenychka nope. I'd agree for the money to go to you, if you fix this ticket.

**Comment by ypshenychka** [comment]
@ledestin I'm afraid that's not the case. Okay then. Since I don't see what job was actually done here, I must mark it as bad. Thanks.

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
