### ISSUE TITLE
show execution time in case of error in Remotes::Remote

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#221]
Every time we report an error in `Remotes.iterate` let's add the time in seconds to the log

**Comment by 0crat** [comment]
Job [#221](https://github.com/zold-io/zold/issues/221) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @vl3

**Comment by 0crat** [comment]
> @0crat assign @vl3 ([here](https://github.com/zold-io/zold/issues/221#issuecomment-397368632))

@yegor256 The job [#221](https://github.com/zold-io/zold/issues/221) assigned to @vl3[/z](https://www.0crat.com/u/vl3), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1651725435); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@vl3[/z](https://www.0crat.com/u/vl3) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @vl3[/z](https://www.0crat.com/u/vl3) resigned from [#221](https://github.com/zold-io/zold/issues/221), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @vl3[/z](https://www.0crat.com/u/vl3)

**Comment by 0crat** [comment]
Job [#221](https://github.com/zold-io/zold/issues/221) is not in the agenda of @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), can't inspect

**Comment by 0crat** [comment]
The job [#221](https://github.com/zold-io/zold/issues/221) is now out of scope

**Comment by ypshenychka** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zold-io/zold/issues/221#issuecomment-428504215))

@ypshenychka This is what I know about this job in [CAZPZR9FS](https://www.0crat.com/p/CAZPZR9FS), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#221](https://github.com/zold-io/zold/issues/221) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 3mon
  * @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CAZPZR9FS?q=%7Bjob%3A%27gh%3Azold-io%2Fzold%23221%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@vl3 According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues 

Your commit doesn't contain link to this issue. Plese confirm you'll try to avoid this mistake in future.

**Comment by ypshenychka** [comment]
@vl3 ping

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
