### ISSUE TITLE
remote trim --tolerate=0

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#222]
Let's add a new option `--tolerate` which will say what is the maximum level of errors we are ready to tolerate. If the remote has a higher level, we remove it. At the moment we are using `Remote::TOLERATE` always.

**Comment by 0crat** [comment]
Job [#222](https://github.com/zold-io/zold/issues/222) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @sandiks

**Comment by 0crat** [comment]
> @0crat assign @sandiks ([here](https://github.com/zold-io/zold/issues/222#issuecomment-397300167))

@yegor256 The job [#222](https://github.com/zold-io/zold/issues/222) assigned to @sandiks[/z](https://www.0crat.com/u/sandiks), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1651353224); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @sandiks[/z](https://www.0crat.com/u/sandiks) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @vl3

**Comment by 0crat** [comment]
> @0crat assign @vl3 ([here](https://github.com/zold-io/zold/issues/222#issuecomment-397368545))

@yegor256 The job [#222](https://github.com/zold-io/zold/issues/222) assigned to @vl3[/z](https://www.0crat.com/u/vl3), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1651725414); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@vl3[/z](https://www.0crat.com/u/vl3) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @vl3[/z](https://www.0crat.com/u/vl3) resigned from [#222](https://github.com/zold-io/zold/issues/222), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @vl3[/z](https://www.0crat.com/u/vl3)

**Comment by yegor256** [comment]
@0crat assign @mgrassotti

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/zold/issues/222#issuecomment-400777563))

@yegor256 Job `gh:zold-io/zold#222` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat assign @mgrassotti ([here](https://github.com/zold-io/zold/issues/222#issuecomment-400777472))

@yegor256 The job [#222](https://github.com/zold-io/zold/issues/222) assigned to @mgrassotti[/z](https://www.0crat.com/u/mgrassotti), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1781808997); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @mgrassotti[/z](https://www.0crat.com/u/mgrassotti) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @mgrassotti[/z](https://www.0crat.com/u/mgrassotti), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#222](https://github.com/zold-io/zold/issues/222) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
> @0crat quality bad ([here](https://github.com/zold-io/zold/issues/222#issuecomment-400796025))

@ypshenychka There is no quality review for [#222](https://github.com/zold-io/zold/issues/222), no performer

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
