### ISSUE TITLE
Appveyor build is broken: openssl is not found

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#231]
See https://ci.appveyor.com/project/yegor256/zold-wcn4o Let's fix it.

**Comment by 0crat** [comment]
Job [#231](https://github.com/zold-io/zold/issues/231) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#231](https://github.com/zold-io/zold/issues/231), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
The job [#231](https://github.com/zold-io/zold/issues/231) assigned to @kuxabeast[/z](https://www.0crat.com/u/kuxabeast), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/2071932287); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/zold-io/zold/issues/231#issuecomment-409238229))

@KuxaBeast Job `gh:zold-io/zold#231` is not assigned, can't get performer

**Comment by emilianodellacasa** [comment]
@yegor256 Please assign this issue to me

**Comment by emilianodellacasa** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@0crat assign @emilianodellacasa

**Comment by emilianodellacasa** [comment]
@yegor256 Is there a reason why we are using a Windows OS for Appveyor?

**Comment by emilianodellacasa** [comment]
@yegor256 This issue is not assigned to me, could you please try again?

**Comment by emilianodellacasa** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@0crat assign @emilianodellacasa

**Comment by yegor256** [comment]
@emilianodellacasa Appveyor is designed to test in Windows OS

**Comment by 0crat** [comment]
> @0crat assign @emilianodellacasa  ([here](https://github.com/zold-io/zold/issues/231#issuecomment-411361663))

@yegor256 The job [#231](https://github.com/zold-io/zold/issues/231) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/2201035516); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by emilianodellacasa** [comment]
@yegor256 This issue has been solved on PR #443, please close this issue

**Comment by emilianodellacasa** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@emilianodellacasa thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#231](https://github.com/zold-io/zold/issues/231) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
