### ISSUE TITLE
list of modified IDs is not getting emptified

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#232]
In `Entrance.rb` we have a list of wallet ID-s in `@modified`. If you look at a front page of any node, you will see that they have large numbers in the size of this array. This is wrong. The array should be empty when the node is staying quiet.

Check any node from this map: http://www.zold.io/map.html

**Comment by 0crat** [comment]
Job [#232](https://github.com/zold-io/zold/issues/232) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#232](https://github.com/zold-io/zold/issues/232) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1691404429); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @yegor256[/z](https://www.0crat.com/u/yegor256) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.31`

**Comment by yegor256** [comment]
fixed in 4f54c33

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#232](https://github.com/zold-io/zold/issues/232) is now out of scope
