### ISSUE TITLE
Spread.rb must not be random

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#235]
Now `spread.rb` is taking random wallets from the list and pushes them to the network. This is not a reliable algorithms, since many wallets may stay non-pushed for a long time, while others will be spread many times. Let's do something more predictable. Maybe keeping a list of recently pushed wallets somewhere in the array and don't push them again. If we keep that list in a fixed size, we will be sure that until we push the required amount of wallets, we won't duplicate.

**Comment by 0crat** [comment]
Job [#235](https://github.com/zold-io/zold/issues/235) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#235](https://github.com/zold-io/zold/issues/235), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
The job [#235](https://github.com/zold-io/zold/issues/235) assigned to @mulev[/z](https://www.0crat.com/u/mulev), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/2561017036); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by yegor256** [comment]
It's gone

**Comment by 0crat** [comment]
The job [#235](https://github.com/zold-io/zold/issues/235) is now out of scope
