### ISSUE TITLE
test_front.rb:87-90: This tests is skipped since it...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/zold#241]
The puzzle `239-8451ca17` from #239 has to be resolved:

https://github.com/zold-io/zold/blob/504a4272be4a1394302d8ce1fa14e97dab05b404/test/node/test_front.rb#L87-L90

The puzzle was created by Yegor Bugayenko on 15-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#241](https://github.com/zold-io/zold/issues/241) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#241](https://github.com/zold-io/zold/issues/241), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0pdd** [comment]
The puzzle `239-8451ca17` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#241` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#241](https://github.com/zold-io/zold/issues/241) is now out of scope
