### ISSUE TITLE
Zold::Pay should do Zold::Pull if the paying wallet is absent

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#248]
Let's do the pull if the wallet is absent. Let's make it possible to disable it with `--skip-pull`.

**Comment by 0crat** [comment]
Job [#248](https://github.com/zold-io/zold/issues/248) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#248](https://github.com/zold-io/zold/issues/248), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
The job [#248](https://github.com/zold-io/zold/issues/248) assigned to @lastk[/z](https://www.0crat.com/u/lastk), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/7428e181-2681-4dc6-a129-6f96cb279603); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@lastk[/z](https://www.0crat.com/u/lastk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by lastk** [comment]
@0crat resign

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/zold-io/zold/issues/248#issuecomment-475963057))

@lastk The user @lastk[/z](https://www.0crat.com/u/lastk) resigned from [#248](https://github.com/zold-io/zold/issues/248), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @lastk[/z](https://www.0crat.com/u/lastk)

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@lastk this is done already

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/zold/issues/248#issuecomment-476265477))

@yegor256 Job `gh:zold-io/zold#248` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#248` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#248](https://github.com/zold-io/zold/issues/248) is now out of scope
