### ISSUE TITLE
too many similar scores in the BEST

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#250]
They look very similar, taking into account their `age` values. We have to get rid of those that stay close to each other.

<img width="715" alt="screen shot 2018-06-18 at 2 35 49 pm" src="https://user-images.githubusercontent.com/526301/41533865-eb77ea82-7304-11e8-9e59-584b4e0420f1.png">

Here it's obvious that there is no need to work on `6:279m` and `6:255m` at the same time. It's better to drop one of them, since 279 and 255 are very close to each other. We must work only with ages that are unique in ranges "24 / threads". If there are 4 threads, we should deal with one score per 6 hours.

I believe the problem is that we are using `@pipeline` and the list of scores independently. I think it should be done differently.

**Comment by 0crat** [comment]
The job [#250](https://github.com/zold-io/zold/issues/250) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1691207881); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @yegor256[/z](https://www.0crat.com/u/yegor256) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#250` already assigned to @yegor256, can't assign to @yegor256

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.27`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.28`

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#250](https://github.com/zold-io/zold/issues/250) is now out of scope
