### ISSUE TITLE
TestZold#test_all_scripts  failure

### ISSUE THREAD

**Issue by sandiks** [zold-io/zold#252]
Failure:
TestZold#test_all_scripts [test/test_zold.rb:49]:
push-and-pull.sh.
Expected: 0
  Actual: 65280

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@sandiks I believe it's fine now, thanks

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#252` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
