### ISSUE TITLE
NohupLog.print must be synchronized

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#256]
At the moment the log sometimes gets broken lines, because they clash when coming from different threads. Let's make sure the log is synchronized.

**Comment by 0crat** [comment]
Job [#256](https://github.com/zold-io/zold/issues/256) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @vl3

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@62c94ee0-47b0-4040-a917-bc85e86ebac6, thread: pool-152-thread-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: e52044b7d4bb/6min/0/3/true/false by QuartzScheduler_Worker-8
```

[0.22.21](https://github.com/zerocracy/farm): Issue: zold-io/zold#256, Comment: 398973757

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#256](https://github.com/zold-io/zold/issues/256), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
The job [#256](https://github.com/zold-io/zold/issues/256) assigned to @theterminalguy[/z](https://www.0crat.com/u/theterminalguy), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/62c616fc-ba9a-4df3-b09b-919cc9f2269d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@theterminalguy[/z](https://www.0crat.com/u/theterminalguy) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@theterminalguy this is done already

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/zold/issues/256#issuecomment-476265700))

@yegor256 The user @theterminalguy[/z](https://www.0crat.com/u/theterminalguy) resigned from [#256](https://github.com/zold-io/zold/issues/256), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#256` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#256](https://github.com/zold-io/zold/issues/256) is now out of scope
