### ISSUE TITLE
Remotes.iterate in multiple threads

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#260]
Let's do `Remotes.iterate` in multiple threads. Also, let's make sure `Remotes` is a thread safe class. At the moment it sometimes crashes if, for example, `error` is called many times from different threads.

For example:

```
RuntimeError: localhost:35765 is absent among 24 remotes
/app/lib/zold/remotes.rb:195:in `error'
	/app/lib/zold/remotes.rb:172:in `rescue in block in iterate'
	/app/lib/zold/remotes.rb:168:in `block in iterate'
	/app/lib/zold/remotes.rb:167:in `each'
	/app/lib/zold/remotes.rb:167:in `iterate'
	/app/lib/zold/commands/fetch.rb:71:in `fetch'
	/app/lib/zold/commands/fetch.rb:62:in `block in run'
	/app/lib/zold/commands/fetch.rb:61:in `each'
	/app/lib/zold/commands/fetch.rb:61:in `run'
	/app/lib/zold/commands/pull.rb:41:in `run'
	/app/lib/zold/commands/routines/bonuses.rb:55:in `block in exec'
	/app/lib/zold/commands/routines/bonuses.rb:54:in `each'
	/app/lib/zold/commands/routines/bonuses.rb:54:in `exec'
	/app/lib/zold/metronome.rb:58:in `block (3 levels) in start'
	/app/lib/zold/metronome.rb:55:in `loop'
	/app/lib/zold/metronome.rb:55:in `block (2 levels) in start'
```

**Comment by 0crat** [comment]
Job [#260](https://github.com/zold-io/zold/issues/260) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @vl3

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@62c94ee0-47b0-4040-a917-bc85e86ebac6, thread: pool-144-thread-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: e52044b7d4bb/4min/0/4/true/false by QuartzScheduler_Worker-8
```

[0.22.21](https://github.com/zerocracy/farm): Issue: zold-io/zold#260, Comment: 398973723

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@62c94ee0-47b0-4040-a917-bc85e86ebac6, thread: pool-144-thread-1
com.zerocracy.radars.github.ReSafe[82] java.io.IOException: java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: e52044b7d4bb/4min/0/4/true/false by QuartzScheduler_Worker-8
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: e52044b7d4bb/4min/0/4/true/false by QuartzScheduler_Worker-8
```

[0.22.21](https://github.com/zerocracy/farm): Issue: zold-io/zold#260, Action: `created`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@62c94ee0-47b0-4040-a917-bc85e86ebac6, thread: pool-152-thread-1
com.zerocracy.radars.github.ReSafe[82] java.io.IOException: java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: e52044b7d4bb/6min/0/3/true/false by QuartzScheduler_Worker-8
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: e52044b7d4bb/6min/0/3/true/false by QuartzScheduler_Worker-8
```

[0.22.21](https://github.com/zerocracy/farm): Issue: zold-io/zold#260, Action: `created`

**Comment by yegor256** [comment]
@0crat assign @vl3

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.38`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#260` already assigned to @vl3, can't assign to @yegor256

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@a3164daf-d45d-4aea-9d64-81995b096aea, thread: AsyncFlush-6
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "verbosity/vl3.xml" in "PMO" in 2min: b39ba5f0e021/11min/0/2/true/false by AsyncFlush-5
```

[0.22.21](https://github.com/zerocracy/farm): CID: [1720621084](https://www.0crat.com/CAZPZR9FS/1720621084), Type: "Close job", Author: "yegor256"

**Comment by 0crat** [comment]
The job [#260](https://github.com/zold-io/zold/issues/260) is now out of scope

**Comment by ypshenychka** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zold-io/zold/issues/260#issuecomment-428504088))

@ypshenychka This is what I know about this job in [CAZPZR9FS](https://www.0crat.com/p/CAZPZR9FS), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#260](https://github.com/zold-io/zold/issues/260) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 4mon
  * @vl3[/z](https://www.0crat.com/u/vl3) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CAZPZR9FS?q=%7Bjob%3A%27gh%3Azold-io%2Fzold%23260%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@yegor256 You self-assigned your own issue and didn't submit any PR for review. Please confirm you'll try to avoid such mistakes in future.

**Comment by ypshenychka** [comment]
@yegor256 ping

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @vl3[/z](https://www.0crat.com/u/vl3)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
