### ISSUE TITLE
push queue is not getting emptied

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#262]
`modified` stays high

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#264](https://github.com/zold-io/zold/issues/264) is still not solved.

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.35`

**Comment by yegor256** [comment]
@rultor stop

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#262` is not assigned, can't get performer

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@62c94ee0-47b0-4040-a917-bc85e86ebac6, thread: AsyncFlush-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "blanks/yegor256.xml" in "PMO" in 2min: e52044b7d4bb/8min/0/2/true/false by QuartzScheduler_Worker-8
```

[0.22.21](https://github.com/zerocracy/farm): CID: [1720304310](https://www.0crat.com/CAZPZR9FS/1720304310), Type: "Close job", Author: "yegor256"

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#264](https://github.com/zold-io/zold/issues/264) is solved here.
