### ISSUE TITLE
test_atomic_file.rb:45-48: This test is skipped because...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/zold#264]
The puzzle `262-ee9602d6` from #262 has to be resolved:

https://github.com/zold-io/zold/blob/bfcf79cfb573220cf29de6e04f6275cb713758ab/test/test_atomic_file.rb#L45-L48

The puzzle was created by Yegor Bugayenko on 21-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#264](https://github.com/zold-io/zold/issues/264) is now in scope, role is `DEV`

**Comment by yegor256** [comment]
@0crat assign @ledestin

**Comment by 0crat** [comment]
> @0crat assign @ledestin ([here](https://github.com/zold-io/zold/issues/264#issuecomment-400292359))

@yegor256 The job [#264](https://github.com/zold-io/zold/issues/264) assigned to @ledestin[/z](https://www.0crat.com/u/ledestin), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1771250651); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ledestin** [comment]
@yegor256 `flock` doesn't block in the same process, it's a tool to use for separate processes.

```
file = File.open('a.txt', 'w')                                               
file.flock(File::LOCK_EX)                                                    
file.flock(File::LOCK_EX) 
```

You'd think the code above would block, but it doesn't.

Proposed fix: via `#synchronize`. Overall, multithread-safe code should be synchronized.

**Comment by ledestin** [comment]
@0crat boost 3x

**Comment by yegor256** [comment]
@ledestin got it. Please, go ahead and fix it the way you see it should be done.

**Comment by ledestin** [comment]
@yegor256 https://github.com/zold-io/zold/pull/303

**Comment by 0pdd** [comment]
The puzzle `262-ee9602d6` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ledestin[/z](https://www.0crat.com/u/ledestin), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#264](https://github.com/zold-io/zold/issues/264) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +53 point(s) just awarded to @ledestin[/z](https://www.0crat.com/u/ledestin)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by ledestin** [comment]
@yegor256 I requested *boost 3x*, but got *2x*, according to 0crat Telegram.

**Comment by yegor256** [comment]
@ledestin you can't boost a task, only an architect or a product owner can do that. It was a bug in Zerocrat that it didn't inform you about access rights violation. When/if you want to boost a task, you should ask ARC or PO to do that, see: http://www.zerocracy.com/policy.html#5

**Comment by ledestin** [comment]
@yegor256 ok, so what should be done with this PR's boost? Should I request it now?

**Comment by yegor256** [comment]
@ledestin you can, of course, but I don't see a reason for a boost here. It's a pretty standard pull request.
