### ISSUE TITLE
patch is making mistakes

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#266]
`Patch` is making mistakes in some corner cases. Let's test, reproduce and fix.

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.35`

**Comment by yegor256** [comment]
@rultor stop

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@62c94ee0-47b0-4040-a917-bc85e86ebac6, thread: AsyncFlush-3
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "agenda/yegor256.xml" in "PMO" in 2min: e52044b7d4bb/4min/0/2/true/false by QuartzScheduler_Worker-8
```

[0.22.21](https://github.com/zerocracy/farm): CID: [1720421403](https://www.0crat.com/CAZPZR9FS/1720421403), Type: "Start order", Author: "yegor256"

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#266` is not assigned, can't get performer

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
