### ISSUE TITLE
positive and negative txns conflict by ID in Patch

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#267]
positive and negative txns conflict by ID in Patch

**Comment by yegor256** [comment]
@rultor merge, tag is `0.13.36`

**Comment by yegor256** [comment]
@rultor release, tag is 0.13.36

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#267` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#267](https://github.com/zold-io/zold/issues/267) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1720557019); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @yegor256[/z](https://www.0crat.com/u/yegor256) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) resigned from [#267](https://github.com/zold-io/zold/issues/267), since the job is not in scope anymore

**Comment by 0crat** [comment]
The job [#267](https://github.com/zold-io/zold/issues/267) is now out of scope
