### ISSUE TITLE
/wallet/id.txt

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#271]
Let's show it's text version

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.42`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@9509281b-b1e7-4a9b-8fd0-53540a3705c3, thread: pool-87-thread-1
java.util.concurrent.ThreadPoolExecutor$AbortPolicy[2063] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@1e27e78f rejected from java.util.concurrent.ThreadPoolExecutor@1fdc65f[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 15953]
```

[0.22.26](https://github.com/zerocracy/farm): Issue: zold-io/zold#271, Action: `closed`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@9f6c64e7-3621-4c53-a7db-c4ce7a5cf502, thread: AsyncFlush-4
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "blanks/yegor256.xml" in "PMO" in 2min: 57e5019db0b7/4min/0/4/true/false by zerocrat_bot Telegram Executor
```

[0.22.28](https://github.com/zerocracy/farm): CID: [1721348101](https://www.0crat.com/CAZPZR9FS/1721348101), Type: "Close job", Author: "yegor256"

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#271` is not assigned, can't get performer
