### ISSUE TITLE
prioritize requests in AsyncEntrance

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#275]
At the moment we process same wallets many times:

<img width="1420" alt="screen shot 2018-06-22 at 5 29 53 pm" src="https://user-images.githubusercontent.com/526301/41782134-0d9ea3ae-7642-11e8-9238-5eef238a0662.png">

I think it's not effective. Instead, we should keep a short-term history of requests in `AsyncEntrance` and  give priority to wallets that we haven't seen for a while. Others will go next.

**Comment by 0crat** [comment]
Job [#275](https://github.com/zold-io/zold/issues/275) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#275](https://github.com/zold-io/zold/issues/275), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
The job [#275](https://github.com/zold-io/zold/issues/275) assigned to @vl3[/z](https://www.0crat.com/u/vl3), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/af83221b-51cc-4a32-b4cf-587a320aa386); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@vl3[/z](https://www.0crat.com/u/vl3) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@vl3 this is done already

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/zold/issues/275#issuecomment-476265830))

@yegor256 The user @vl3[/z](https://www.0crat.com/u/vl3) resigned from [#275](https://github.com/zold-io/zold/issues/275), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#275` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#275](https://github.com/zold-io/zold/issues/275) is now out of scope
