### ISSUE TITLE
pro-active pulling of wallets

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#280]
A node has to have a decorated version of `Wallets`. Every time `find()` is called, it has to see whether the returned wallet exists. If it's not, it has to put it into the queue and attempt to pull, as soon as possible.

**Comment by 0crat** [comment]
Job [#280](https://github.com/zold-io/zold/issues/280) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @botanicus

**Comment by 0crat** [comment]
> @0crat assign @botanicus ([here](https://github.com/zold-io/zold/issues/280#issuecomment-399961685))

@yegor256 The job [#280](https://github.com/zold-io/zold/issues/280) assigned to @botanicus[/z](https://www.0crat.com/u/botanicus), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1761390640); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by botanicus** [comment]
@yegor256 can you please reference the class names? I don't want to be guessing which part of code to touch.

- node = ?
- queue = ?

So I'm supposed to create something like:

```ruby
class WalletsProActivePullingDecorator
  def initialize(wallets)
    @wallets = wallets
  end

  def find(id)
    unless @wallets.find(id)
      # TODO: Add to the queue. (Still not sure which queue.)
      # returns nil
    end
  end
end
```

**Comment by yegor256** [comment]
@botanicus I think we should create `HungryWallets` (why not) decorator, which will be instantiated in `node.rb` and will have its own internal pool, similar to what `SpreadEntrace` has. And it should do what you described above.

**Comment by 0crat** [comment]
@botanicus[/z](https://www.0crat.com/u/botanicus) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by botanicus** [comment]
@yegor256 please close.

**Comment by 0crat** [comment]
The user @botanicus[/z](https://www.0crat.com/u/botanicus) resigned from [#280](https://github.com/zold-io/zold/issues/280), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by yegor256** [comment]
@0crat assign @botanicus

**Comment by 0crat** [comment]
> @0crat assign @botanicus  ([here](https://github.com/zold-io/zold/issues/280#issuecomment-402774862))

@yegor256 The job [#280](https://github.com/zold-io/zold/issues/280) assigned to @botanicus[/z](https://www.0crat.com/u/botanicus), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1861616903); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job [#280](https://github.com/zold-io/zold/issues/280) is not in the agenda of @botanicus[/z](https://www.0crat.com/u/botanicus), can't inspect

**Comment by 0crat** [comment]
The job [#280](https://github.com/zold-io/zold/issues/280) is now out of scope

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zold-io/zold/issues/280#issuecomment-402997184))

@g4s8 This is what I know about this job in [CAZPZR9FS](https://www.0crat.com/p/CAZPZR9FS), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#280](https://github.com/zold-io/zold/issues/280) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 18hr
  * @botanicus[/z](https://www.0crat.com/u/botanicus) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CAZPZR9FS?q=%7Bjob%3A%27gh%3Azold-io%2Fzold%23280%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +38 point(s) just awarded to @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#333](https://github.com/zold-io/zold/issues/333) is solved here.
