### ISSUE TITLE
AsyncEntrance queue persistence

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#281]
Currently, the entire queue stays in memory. If we restart a node, everything is lost. This is a serious threat to stability. Let's preserve the queue on disc and restore it from there on start.

**Comment by 0crat** [comment]
Job [#281](https://github.com/zold-io/zold/issues/281) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @vl3

**Comment by 0crat** [comment]
> @0crat assign @vl3  ([here](https://github.com/zold-io/zold/issues/281#issuecomment-399728752))

@yegor256 The job [#281](https://github.com/zold-io/zold/issues/281) assigned to @vl3[/z](https://www.0crat.com/u/vl3), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1750479138); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@vl3[/z](https://www.0crat.com/u/vl3) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @vl3[/z](https://www.0crat.com/u/vl3) resigned from [#281](https://github.com/zold-io/zold/issues/281), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @vl3[/z](https://www.0crat.com/u/vl3)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@87be32ae-767e-4c81-b831-d8034fe0cd90, thread: pool-1193-thread-1
java.util.concurrent.ThreadPoolExecutor$AbortPolicy[2063] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@6da53daf rejected from java.util.concurrent.ThreadPoolExecutor@1e0dbd39[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1250718]
```

[0.25.2](https://github.com/zerocracy/farm): Issue: zold-io/zold#281, Comment: 403704747

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@87be32ae-767e-4c81-b831-d8034fe0cd90, thread: pool-1193-thread-1
com.zerocracy.radars.github.ReSafe[82] java.io.IOException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@6da53daf rejected from java.util.concurrent.ThreadPoolExecutor@1e0dbd39[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1250718]
java.util.concurrent.ThreadPoolExecutor$AbortPolicy[2063] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@6da53daf rejected from java.util.concurrent.ThreadPoolExecutor@1e0dbd39[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1250718]
```

[0.25.2](https://github.com/zerocracy/farm): Issue: zold-io/zold#281, Action: `created`

**Comment by yegor256** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zold-io/zold/issues/281#issuecomment-403704930))

@yegor256 The job [#281](https://github.com/zold-io/zold/issues/281) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1910530007); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @yegor256[/z](https://www.0crat.com/u/yegor256) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#281](https://github.com/zold-io/zold/issues/281) is now out of scope
