### ISSUE TITLE
Network JSON representation of wallets is not documented

### ISSUE THREAD

**Issue by llorllale** [zold-io/zold#283]
What is the JSON representation of wallets that is sent between nodes?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
moved to zold-io/papers#26

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#283` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
