### ISSUE TITLE
upgrade on start

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#285]
After releasing #282 all nodes will lose all wallets. This is unacceptable. Let's create a new routine, which will check the current version of files (let's keep in `.zoldata/version`) and compare it with the current one. Then, we should have a collection of `.rb` scripts in `upgrades/` directory. They should be executed one by one, for example:

```
upgrades/
  0.11.0.rb
  0.12.5.rb
  0.14.0.rb
```

When version jumps from, say, `0.12.46` to `0.14.0` -- the third script in this list will be executed. Let's create a script to rename all wallets, to make them have an extension required by #282 

After each successful (!) upgrade to the next version we have to modify the `.zoldata/version` file

If `.zoldata/version` is absent let's assume the version is `0.0.0`

I think we should run this upgrade routine automatically on each (!) start of the gem. Let's also introduce `--skip-upgrade` command line argument to disable this.

**Comment by 0crat** [comment]
Job [#285](https://github.com/zold-io/zold/issues/285) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @vl3

**Comment by 0crat** [comment]
> @0crat assign @vl3  ([here](https://github.com/zold-io/zold/issues/285#issuecomment-399728664))

@yegor256 The job [#285](https://github.com/zold-io/zold/issues/285) assigned to @vl3[/z](https://www.0crat.com/u/vl3), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1750478084); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@vl3 this is pretty urgent, since we can't release anything until this is fixed. Thanks!

**Comment by yegor256** [comment]
@0crat assign @botanicus

**Comment by yegor256** [comment]
@0crat boost 4x

**Comment by 0crat** [comment]
> @0crat boost 4x ([here](https://github.com/zold-io/zold/issues/285#issuecomment-400921250))

@yegor256 Boost 4x was set for [#285](https://github.com/zold-io/zold/issues/285)

**Comment by 0crat** [comment]
> @0crat assign @botanicus  ([here](https://github.com/zold-io/zold/issues/285#issuecomment-400921199))

@yegor256 The job [#285](https://github.com/zold-io/zold/issues/285) assigned to @botanicus[/z](https://www.0crat.com/u/botanicus), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1790615668); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by botanicus** [comment]
@yegor256 please close.

**Comment by yegor256** [comment]
@botanicus thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @botanicus[/z](https://www.0crat.com/u/botanicus), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#285](https://github.com/zold-io/zold/issues/285) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +38 point(s) just awarded to @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@yegor256 4 puzzles [#326](https://github.com/zold-io/zold/issues/326), [#327](https://github.com/zold-io/zold/issues/327), [#365](https://github.com/zold-io/zold/issues/365), [#366](https://github.com/zold-io/zold/issues/366) are still not solved.

**Comment by 0pdd** [comment]
@yegor256 3 puzzles [#326](https://github.com/zold-io/zold/issues/326), [#365](https://github.com/zold-io/zold/issues/365), [#366](https://github.com/zold-io/zold/issues/366) are still not solved; solved: [#327](https://github.com/zold-io/zold/issues/327).
