### ISSUE TITLE
root node public key validation

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#286]
Let's embed a validation of a public key of the root node. `Patch` should do that. Let's keep the root node public key in the repository and raise an exception if root node has a different key.

**Comment by 0crat** [comment]
Job [#286](https://github.com/zold-io/zold/issues/286) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @liligga

**Comment by yegor256** [comment]
@liligga let's make sure this happens only if `wallet.network` equals to `Wallet::MAIN_NETWORK`

**Comment by 0crat** [comment]
> @0crat assign @liligga ([here](https://github.com/zold-io/zold/issues/286#issuecomment-399746248))

@yegor256 The job [#286](https://github.com/zold-io/zold/issues/286) assigned to @liligga[/z](https://www.0crat.com/u/liligga), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1751040875); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @liligga[/z](https://www.0crat.com/u/liligga) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@liligga[/z](https://www.0crat.com/u/liligga) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @liligga[/z](https://www.0crat.com/u/liligga) resigned from [#286](https://github.com/zold-io/zold/issues/286), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @liligga[/z](https://www.0crat.com/u/liligga)

**Comment by 0crat** [comment]
The job [#286](https://github.com/zold-io/zold/issues/286) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/2791004066); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by emilianodellacasa** [comment]
@yegor256 I don't clearly understand what is it required in this issue; what is it supposed to be achieved? What's the reason of this validation?

**Comment by emilianodellacasa** [comment]
@0crat - waiting for an answer regarding the issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by emilianodellacasa** [comment]
@0crat wait - waiting for an answer regarding the issue

**Comment by 0crat** [comment]
> @0crat wait - waiting for an answer regarding the issue ([here](https://github.com/zold-io/zold/issues/286#issuecomment-428955794))

@emilianodellacasa The impediment for [#286](https://github.com/zold-io/zold/issues/286) was registered successfully by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by yegor256** [comment]
@yegor256 we have to make sure that public key of the root wallet (if the network is `zold`) is always the say (hardcoded in the repository).

**Comment by emilianodellacasa** [comment]
@yegor256 Maybe I should open an issue asking to document everything we need to know about this topic

**Comment by 0crat** [comment]
The job [#286](https://github.com/zold-io/zold/issues/286) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/77daf667-b713-4438-b9e4-38c33639ad54); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#286](https://github.com/zold-io/zold/issues/286) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
