### ISSUE TITLE
REMOTE UPDATE should limit the amount of nodes

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#292]
When we do `zold remote update` we fetch the entire list of remote nodes we can possibly find. If the network is big, this will create an overhead for the user, since it will push and pull to/from a large number of nodes. This is time consuming. Let's make sure `zole remote update` leaves just 16 nodes in the list, selecting the strongest ones. 

There should also be a command line argument `--max-nodes`, which is set to 16 by default. Setting it to, say, 10000 will make sure the node gets all nodes.

**Comment by 0crat** [comment]
Job [#292](https://github.com/zold-io/zold/issues/292) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @botanicus

**Comment by 0crat** [comment]
> @0crat assign @botanicus ([here](https://github.com/zold-io/zold/issues/292#issuecomment-399961531))

@yegor256 The job [#292](https://github.com/zold-io/zold/issues/292) assigned to @botanicus[/z](https://www.0crat.com/u/botanicus), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1761390643); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by botanicus** [comment]
https://github.com/zold-io/zold/pull/295

**Comment by 0crat** [comment]
@botanicus[/z](https://www.0crat.com/u/botanicus) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#328](https://github.com/zold-io/zold/issues/328), [#329](https://github.com/zold-io/zold/issues/329) are still not solved.

**Comment by yegor256** [comment]
@botanicus thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @botanicus[/z](https://www.0crat.com/u/botanicus), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#292](https://github.com/zold-io/zold/issues/292) is now out of scope

**Comment by ypshenychka** [comment]
@botanicus According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to.

Please correct your [message](https://github.com/zold-io/zold/issues/292#issuecomment-400203997) by indicating an addressee in the beginning.

**Comment by botanicus** [comment]
@ypshenychka fixed.

**Comment by ypshenychka** [comment]
@botanicus Thank you

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#328](https://github.com/zold-io/zold/issues/328), [#388](https://github.com/zold-io/zold/issues/388) are still not solved; solved: [#329](https://github.com/zold-io/zold/issues/329).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#328](https://github.com/zold-io/zold/issues/328) is still not solved; solved: [#329](https://github.com/zold-io/zold/issues/329), [#388](https://github.com/zold-io/zold/issues/388).
