### ISSUE TITLE
farm fails if FARM file contains garbage

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#297]
```
RuntimeError: Invalid score '0/6: 2018-06-26T00:32:43Z 178.128.165.12 4096 MIRhypo1@c13620484b46caa4  15e0cb 6be8b0 4849a8 305ae7d 9c30f4 e6d1e3 3b62ed 1281eb4 6b9173 449ef5', doesn't match: (?-mix:^([0-9]+)\/(?<strength>[0-9]+): (?<time>[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z) (?<host>[0-9a-z\.\-]+) (?<port>[0-9]+) (?<invoice>[a-zA-Z0-9]{8,32}@[a-f0-9]{16})(?<suffixes>( [a-zA-Z0-9]+)*)$)
 /var/lib/gems/2.3.0/gems/zold-0.13.46/lib/zold/score.rb:80:in `parse'
 /var/lib/gems/2.3.0/gems/zold-0.13.46/lib/zold/node/farm.rb:168:in `block (2 levels) in load'
 /var/lib/gems/2.3.0/gems/zold-0.13.46/lib/zold/node/farm.rb:168:in `map'
 /var/lib/gems/2.3.0/gems/zold-0.13.46/lib/zold/node/farm.rb:168:in `block in load'
 /var/lib/gems/2.3.0/gems/zold-0.13.46/lib/zold/node/farm.rb:166:in `synchronize'
 /var/lib/gems/2.3.0/gems/zold-0.13.46/lib/zold/node/farm.rb:166:in `load'
 /var/lib/gems/2.3.0/gems/zold-0.13.46/lib/zold/node/farm.rb:51:in `best'
 /var/lib/gems/2.3.0/gems/zold-0.13.46/lib/zold/node/front.rb:264:in `score'
 /var/lib/gems/2.3.0/gems/zold-0.13.46/lib/zold/node/front.rb:130:in `block in <class:Front>'
```

This must not happen. Instead, we should just ignore the score and report it via `@log.error()`

**Comment by 0crat** [comment]
Job [#297](https://github.com/zold-io/zold/issues/297) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @emilianodellacasa

**Comment by 0crat** [comment]
> @0crat assign @emilianodellacasa ([here](https://github.com/zold-io/zold/issues/297#issuecomment-400689600))

@yegor256 There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@b6bacaf1-6a1c-4350-8b12-c99321e58e43, thread: AsyncFlush-3
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value '$257.50 + €40.00' is not facet-valid with respect to pattern '0|([A-Z]{3} \-?|\-?($|€|£|¥))\d+(\.\d{1,2})?' for type 'cash'.;-1:-1: cvc-attribute.3: The value '$257.50 + €40.00' of attribute 'total' on element 'estimates' is not valid with respect to its type, 'cash'.
```

[0.23.3](https://github.com/zerocracy/farm): CID: [1781436273](https://www.0crat.com/CAZPZR9FS/1781436273), Type: "Start order", Author: "yegor256"

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @emilianodellacasa

**Comment by 0crat** [comment]
> @0crat assign @emilianodellacasa ([here](https://github.com/zold-io/zold/issues/297#issuecomment-400697322))

@yegor256 Job [#297](https://github.com/zold-io/zold/issues/297) is already assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/zold/issues/297#issuecomment-400744255))

@yegor256 The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#297](https://github.com/zold-io/zold/issues/297), please stop working. Reason for job resignation: Order was cancelled

**Comment by yegor256** [comment]
@0crat assign @emilianodellacasa

**Comment by 0crat** [comment]
> @0crat assign @emilianodellacasa ([here](https://github.com/zold-io/zold/issues/297#issuecomment-400778646))

@yegor256 There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@07414ffa-14ca-4340-b594-8ebf9e40e362, thread: AsyncFlush-1
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value '$1244.50 + €20.00' is not facet-valid with respect to pattern '0|([A-Z]{3} \-?|\-?($|€|£|¥))\d+(\.\d{1,2})?' for type 'cash'.;-1:-1: cvc-attribute.3: The value '$1244.50 + €20.00' of attribute 'total' on element 'estimates' is not valid with respect to its type, 'cash'.
```

[0.23.4](https://github.com/zerocracy/farm): CID: [1781811082](https://www.0crat.com/CAZPZR9FS/1781811082), Type: "Start order", Author: "yegor256"

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @emilianodellacasa

**Comment by 0crat** [comment]
> @0crat assign @emilianodellacasa ([here](https://github.com/zold-io/zold/issues/297#issuecomment-400793838))

@yegor256 Job [#297](https://github.com/zold-io/zold/issues/297) is already assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#297](https://github.com/zold-io/zold/issues/297), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by emilianodellacasa** [comment]
@yegor256 please assign this task back to me

**Comment by yegor256** [comment]
@0crat assign @emilianodellacasa

**Comment by 0crat** [comment]
> @0crat assign @emilianodellacasa  ([here](https://github.com/zold-io/zold/issues/297#issuecomment-403504092))

@yegor256 The job [#297](https://github.com/zold-io/zold/issues/297) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1901447780); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by emilianodellacasa** [comment]
@yegor256 PR has been merged, could you please close this issue?

**Comment by emilianodellacasa** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@emilianodellacasa thanks!

**Comment by yegor256** [comment]
@emilianodellacasa for the future, when you ask the author to close the issue, explicitly mention the PR(s) where the problem was solved.

**Comment by emilianodellacasa** [comment]
@yegor256 I certainly will, thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#297](https://github.com/zold-io/zold/issues/297) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +38 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
