### ISSUE TITLE
Remotes.error() should not fail if not found

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#298]
```
RuntimeError: 138.201.231.23:4096 is absent among 38 remotes
	/app/lib/zold/remotes.rb:208:in `error'
	/app/lib/zold/remotes.rb:184:in `rescue in block in iterate'
	/app/lib/zold/remotes.rb:180:in `block in iterate'
	/app/lib/zold/remotes.rb:178:in `each'
	/app/lib/zold/remotes.rb:178:in `iterate'
	/app/lib/zold/commands/remote.rb:194:in `update'
	/app/lib/zold/commands/remote.rb:110:in `run'
	/app/lib/zold/commands/routines/reconnect.rb:46:in `exec'
	/app/lib/zold/metronome.rb:59:in `block (2 levels) in start'
```

This is a regular exception. It's only logical that it happens, since the node may disappear from the list while update is running. I believe we should not fail in `error()` if the node is not found. Just silently return.

**Comment by 0crat** [comment]
Job [#298](https://github.com/zold-io/zold/issues/298) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign emilianodellacasa

**Comment by 0crat** [comment]
> @0crat assign @emilianodellacasa ([here](https://github.com/zold-io/zold/issues/298#issuecomment-400689476))

@yegor256 There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@b6bacaf1-6a1c-4350-8b12-c99321e58e43, thread: AsyncFlush-5
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value '$257.50 + €20.00' is not facet-valid with respect to pattern '0|([A-Z]{3} \-?|\-?($|€|£|¥))\d+(\.\d{1,2})?' for type 'cash'.;-1:-1: cvc-attribute.3: The value '$257.50 + €20.00' of attribute 'total' on element 'estimates' is not valid with respect to its type, 'cash'.
```

[0.23.3](https://github.com/zerocracy/farm): CID: [1781435259](https://www.0crat.com/CAZPZR9FS/1781435259), Type: "Start order", Author: "yegor256"

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @emilianodellacasa

**Comment by yegor256** [comment]
@0crat assign @emilianodellacasa

**Comment by 0crat** [comment]
> @0crat assign @emilianodellacasa ([here](https://github.com/zold-io/zold/issues/298#issuecomment-400697338))

@yegor256 Job [#298](https://github.com/zold-io/zold/issues/298) is already assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
> @0crat assign @emilianodellacasa ([here](https://github.com/zold-io/zold/issues/298#issuecomment-400744215))

@yegor256 Job [#298](https://github.com/zold-io/zold/issues/298) is already assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/zold/issues/298#issuecomment-400777339))

@yegor256 The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#298](https://github.com/zold-io/zold/issues/298), please stop working. Reason for job resignation: Order was cancelled

**Comment by yegor256** [comment]
@0crat assign @emilianodellacasa

**Comment by 0crat** [comment]
> @0crat assign @emilianodellacasa ([here](https://github.com/zold-io/zold/issues/298#issuecomment-400778610))

@yegor256 There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@07414ffa-14ca-4340-b594-8ebf9e40e362, thread: AsyncFlush-6
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value '$1221.00 + €20.00' is not facet-valid with respect to pattern '0|([A-Z]{3} \-?|\-?($|€|£|¥))\d+(\.\d{1,2})?' for type 'cash'.;-1:-1: cvc-attribute.3: The value '$1221.00 + €20.00' of attribute 'total' on element 'estimates' is not valid with respect to its type, 'cash'.
```

[0.23.4](https://github.com/zerocracy/farm): CID: [1781811070](https://www.0crat.com/CAZPZR9FS/1781811070), Type: "Start order", Author: "yegor256"

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @emilianodellacasa

**Comment by 0crat** [comment]
> @0crat assign @emilianodellacasa ([here](https://github.com/zold-io/zold/issues/298#issuecomment-400793618))

@yegor256 Job [#298](https://github.com/zold-io/zold/issues/298) is already assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by emilianodellacasa** [comment]
PR #309

**Comment by emilianodellacasa** [comment]
@yegor256 Should an absent node be removed by a "trim" command?

**Comment by yegor256** [comment]
@emilianodellacasa `trim` will remove some nodes, according to some logic. This is not important here. Here the problem is that we crash when the node is not in the list.

**Comment by emilianodellacasa** [comment]
@yegor256 I have already resolved the crash problem, but the "trim" test is failing because the unavailability of the remote was the preocondition on the test.

Here the question is: if the remote is unavailable, should the "trim" command remove it from the list?

**Comment by yegor256** [comment]
@emilianodellacasa what is "unavailable"? I don't understand the question.

**Comment by emilianodellacasa** [comment]
@yegor256 When I say "unavailable" I mean when the node is not found in the list, as you said in the description of the issue. I already fixed the issue and now the code is not throwing an error, just logging a message.

Noow I am asking if the "trim" command should remove the remote if this is not found in the list

**Comment by yegor256** [comment]
@emilianodellacasa how can it remove the node if it's already absent in the list?

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by emilianodellacasa** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@emilianodellacasa what? :)

**Comment by emilianodellacasa** [comment]
@yegor256 Sorry, Should have ping on PR #312 :-P

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#298](https://github.com/zold-io/zold/issues/298), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by emilianodellacasa** [comment]
@yegor256 please assign this task back to me

**Comment by yegor256** [comment]
@0crat assign me

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#298` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zold-io/zold/issues/298#issuecomment-405159521))

@yegor256 The job [#298](https://github.com/zold-io/zold/issues/298) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1970814103); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @yegor256[/z](https://www.0crat.com/u/yegor256) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) resigned from [#298](https://github.com/zold-io/zold/issues/298), since the job is not in scope anymore

**Comment by 0crat** [comment]
The job [#298](https://github.com/zold-io/zold/issues/298) is now out of scope
