### ISSUE TITLE
Documentation on log levels is missing

### ISSUE THREAD

**Issue by ledestin** [zold-io/zold#300]
I can guess that probably info will get to the user, but an overview would be nice.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#300](https://github.com/zold-io/zold/issues/300) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1771732904); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @yegor256[/z](https://www.0crat.com/u/yegor256) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#300` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ledestin[/z](https://www.0crat.com/u/ledestin)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@ledestin check e4a0b77 Good enough?

**Comment by ledestin** [comment]
@yegor256 great, ty

**Comment by ledestin** [comment]
@yegor256 I envisioned more of an overview document with such details, not code comments though. So you could point new contributors to it.

**Comment by yegor256** [comment]
@ledestin please, close the ticket if the problem is solved

**Comment by yegor256** [comment]
@ledestin it's better to keep documentation close to the code. More contributors will easily modify this comment too.

**Comment by ledestin** [comment]
@yegor256 Ok

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#300](https://github.com/zold-io/zold/issues/300) is now out of scope
