### ISSUE TITLE
Ethereum is mispelled in gemspec and whitepaper.

### ISSUE THREAD

**Issue by jsoroka** [zold-io/zold#304]
I expect to see 'ethereum' but I see 'etherium' instead, here in the gemspec: https://github.com/zold-io/zold/blob/6eaac8af81da7575157a40e251cb03cfda53d812/zold.gemspec#L40

Also in the whitepaper, [here](https://github.com/zold-io/papers/blob/f5561d96c879a0200296ce85921749b92487607a/tex/wp.tex#L44) and [here](https://github.com/zold-io/papers/blob/f5561d96c879a0200296ce85921749b92487607a/tex/wp.tex#L71)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@jsoroka[/z](https://www.0crat.com/u/jsoroka) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@jsoroka fixed in 25ac9b6 thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#304` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
