### ISSUE TITLE
Replace stdlib digest with digest from OpenSSL

### ISSUE THREAD

**Issue by botanicus** [zold-io/zold#305]
During the investigation of #113 I found out the stdlib digest is not thread safe and so I replaced it with digest from the OpenSSL library instead.

I did so only in the one place the bug was occurring, but there are more places where digest is still being used. So in order for no more bugs like #113 to pop up in the future, we need to replace these digest calls as well.

**Comment by 0crat** [comment]
Job [#305](https://github.com/zold-io/zold/issues/305) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by 0crat** [comment]
The job [#305](https://github.com/zold-io/zold/issues/305) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1790613629); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by emilianodellacasa** [comment]
The fix is in pull request #311

**Comment by emilianodellacasa** [comment]
@botanicus @yegor256 The fix has been merged, what is left to be done with this issue?

**Comment by botanicus** [comment]
@emilianodellacasa have you replaced everything? https://github.com/zold-io/zold/blob/master/lib/zold/tax.rb#L21

**Comment by botanicus** [comment]
@emilianodellacasa definitely. Although I’m not sure whether it’s in the scope of this bug[1] as I’m new to the zerocracy process myself, I’ll defer to @yegor256 here.

[1] I’m not sure if it is, but opening a ticket for removing 1 line of code sounds like an overkill to me.

**Comment by emilianodellacasa** [comment]
@botanicus I'll remove it right away

**Comment by emilianodellacasa** [comment]
@botanicus  New PR in #339 sorry for the duplication @yegor256

**Comment by emilianodellacasa** [comment]
@botanicus  @yegor256 Everything should be ok now

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by botanicus** [comment]
@emilianodellacasa perfect, thanks!

@yegor256 please close.

**Comment by yegor256** [comment]
@botanicus why me? :) It's your ticket.

**Comment by botanicus** [comment]
@yegor256 haha, fair enough :)) I thought it’s the `ARC` job. But yeah, makes sense.

Closed now.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#305](https://github.com/zold-io/zold/issues/305) is now out of scope

**Comment by ypshenychka** [comment]
@emilianodellacasa According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to.

Please correct your [message](https://github.com/zold-io/zold/issues/305#issuecomment-401308950) by indicating an addressee in the beginning.

**Comment by ypshenychka** [comment]
@emilianodellacasa Thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
