### ISSUE TITLE
Do not lock to a certain Ruby version (Gemfile)

### ISSUE THREAD

**Issue by botanicus** [zold-io/zold#306]
As a library that's supposed to work for a wide range of users and their environments, it's only reasonable to demand that it runs on more Ruby versions than just `2.3.3`.

I don't have the aforementioned version of Ruby installed, so I commented out the version requirement and I'm running zold on `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]` and it works well.

I'd like to suggest that locking to a _specific_ Ruby version _in a library or open application_ is as bad as locking to specific gem versions. It's fine to require Ruby 2.x (which is in fact what we should do), but not (only) `2.3.3`.

**Next steps:**
- Change the gemspec (delete or change to more versatile option).
- Document supported versions in the README.
- Change Travis CI and Appveyor configuration to Run against say `2.0`, `2.1`, `2.3`, `2.4`, `2.5` and `2.6.pre`.
- Is there anything to be done about `TargetRubyVersion` in `.rubocop.yml`? It's `2.2` at the moment, so not even the default `2.3.3`.

**EDIT:** In the gemspec file, the version is identified as `s.required_ruby_version = '~>2.2'`, we might want to stick to that.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#306](https://github.com/zold-io/zold/issues/306) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by 0crat** [comment]
The job [#306](https://github.com/zold-io/zold/issues/306) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1790618731); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by botanicus** [comment]
@yegor256 what should be the lowest supported Ruby version?

Ruby 2.3 has some features that are pretty handy, such as the safe navigation operator `test&.method` (shortcut for `test.method if test`) and the whitespace-trimming heredoc `<<~EOF`.

**Comment by emilianodellacasa** [comment]
@yegor256 I think @botanicus is right, we should take a decision about which minimum version of Ruby should we support.

Ruby 2.2 is 4 years old but still used in many projects, based on recent statistics.

**Comment by g4s8** [comment]
@0crat status

**Comment by yegor256** [comment]
@botanicus I would say 2.3 is the minimum, but I'm not an expert...

**Comment by botanicus** [comment]
@yegor256 I agree, supporting 2.3+ is good enough and since it gives us quite a few pretty significant benefits, let’s go with it // cc @emilianodellacasa

**Comment by emilianodellacasa** [comment]
@botanicus @yegor256 I agree with this decision, let's go to 2.3+ then

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zold-io/zold/issues/306#issuecomment-402140958))

@g4s8 This is what I know about this job in [CAZPZR9FS](https://www.0crat.com/p/CAZPZR9FS), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#306](https://github.com/zold-io/zold/issues/306) is [in scope](http://www.zerocracy.com/policy.html#14) for 5days
  * The role is `DEV`
  * The job is assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) for [5days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @botanicus[/z](https://www.0crat.com/u/botanicus): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CAZPZR9FS?q=%7Bjob%3A%27gh%3Azold-io%2Fzold%23306%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by emilianodellacasa** [comment]
PR #336

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#306](https://github.com/zold-io/zold/issues/306), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by emilianodellacasa** [comment]
@yegor256 please assign this task back to me

**Comment by emilianodellacasa** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@0crat assign @emilianodellacasa

**Comment by 0crat** [comment]
> @0crat assign @emilianodellacasa  ([here](https://github.com/zold-io/zold/issues/306#issuecomment-403504270))

@yegor256 The job [#306](https://github.com/zold-io/zold/issues/306) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1901448804); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by emilianodellacasa** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/zold-io/zold/issues/306#issuecomment-404233149))

@emilianodellacasa The impediment for [#306](https://github.com/zold-io/zold/issues/306) was registered successfully by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0pdd** [comment]
@botanicus the puzzle [#389](https://github.com/zold-io/zold/issues/389) is still not solved.

**Comment by emilianodellacasa** [comment]
@botanicus PR https://github.com/zold-io/zold/pull/336 has been successfully closed, please close this issue

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#306](https://github.com/zold-io/zold/issues/306) is now out of scope

**Comment by ypshenychka** [comment]
@emilianodellacasa According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to.

Please correct your [message](https://github.com/zold-io/zold/issues/306#issuecomment-402200457) by indicating an addressee in the beginning.

**Comment by ypshenychka** [comment]
@emilianodellacasa According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary

Please add more details to the registered [impediment](https://github.com/zold-io/zold/issues/306#issuecomment-404233149)

**Comment by emilianodellacasa** [comment]
@ypshenychka Done, sorry for that

**Comment by ypshenychka** [comment]
@emilianodellacasa thank you

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@botanicus the only puzzle [#389](https://github.com/zold-io/zold/issues/389) is solved here.
