### ISSUE TITLE
Test output is chaotic and unusable

### ISSUE THREAD

**Issue by botanicus** [zold-io/zold#307]
I just run `rake test`. It failed with 4 failures, and I'm just not able to find them, because the output is very verbose and very confusing (failures from the CLI looks like failures from the tests).

**Next steps:**
- Output to the logger (and/or `$stdout`/`$stderr`) needs to be redirected.
- It'd be great if there would be failure summary at the very end of all output, linking files and lines of the failed specs, just like rSpec does.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@botanicus you can go to `test__helper.rb` and replace the logger with a `Quiet` one. I think we should make it possible to suppress all logs from command line: `rake --quiet`. Let's implement this possibility.

**Comment by 0crat** [comment]
Job [#307](https://github.com/zold-io/zold/issues/307) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by 0crat** [comment]
The job [#307](https://github.com/zold-io/zold/issues/307) assigned to @mgrassotti[/z](https://www.0crat.com/u/mgrassotti), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1791324846); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by mgrassotti** [comment]
I wrote a solution but I cannot push a new branch to create a new PR: 
```
$ git push --set-upstream origin quiet-test-option
remote: Permission to zold-io/zold.git denied to mgrassotti.
fatal: unable to access 'https://github.com/zold-io/zold.git/': The requested URL returned error: 403
```

**Comment by 0crat** [comment]
@mgrassotti[/z](https://www.0crat.com/u/mgrassotti) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by mgrassotti** [comment]
@0crat I cannot close it until the related PR #316 is under review / unmerged

**Comment by 0crat** [comment]
> @0crat I cannot close it until the related PR #316 is under review / unmerged ([here](https://github.com/zold-io/zold/issues/307#issuecomment-402525366))

@mgrassotti Can't understand "I", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by mgrassotti** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zold-io/zold/issues/307#issuecomment-403014776))

@mgrassotti This is what I know about this job in [CAZPZR9FS](https://www.0crat.com/p/CAZPZR9FS), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#307](https://github.com/zold-io/zold/issues/307) is [in scope](http://www.zerocracy.com/policy.html#14) for 8days
  * The role is `DEV`
  * The job is assigned to @mgrassotti[/z](https://www.0crat.com/u/mgrassotti) for [8days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @mgrassotti[/z](https://www.0crat.com/u/mgrassotti) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @botanicus[/z](https://www.0crat.com/u/botanicus): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CAZPZR9FS?q=%7Bjob%3A%27gh%3Azold-io%2Fzold%23307%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by mgrassotti** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zold-io/zold/issues/307#issuecomment-403015381))

@mgrassotti GitHub issue is still open, won't close

**Comment by mgrassotti** [comment]
@yegor256 who is supposed to close the issue? The related PR is closed (#316) but I cannot close this

**Comment by yegor256** [comment]
@mgrassotti the author of the ticket, read this please: https://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by mgrassotti** [comment]
@yegor256 ah ok thanks, sorry

**Comment by mgrassotti** [comment]
@botanicus could you please close ticket if it is fine for you? Thanks

**Comment by botanicus** [comment]
@mgrassotti closing now, thanks Matteo!

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@8f093af3-e192-4652-b43a-82b22aa39bc1, thread: AsyncFlush-8
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:zold-io/zold#307] declared for identity constraint of element "verbosity".
```

[0.25.2](https://github.com/zerocracy/farm): CID: [1871426089](https://www.0crat.com/CAZPZR9FS/1871426089), Type: "Close job", Author: "botanicus"

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @mgrassotti[/z](https://www.0crat.com/u/mgrassotti), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#307](https://github.com/zold-io/zold/issues/307) is now out of scope

**Comment by ypshenychka** [comment]
@mgrassotti According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues

None of your commits contain link to this issue. Please confirm you'll try to follow this rule next time.

**Comment by mgrassotti** [comment]
@ypshenychka sure, I think that's the same as https://github.com/zold-io/zold/pull/316#issuecomment-402941898

**Comment by ypshenychka** [comment]
@mgrassotti Thanks, you're right. But you're going to be paid for this ticket, so I have to mention this rule here.

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @mgrassotti[/z](https://www.0crat.com/u/mgrassotti)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
