### ISSUE TITLE
Remotes.rb should ignore non-matching networks

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#314]
Let's add an extra validation step for `Remotes::Remote` to check that the `network` matches. If we fetch JSON that contains `network` that doesn't match what we have encapsulated, we should raise an exception.

**Comment by 0crat** [comment]
Job [#314](https://github.com/zold-io/zold/issues/314) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#314](https://github.com/zold-io/zold/issues/314) assigned to @mgrassotti[/z](https://www.0crat.com/u/mgrassotti), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1811448243); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by mgrassotti** [comment]
hi @yegor256, sorry could you specify more _"If we fetch JSON that contains `network` that doesn't match what we have encapsulated"_ ? With _encapsulation_, do you mean initialization `Remote#new` at `lib/zold/remotes.rb:63`? 

Where can we load a new network? Is that in `Fetch#new` at /Users/mateosky/dev/zold/lib/zold/commands/fetch.rb:41" ? 

Thanks

**Comment by 0crat** [comment]
@mgrassotti[/z](https://www.0crat.com/u/mgrassotti) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @mgrassotti[/z](https://www.0crat.com/u/mgrassotti) resigned from [#314](https://github.com/zold-io/zold/issues/314), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @mgrassotti[/z](https://www.0crat.com/u/mgrassotti)

**Comment by 0crat** [comment]
The job [#314](https://github.com/zold-io/zold/issues/314) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1990748865); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by emilianodellacasa** [comment]
@yegor256 Isn't it what it's already happening _lib/zold/commands/fetch.rb:115_? We already are raising an exception in case we fetch a JSON with a different network

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@emilianodellacasa you are right, it's already implemented

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/zold/issues/314#issuecomment-405934513))

@yegor256 The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#314](https://github.com/zold-io/zold/issues/314), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#314` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#314](https://github.com/zold-io/zold/issues/314) is now out of scope
