### ISSUE TITLE
Travis build must fail if PDD fails

### ISSUE THREAD

**Issue by botanicus** [zold-io/zold#321]
Travis currently doesn’t fail if PDD does.

That means we’re all wasting our time if a PR looks good, everything’s green, but in fact PDD hasn’t been tested, as it happened in https://github.com/zold-io/zold/pull/295

That means 2 people have to do something and all is being held back and an unnecessary context switching introduces overhead and waste of time for the both of them.

```ruby
def :pdd do
  puts `pdd -f /dev/null`
end

# ... add :pdd to the default task.
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#321](https://github.com/zold-io/zold/issues/321) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1830929991); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @yegor256[/z](https://www.0crat.com/u/yegor256) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#321` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#321](https://github.com/zold-io/zold/issues/321) is now out of scope
