### ISSUE TITLE
test_alias.rb:3-5: Write unit tests for the alias...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/zold#322]
The puzzle `279-4664e37c` from #279 has to be resolved:

https://github.com/zold-io/zold/blob/bc98df8a4527bcce4ef88494de1b71c448b033bd/test/commands/test_alias.rb#L3-L5

The puzzle was created by rultor on 02-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#322](https://github.com/zold-io/zold/issues/322) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@0crat assign @botanicus

**Comment by 0crat** [comment]
> @0crat assign @botanicus  ([here](https://github.com/zold-io/zold/issues/322#issuecomment-401693018))

@yegor256 The job [#322](https://github.com/zold-io/zold/issues/322) assigned to @botanicus[/z](https://www.0crat.com/u/botanicus), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1830721562); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@botanicus[/z](https://www.0crat.com/u/botanicus) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by botanicus** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/zold-io/zold/issues/322#issuecomment-404120260))

@botanicus The impediment for [#322](https://github.com/zold-io/zold/issues/322) was registered successfully by @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by 0pdd** [comment]
The puzzle `279-4664e37c` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#377](https://github.com/zold-io/zold/issues/377), [#378](https://github.com/zold-io/zold/issues/378), [#379](https://github.com/zold-io/zold/issues/379) are still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @botanicus[/z](https://www.0crat.com/u/botanicus), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#322](https://github.com/zold-io/zold/issues/322) is now out of scope

**Comment by ypshenychka** [comment]
@botanicus According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary

Please add more details to the registered [impediment](https://github.com/zold-io/zold/issues/322#issuecomment-404120260).

**Comment by ypshenychka** [comment]
@botanicus ping

**Comment by ypshenychka** [comment]
@botanicus Please respond to the above [remark](https://github.com/zold-io/zold/issues/322#issuecomment-404276445)

**Comment by ypshenychka** [comment]
@0crat quality acceptable
