### ISSUE TITLE
Create test helper to populate wallet file with transactions(specified amount) without executing `sub` or `add`.

### ISSUE THREAD

**Issue by liligga** [zold-io/zold#325]
So I am testing  `Patch#join` and trying to make it fail when wallet has too big amount transactions:

          wallet = home.create_wallet
          wallet.add big_amount_txn
          patch = Zold::Patch.new(home.wallets, log: test_log)
          error = assert_raises RuntimeError do
              patch.join(wallet)
          end

 I can't  test `Patch#join` because the check on `wallet.add big_amount_txn` already implemented and `Too big amount` error is thrown right there and line `patch.join(wallet)` never got hit. So I realized I have to create a wallet file with transactions by hand but have no idea how.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@liligga[/z](https://www.0crat.com/u/liligga) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
The job [#325](https://github.com/zold-io/zold/issues/325) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1831722235); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @yegor256[/z](https://www.0crat.com/u/yegor256) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by liligga** [comment]
@yegor256 can you assign this to me?

**Comment by yegor256** [comment]
@0crat assign @liligga

**Comment by 0crat** [comment]
> @0crat assign @liligga  ([here](https://github.com/zold-io/zold/issues/325#issuecomment-403471029))

@yegor256 The job [#325](https://github.com/zold-io/zold/issues/325) assigned to @liligga[/z](https://www.0crat.com/u/liligga), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1901304826); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @liligga[/z](https://www.0crat.com/u/liligga) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; we should be aware that @liligga[/z](https://www.0crat.com/u/liligga) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@0crat[/z](https://www.0crat.com/u/0crat) I see that you unassigned this issue; the order is still assigned to @liligga[/z](https://www.0crat.com/u/liligga) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The user @liligga[/z](https://www.0crat.com/u/liligga) resigned from [#325](https://github.com/zold-io/zold/issues/325), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @liligga[/z](https://www.0crat.com/u/liligga)

**Comment by 0crat** [comment]
The job [#325](https://github.com/zold-io/zold/issues/325) assigned to @alhadhrami[/z](https://www.0crat.com/u/alhadhrami), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/9a77c93e-49b5-4832-a30a-7e637965ee0e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by alhadhrami** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/zold/issues/325#issuecomment-475636743))

@alhadhrami The user @alhadhrami[/z](https://www.0crat.com/u/alhadhrami) resigned from [#325](https://github.com/zold-io/zold/issues/325), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @alhadhrami[/z](https://www.0crat.com/u/alhadhrami)

**Comment by yegor256** [comment]
@liligga it's fixed already

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#325` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#325](https://github.com/zold-io/zold/issues/325) is now out of scope
