### ISSUE TITLE
upgrades.rb:12-15: Write the upgrade manager tests that...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/zold#327]
The puzzle `285-214c18b0` from #285 has to be resolved:

https://github.com/zold-io/zold/blob/90f141e718477fbbfcf49542726ad7204f70fcf7/lib/zold/upgrades.rb#L12-L15

The puzzle was created by James C Russell on 30-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@0crat assign @ledestin

**Comment by 0crat** [comment]
> @0crat assign @ledestin  ([here](https://github.com/zold-io/zold/issues/327#issuecomment-401888614))

@yegor256 The job [#327](https://github.com/zold-io/zold/issues/327) assigned to @ledestin[/z](https://www.0crat.com/u/ledestin), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1831811811); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ledestin** [comment]
@yegor256 documentation missing https://github.com/zold-io/zold/issues/343

**Comment by ledestin** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/zold-io/zold/issues/327#issuecomment-402411466))

@ledestin The impediment for [#327](https://github.com/zold-io/zold/issues/327) was registered successfully by @ledestin[/z](https://www.0crat.com/u/ledestin)

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/zold-io/zold/issues/327#issuecomment-402411466))

@ledestin Job [#327](https://github.com/zold-io/zold/issues/327) is not in the agenda of @ledestin[/z](https://www.0crat.com/u/ledestin), can't set impediment

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#365](https://github.com/zold-io/zold/issues/365), [#366](https://github.com/zold-io/zold/issues/366) are still not solved.

**Comment by 0pdd** [comment]
The puzzle `285-214c18b0` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#327](https://github.com/zold-io/zold/issues/327) is not in the agenda of @ledestin[/z](https://www.0crat.com/u/ledestin), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job [#327](https://github.com/zold-io/zold/issues/327) is not in the agenda of @ledestin[/z](https://www.0crat.com/u/ledestin), can't inspect

**Comment by 0crat** [comment]
The job [#327](https://github.com/zold-io/zold/issues/327) is now out of scope

**Comment by ypshenychka** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zold-io/zold/issues/327#issuecomment-428504257))

@ypshenychka This is what I know about this job in [CAZPZR9FS](https://www.0crat.com/p/CAZPZR9FS), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#327](https://github.com/zold-io/zold/issues/327) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 3mon
  * @ledestin[/z](https://www.0crat.com/u/ledestin) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CAZPZR9FS?q=%7Bjob%3A%27gh%3Azold-io%2Fzold%23327%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @ledestin[/z](https://www.0crat.com/u/ledestin)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
