### ISSUE TITLE
remote.rb:254-255: Implement the logic of selecting the...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/zold#329]
The puzzle `292-3bcf6540` from #292 has to be resolved:

https://github.com/zold-io/zold/blob/c3f2f8dc1a46c3587026b1f4382fd657e425157a/lib/zold/commands/remote.rb#L254-L255

The puzzle was created by James C Russell on 30-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#329](https://github.com/zold-io/zold/issues/329) is now in scope, role is `DEV`

**Comment by botanicus** [comment]
@yegor256 may I have this ticket please?

**Comment by yegor256** [comment]
@0crat assign @botanicus

**Comment by 0crat** [comment]
> @0crat assign @botanicus  ([here](https://github.com/zold-io/zold/issues/329#issuecomment-402061591))

@yegor256 The job [#329](https://github.com/zold-io/zold/issues/329) assigned to @botanicus[/z](https://www.0crat.com/u/botanicus), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1840848545); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@botanicus[/z](https://www.0crat.com/u/botanicus) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by botanicus** [comment]
@0crat wait

**Comment by botanicus** [comment]
Stopping the counter as an action from REV has been due for 3 days.

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/zold-io/zold/issues/329#issuecomment-403490434))

@botanicus The impediment for [#329](https://github.com/zold-io/zold/issues/329) was registered successfully by @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by 0pdd** [comment]
The puzzle `292-3bcf6540` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#388](https://github.com/zold-io/zold/issues/388) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @botanicus[/z](https://www.0crat.com/u/botanicus), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#329](https://github.com/zold-io/zold/issues/329) is now out of scope

**Comment by ypshenychka** [comment]
@botanicus According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to.

Please correct your [message](https://github.com/zold-io/zold/issues/329#issuecomment-403490560) by indicating an addressee in the beginning.

**Comment by ypshenychka** [comment]
@botanicus ping

**Comment by botanicus** [comment]
@ypshenychka done

**Comment by ypshenychka** [comment]
@botanicus thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#388](https://github.com/zold-io/zold/issues/388) is solved here.
