### ISSUE TITLE
Do not throw exception in remote commands

### ISSUE THREAD

**Issue by emilianodellacasa** [zold-io/zold#334]
In many different points of the remote command's code we thrown an exception when there is an HTTP Error with the node:

```
localhost:888: Unexpected HTTP code 404, instead of 200 in 0s; errors=0
RuntimeError: Unexpected HTTP code 404, instead of 200
        /home/ufi/emiliano/zold/lib/zold/remotes.rb:88:in `assert_code'
        /home/ufi/emiliano/zold/lib/zold/commands/remote.rb:200:in `block in update'
        /home/ufi/emiliano/zold/lib/zold/remotes.rb:184:in `block in iterate'
        /home/ufi/emiliano/zold/lib/zold/remotes.rb:181:in `each'
        /home/ufi/emiliano/zold/lib/zold/remotes.rb:181:in `iterate'
        /home/ufi/emiliano/zold/lib/zold/commands/remote.rb:197:in `update'
        /home/ufi/emiliano/zold/lib/zold/commands/remote.rb:114:in `run'
```

It would be better not to throw the exception and log a message

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#334](https://github.com/zold-io/zold/issues/334) is now in scope, role is `DEV`

**Comment by yegor256** [comment]
@emilianodellacasa  This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#334` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#334](https://github.com/zold-io/zold/issues/334) is now out of scope
