### ISSUE TITLE
599 timeout - builds are filled with timeouts

### ISSUE THREAD

**Issue by oltdaniel** [zold-io/zold#337]
Somehow the nodes cause many 599 timeout responses. This slows down development and hurts actual system stability.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@oltdaniel are you talking about 599 errors during the build or in production? I didn't get the problem.

**Comment by oltdaniel** [comment]
@yegor256 Somehow the fake node is closed before the request has been executed.

The error `599` will only be thrown if the client couldn't execute the request, here the node is closed.
https://travis-ci.org/zold-io/zold/builds/399767497#L2075

**Comment by yegor256** [comment]
@oltdaniel 599 is a fake response code we return when something goes wrong with the connection. So, it's a pretty legal situation. You should find a more specific place you complain about. Just saying that "599 is a problem" is not enough. 599 is a normal situation, which may happen time to time. Find a more specific situation/problem and report, please.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#337` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
