### ISSUE TITLE
Use regexp named match for better readabilty

### ISSUE THREAD

**Issue by ledestin** [zold-io/zold#341]
https://github.com/zold-io/zold/blob/master/lib/zold/upgrades.rb#L27 uses `match[1]`, which isn't as good as a named match of `match[:version]`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#341](https://github.com/zold-io/zold/issues/341) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ledestin[/z](https://www.0crat.com/u/ledestin)

**Comment by 0crat** [comment]
The job [#341](https://github.com/zold-io/zold/issues/341) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1851414619); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by emilianodellacasa** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/zold-io/zold/issues/341#issuecomment-403419686))

@emilianodellacasa The impediment for [#341](https://github.com/zold-io/zold/issues/341) was registered successfully by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by emilianodellacasa** [comment]
@ledestin ping

**Comment by ledestin** [comment]
@emilianodellacasa it's not the only place, where `match[1]` was used.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#341](https://github.com/zold-io/zold/issues/341) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good
