### ISSUE TITLE
pay.rb:110-112: Extract message cretion into a separate...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/zold#342]
The puzzle `79-aed0d144` from #79 has to be resolved:

https://github.com/zold-io/zold/blob/1cd2134e7e24589160d688e3009d7f65754ee3e3/lib/zold/commands/pay.rb#L110-L112

The puzzle was created by rultor on 04-Jul-18. 

Estimate: 40 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#342](https://github.com/zold-io/zold/issues/342) is now in scope, role is `DEV`

**Comment by emilianodellacasa** [comment]
@0crat wait - PR created #485 waiting for review

**Comment by 0crat** [comment]
> @0crat wait - PR created #485 waiting for review ([here](https://github.com/zold-io/zold/issues/342#issuecomment-428507318))

@emilianodellacasa The impediment for [#342](https://github.com/zold-io/zold/issues/342) was registered successfully by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0pdd** [comment]
The puzzle `79-aed0d144` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#342](https://github.com/zold-io/zold/issues/342) is now out of scope

**Comment by ypshenychka** [comment]
@emilianodellacasa Why PR wasn't merged but this ticket is closed?

**Comment by emilianodellacasa** [comment]
@ypshenychka From the commits I see @yegor256 removed th puzzle, this is the reason why this ticket is closed

**Comment by emilianodellacasa** [comment]
@ypshenychka I guess so

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
