### ISSUE TITLE
Documentation on how upgrade manager should work is missing

### ISSUE THREAD

**Issue by ledestin** [zold-io/zold#343]
I'm doing https://github.com/zold-io/zold/issues/327#issuecomment-401888675 and the documentation on how upgrade manager should work is missing. What is `the version file`, for one? And what are `correct upgrade scripts`?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@0crat assign @botanicus

**Comment by 0crat** [comment]
> @0crat assign @botanicus  ([here](https://github.com/zold-io/zold/issues/343#issuecomment-402441229))

@yegor256 The job [#343](https://github.com/zold-io/zold/issues/343) assigned to @botanicus[/z](https://www.0crat.com/u/botanicus), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1851045085); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ledestin[/z](https://www.0crat.com/u/ledestin)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@botanicus[/z](https://www.0crat.com/u/botanicus) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @botanicus[/z](https://www.0crat.com/u/botanicus) resigned from [#343](https://github.com/zold-io/zold/issues/343), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by 0crat** [comment]
The job [#343](https://github.com/zold-io/zold/issues/343) assigned to @alhadhrami[/z](https://www.0crat.com/u/alhadhrami), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/a3f179b9-cafe-49e7-b603-6d79c4ed4412); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by alhadhrami** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@alhadhrami this is not required anymore

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/zold/issues/343#issuecomment-475636778))

@alhadhrami The user @alhadhrami[/z](https://www.0crat.com/u/alhadhrami) resigned from [#343](https://github.com/zold-io/zold/issues/343), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/zold/issues/343#issuecomment-476266031))

@yegor256 Job `gh:zold-io/zold#343` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#343](https://github.com/zold-io/zold/issues/343) is now out of scope

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @alhadhrami[/z](https://www.0crat.com/u/alhadhrami)
