### ISSUE TITLE
Runtime debugger missing

### ISSUE THREAD

**Issue by mgrassotti** [zold-io/zold#344]
I cannot find any debugger inside the project. Is that a planned approach?
I would suggest to add `byebug` or `pry` as development_dependency in `zold.gemspec`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by botanicus** [comment]
Why a `development_dependency`? That’s for things like testing frameworks and the like.

In Gemfile? I think that wouldn’t hurt.

**Comment by mgrassotti** [comment]
Ok thanks @botanicus I added #345 for this

**Comment by botanicus** [comment]
@mgrassotti by the way I can see why you proposed originally to add it as a `development_dependency`. For a reference only: we need to restructure our dependencies, I reported it here #346.

**Comment by yegor256** [comment]
@mgrassotti this is what I think about debugging: https://www.yegor256.com/2016/02/09/are-you-still-debugging.html I created the entire skeleton of Zold without any debugging. Are you sure we need it?

**Comment by mgrassotti** [comment]
@yegor256 I think unit tests are a good way to ensure the code is working _as expected_ or not. If you don't know what to expect because you don't know the code base, I think it is more expensive and time wasteful to write tests with a trial and error approach. 

Furthermore, thank you for your coding suggestions but, isn't this project based on the idea "this is not a school"? So why are we discussing about how I do program? Are you really interested on _how_ I achieve a result? Are you really interested how much does it take to me, if the final code is pretty clear and works as expected? My proposal was to add this gem to the project in order to avoid to add it each time by myself, that would really be a time saver for me.

**Comment by yegor256** [comment]
@mgrassotti good point. OK, let's add the gem.

**Comment by mgrassotti** [comment]
@yegor256 thanks. Could you please review and/or merge #345 ?

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#344` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
