### ISSUE TITLE
Review development dependencies

### ISSUE THREAD

**Issue by botanicus** [zold-io/zold#346]
We should keep our runtime dependencies requirements to the minimum.

Our gemspec has for instance `rubocop` as a runtime dependency.

Why? Will `bin/zold` refuse to start without rubocop?

There’s comment `has to stay there for Heroku` (See https://github.com/zold-io/zold/blob/master/zold.gemspec#L61). I don’t think it’s necessary, I have never seen it.

We can either:

- Use runtime dependencies for what they are. If it’s required for `bin/zold` to run, it’s a runtime dependency.
- Use development dependencies for everything that is required for development. Minitest, rubocop, cucumber, pdd, rake. If you don’t have these, you cannot run the tests (or local checks).
- Use Gemfile for useful things that most zold devs will use, but are not _required_, such as byebug.

Or we can:
- Use runtime dependencies for what’s required.
- Put everything else into the Gemfile, using groups `:development` and `:spec`.

If there are some issues with development dependencies on Heroku, this approach would solve them. I’d personally favour this solution in either case, I think development dependencies of RubyGems have lost their sense when Bundler came about.

https://guides.rubygems.org/patterns/#declaring-dependencies

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#346](https://github.com/zold-io/zold/issues/346) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by 0crat** [comment]
The job [#346](https://github.com/zold-io/zold/issues/346) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/058f9695-8e8c-4c62-835a-484eb219bcc8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by yegor256** [comment]
@botanicus fixed in #662

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#346](https://github.com/zold-io/zold/issues/346) is now out of scope

**Comment by ypshenychka** [comment]
@emilianodellacasa According to our [QA Rules](http://at.teamed.io/qa.html) the quality of a job is “bad” if:
>The job is closed without a solution provided

The PR you've created wasn't merged, thus no solution was provided here.
Please confirm you agree with that decision.

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
