### ISSUE TITLE
README doesn’t link any API documentation

### ISSUE THREAD

**Issue by botanicus** [zold-io/zold#348]
As a public library, we need to have:

1. API documentation online.
2. API documentation should be linked in the README, preferably as a badge (as in for example https://github.com/botanicus/hour-ruby#about).

There are number of services that we can use that integrate with GitHub via hooks.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#348](https://github.com/zold-io/zold/issues/348) is now in scope, role is `DEV`

**Comment by yegor256** [comment]
@botanicus  This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#348` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#348](https://github.com/zold-io/zold/issues/348) is now out of scope
