### ISSUE TITLE
Specify private/public key paths

### ISSUE THREAD

**Issue by g4s8** [zold-io/zold#350]
I have `~/.ssh/id_rsa` for not related to Zold purposes and I don't think that using same private key for different applications is a good security decision, also I want to import private key from wts.zold.io and don't want to override my existing `id_rsa` key.
I think user should be able to configure keys locations to store them in any place.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@g4s8 you can do that with `--public-key` and `--private-key` command line options.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#350` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
