### ISSUE TITLE
Make API doc coverage check part of the build process

### ISSUE THREAD

**Issue by botanicus** [zold-io/zold#352]
Currently the level of API documentation is very low. That’s a serious bug, the more serious so given Zerocracy model, where we work with a lot of developers and need them to start easily by themselves.

We need to make the coverage test part of the build process.

It might be a rubocop plugin.

Or possibly https://github.com/dkubb/yardstick

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@botanicus I believe we check coverage now, here: https://github.com/zold-io/zold/blob/master/.simplecov#L38 But the problem is that coverage information is not collected correctly at the moment. I'm not sure why but we have it reported already: https://github.com/zold-io/zold/issues/109

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#352` is not assigned, can't get performer
