### ISSUE TITLE
Refactor Remotes#iterate to comply with Ruby conventions

### ISSUE THREAD

**Issue by botanicus** [zold-io/zold#354]
The [Zold::Remotes#iterate](https://github.com/zold-io/zold/blob/master/lib/zold/remotes.rb#L177) method goes against Ruby conventions:

1. The base method should be named `#each` instead.
2. The `Enumerable` mixin should be used.
3. If we want to pass `farm`, I’d argue that we should be using `remotes.each.with_object(farm)`. We get the `#with_object` method from `Enumerable`, but we’ll need to extend it I think.
4. Passing the `log` this way also looks weird.

So it should look somethink like:

```ruby
class Remotes
  include Enumerable

  def each
    # yield when XYZ happens
  end
end
```

Apart from behaving the conventional (and therefore the expected way), we get many methods for free, such as `#select`, `#find` etc.

Unless there’s a good reason against using the conventions, we should stick to them to make the project as understandable for developers new to the project as possible and therefore keep the pace of Zold development high and new recruits drop-out rate low.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by emilianodellacasa** [comment]
@yegor256 Would be a problem for you to pass `log` and `farm` in `Zold::Remotes.new` instead of `each`?

**Comment by emilianodellacasa** [comment]
@0crat wait - Waiting for a feedback

**Comment by 0crat** [comment]
> @0crat wait - Waiting for a feedback ([here](https://github.com/zold-io/zold/issues/354#issuecomment-450197865))

@emilianodellacasa The impediment for [#354](https://github.com/zold-io/zold/issues/354) was registered successfully by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@botanicus I don't think we should do that. The `iterate` method doesn't just list remote nodes, but executes a block in multiple threads, which is not what a Ruby default `each` is supposed to do, right? Let's stay with a non-conventional `iterate`. I made it this way intentionally.

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/zold/issues/354#issuecomment-476264555))

@yegor256 The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#354](https://github.com/zold-io/zold/issues/354), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#354` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#354](https://github.com/zold-io/zold/issues/354) is now out of scope
