### ISSUE TITLE
Add guard for incremental testing

### ISSUE THREAD

**Issue by botanicus** [zold-io/zold#356]
When I save a file, I want the checks[1] _for that particular file_ to run. [Guard](https://github.com/guard/guard) is commonly used in the Ruby community exactly for that.

[1] Tests, rubocop and PDD.

**Rationale:** I found this increases my productivity and makes sure I don’t push broken stuff.

**Next steps:**
- Add the `guard` gem and possibly some `guard-minitest`If there is one.
- Run `guard init`.
- Tweak the `Guardfile` as necessary.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@botanicus I don't understand how it works, but I'm not against it :) Let's try.

**Comment by 0crat** [comment]
Job [#356](https://github.com/zold-io/zold/issues/356) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by botanicus** [comment]
@yegor256 cool :) FYI here’s a demo https://m.youtube.com/watch?v=R0F32l0HSwk&t=137s

**Comment by 0crat** [comment]
The job [#356](https://github.com/zold-io/zold/issues/356) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/9d2192e4-5972-49dc-a287-c312e3ebdd79); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by emilianodellacasa** [comment]
@yegor256 PR #655 has beel merged, please close this issue

**Comment by emilianodellacasa** [comment]
@yegor256 ping

**Comment by emilianodellacasa** [comment]
@yegor256 You are right, sorry

**Comment by emilianodellacasa** [comment]
@botanicus could you please close this issue?

**Comment by emilianodellacasa** [comment]
@yegor256 reporter is not answering, could you please close this issue?

**Comment by emilianodellacasa** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@emilianodellacasa closed

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#356](https://github.com/zold-io/zold/issues/356) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/zold-io/zold/issues/356#issuecomment-454679649))

@ypshenychka There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@921cfe52-cfa0-4375-bc9e-960f2dab1feb, thread: AsyncProc-4
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath 'text()' not found in '<param name="payment_id"/>': Index (0) is out of bounds (size=0)
```

[0.40.5](https://github.com/zerocracy/farm): CID: [e75f3536-9fd4-4143-a440-2b68a76aaf89](https://www.0crat.com/footprint/CAZPZR9FS/e75f3536-9fd4-4143-a440-2b68a76aaf89), Type: "Pay cash"

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
