### ISSUE TITLE
Zold::PROTOCOL

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#357]
Let's add a new global constant `Zold::PROTOCOL`, staying next to `VERSION`. This protocol should be visible in Front, in wallets, and in `bin/zold`. We should use it in `Upgrades`, instead of `VERSION`.

We just want our files to be readable not only by Ruby software, but by any others. Say, someone creates Java software that reads the same directory with the same files. The `version` information will be confusing for it, since it will not know anything about Ruby versions. Thus, we should have "protocol" there, not a Ruby version.

**Comment by yegor256** [comment]
@0crat assign @botanicus

**Comment by 0crat** [comment]
> @0crat assign @botanicus  ([here](https://github.com/zold-io/zold/issues/357#issuecomment-403088616))

@yegor256 The job [#357](https://github.com/zold-io/zold/issues/357) assigned to @botanicus[/z](https://www.0crat.com/u/botanicus), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1871655780); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by yegor256** [comment]
@botanicus see the motivation: https://github.com/zold-io/papers/issues/13

**Comment by yegor256** [comment]
@botanicus let's make sure we expose it in `X-Zold-Protocol` too, in `Front`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by botanicus** [comment]
@0crat wait

**Comment by botanicus** [comment]
Pausing the time counting since the request for merge has been waiting for 2 days already.

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/zold-io/zold/issues/357#issuecomment-403487863))

@botanicus The impediment for [#357](https://github.com/zold-io/zold/issues/357) was registered successfully by @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#370](https://github.com/zold-io/zold/issues/370) is still not solved.

**Comment by botanicus** [comment]
@yegor256 please close.

**Comment by yegor256** [comment]
@botanicus thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @botanicus[/z](https://www.0crat.com/u/botanicus), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#357](https://github.com/zold-io/zold/issues/357) is now out of scope

**Comment by ypshenychka** [comment]
@botanicus According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to.

Please correct your [message](https://github.com/zold-io/zold/issues/357#issuecomment-403487890) by indicating an addressee in the beginning.

**Comment by botanicus** [comment]
@ypshenychka it's meant to anyone who reads the ticket, I don't have anyone specific in mind.

I can _not_ post thinks like that (and delete this one), but I believe it's good to inform the public (whoever's interested) about where things are.

**Comment by ypshenychka** [comment]
@botanicus We have to avoid noise in tickets. So please address this to someone (e.g. issue reporter, architect, 0crat).

**Comment by ypshenychka** [comment]
@botanicus ping

**Comment by botanicus** [comment]
@ypshenychka OK, "noise" removed.

**Comment by ypshenychka** [comment]
@botanicus What was the reason to remove the comment at all? It was explaining the reason of impediment. Now please add details to registered [impediment](https://github.com/zold-io/zold/issues/357#issuecomment-403487863) in accordance to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary

**Comment by ypshenychka** [comment]
@botanicus ping

**Comment by ypshenychka** [comment]
@botanicus Please add details to the impediment.

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
