### ISSUE TITLE
file renaming upgrade

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#358]
Let's create the first upgrade script (for `Upgrades`), which will rename all wallets from their current names into `*.z` (thanks to https://github.com/zold-io/zold/issues/164). If we don't do that, all wallets will be lost by all nodes, the moment we launch a new version.

**Comment by yegor256** [comment]
@0crat assign @botanicus

**Comment by 0crat** [comment]
> @0crat assign @botanicus  ([here](https://github.com/zold-io/zold/issues/358#issuecomment-403091087))

@yegor256 The job [#358](https://github.com/zold-io/zold/issues/358) assigned to @botanicus[/z](https://www.0crat.com/u/botanicus), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1871664889); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by botanicus** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/zold-io/zold/issues/358#issuecomment-403192995))

@botanicus The impediment for [#358](https://github.com/zold-io/zold/issues/358) was registered successfully by @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by botanicus** [comment]
Waiting for #351 to be merged in.

**Comment by yegor256** [comment]
@botanicus this one is the most critical now, please make it your high priority

**Comment by botanicus** [comment]
@yegor256 so `PROTOCOL` will go from `1` to `2`, right?

**Comment by yegor256** [comment]
@botanicus correct, just integers

**Comment by yegor256** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zold-io/zold/issues/358#issuecomment-403725697))

@yegor256 The job [#358](https://github.com/zold-io/zold/issues/358) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1910720182); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @yegor256[/z](https://www.0crat.com/u/yegor256) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release, tag is `0.14`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.1`

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#358](https://github.com/zold-io/zold/issues/358) is now out of scope
