### ISSUE TITLE
Sporadic test failure

### ISSUE THREAD

**Issue by botanicus** [zold-io/zold#361]
[Build 584](https://travis-ci.org/zold-io/zold/builds/401092358) failed in `TestNode#test_push_and_fetch`.

I tested locally, everything worked, so I pushed an _empty_ commit and the [build 585](https://travis-ci.org/zold-io/zold/builds/401094104) has succeeded.

I have seen this one once before.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#361](https://github.com/zold-io/zold/issues/361) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by yegor256** [comment]
@botanicus 
This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#361` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#361](https://github.com/zold-io/zold/issues/361) is now out of scope
