### ISSUE TITLE
README forgets to use bundle exec

### ISSUE THREAD

**Issue by botanicus** [zold-io/zold#364]
In the contribute section all the commands should be prefixed with `bundle exec`. Otherwise Bundler is not being used in the runtime, meaning `Gemfile.lock` is being totally ignored and Bundler is being used only to install the gems, but not to select the correct version at the runtime.

Does it matter?

Say we upgrade library xyz from version 1 to version 2. All the contributors have version 1 installed, that's how they've been working until now.

Now they run `rake test` and they get a lot of weird errors from xyz. They have to search what changed to realise they are running the wrong version of xyz.

So they do `gem uninstall xyz; gem install xyz -v 2` and they are good to go. Until this happens again with some other library.

... or they just use `bundle exec [cmd]`, so it tells you when you need to run `bundle update` and it will select the right version if you have multiple installed.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#364](https://github.com/zold-io/zold/issues/364) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @botanicus[/z](https://www.0crat.com/u/botanicus)

**Comment by theterminalguy** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zold-io/zold/issues/364#issuecomment-408700608))

@theterminalguy This is what I know about this job in [CAZPZR9FS](https://www.0crat.com/p/CAZPZR9FS), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#364](https://github.com/zold-io/zold/issues/364) is [in scope](http://www.zerocracy.com/policy.html#14) for 22days
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @botanicus[/z](https://www.0crat.com/u/botanicus): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CAZPZR9FS?q=%7Bjob%3A%27gh%3Azold-io%2Fzold%23364%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by yegor256** [comment]
@botanicus explained in d3cec1d thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#364` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#364](https://github.com/zold-io/zold/issues/364) is now out of scope
