### ISSUE TITLE
Store wallets in user's HOME

### ISSUE THREAD

**Issue by botanicus** [zold-io/zold#372]
When I create a wallet, the wallet is created in the current directory. There's nothing wrong with that per-se, but in #358 we want to rename these wallets.

_But where do I find them?_

Currently, there's no way of doing so. It's reasonable to expect that the user could be in any location when calling the `zold` Command.

```
Gem update zold
./zold/create # anything triggers the upgrades.
Echo $PWD
# ... ?
```

Besides [we cannot even reasonably determine what the wallets are](https://github.com/zold-io/zold/pull/371/files#diff-da975b93d4945fef12ab46fbc45d2efcR5) Without reading the files in the current directory. 

Therefore I suggest storing them in `~/.zoldata`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@botanicus well, we are trying to copy Git in our design, which is using _current directory_ when you run it. In order to find all wallets, just do `Wallets.new(dir).all`

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#372` is not assigned, can't get performer
