### ISSUE TITLE
identical content is identified as different copies

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#374]
I can't understand how this can happen:

```
159.65.37.22:4096/0 returned 3057b/3t/?/5h as copy 2 of 0000000000000000 in 1.67s: 26 (0.14.1)
167.99.35.39:4096/1 returned 3057b/3t/?/37m as copy 2 of 0000000000000000 in 1.25s: 15 (0.14.1)
138.68.165.235:4096/2 returned 3057b/3t/?/23m as copy 2 of 0000000000000000 in 1.98s: 15 (0.14.1)
159.203.19.189:4096/3 returned 3057b/3t/?/20m as copy 1 of 0000000000000000 in 2.15s: 18 (0.14.1)
```

It's obvious that all four nodes returned exactly the same content of the wallet (3057 bytes). However, the forth node was identified as copy no.1 while the first three as copy no.2. How this could be? Let's try to reproduce in a test and fix.

**Comment by 0crat** [comment]
Job [#374](https://github.com/zold-io/zold/issues/374) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.3`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#374` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#374](https://github.com/zold-io/zold/issues/374) is now out of scope
