### ISSUE TITLE
prefix building fails with special symbols

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#382]
If key contains `/` for example

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.6`

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#382](https://github.com/zold-io/zold/issues/382) is now out of scope
