### ISSUE TITLE
remove non-production wallets on start

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#384]
Let's kill wallets that belong to another network, on start.

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#385](https://github.com/zold-io/zold/issues/385) is still not solved.

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.8`

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#384` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#385](https://github.com/zold-io/zold/issues/385) is solved here.
