### ISSUE TITLE
zold:141-143: This is a workaround, move this code into...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/zold#385]
The puzzle `384-9943eeb2` from #384 has to be resolved:

https://github.com/zold-io/zold/blob/9406401e7e48ae30e18550c258352456d5a533e3/bin/zold#L141-L143

The puzzle was created by Yegor Bugayenko on 11-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#385](https://github.com/zold-io/zold/issues/385) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#385](https://github.com/zold-io/zold/issues/385) assigned to @vl3[/z](https://www.0crat.com/u/vl3), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/776c8c18-8ab9-443c-9809-3fe77bc939bc); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@vl3[/z](https://www.0crat.com/u/vl3) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by vl3** [comment]
@0crat resign

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/zold-io/zold/issues/385#issuecomment-439741077))

@vl3 The user @vl3[/z](https://www.0crat.com/u/vl3) resigned from [#385](https://github.com/zold-io/zold/issues/385), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @vl3[/z](https://www.0crat.com/u/vl3)

**Comment by 0crat** [comment]
The job [#385](https://github.com/zold-io/zold/issues/385) assigned to @sergeykutsko[/z](https://www.0crat.com/u/sergeykutsko), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/458647f8-3c4d-4489-845c-ee9695194647); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@sergeykutsko[/z](https://www.0crat.com/u/sergeykutsko) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `384-9943eeb2` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @sergeykutsko[/z](https://www.0crat.com/u/sergeykutsko), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#385](https://github.com/zold-io/zold/issues/385) is now out of scope

**Comment by ypshenychka** [comment]
@SergeyKutsko According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues

Only one commit contains link to issue. Please confirm you'll try to follow this rule next time.

**Comment by SergeyKutsko** [comment]
@ypshenychka  ok, but t have only 1 commit. other are merges

**Comment by ypshenychka** [comment]
@SergeyKutsko Thanks for clarification. Then no comments from my side :)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @sergeykutsko[/z](https://www.0crat.com/u/sergeykutsko)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
