### ISSUE TITLE
'zold push' require HTTP 200 instead of 202

### ISSUE THREAD

**Issue by DronMDF** [zold-io/zold#386]
Rest API PUT /wallet/<id> should return 202 http status as it is written in WP.

Instead I see error:
```sh
$ zold push ff96a73c5d6a7a30
localhost:8000: ACCEPTED (HTTP code 202, instead of 200) in 0s; errors=1
ERROR: No nodes out of 1 accepted the wallet ff96a73c5d6a7a30 (RuntimeError)
```

**Comment by yegor256** [comment]
@DronMDF what is the version you are using? I don't see anywhere in our code where 202 is returned.

**Comment by DronMDF** [comment]
I use alternative node implementation.

White paper require 202:
![image](https://user-images.githubusercontent.com/2982959/42632555-3b532bcc-85e6-11e8-8ccd-dffa2b676fcb.png)

**Comment by yegor256** [comment]
@DronMDF This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#386` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
