### ISSUE TITLE
Difference between FETCH and PULL

### ISSUE THREAD

**Issue by llorllale** [zold-io/zold#387]
Over at [zold-io/java-api](https://github.com/zold-io/java-api/issues/5#issuecomment-402911750) we're asking if there are supposed to be the semantic differences between the verbs "fetching" vs "pulling" a wallet? Do they have different meanings or are they the same concept?

Looking through the ruby code, I *think* `fetch` will just download all versions of your wallets from the network, whereas `pull` will fetch *and* merge. Am I wrong?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@llorllale that's, right: FETCH will only download, while PULL will fetch and merge. Just like it works in Git.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#387` is not assigned, can't get performer
