### ISSUE TITLE
test_remote.rb:120-122: Verify that the nodes that are...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/zold#388]
The puzzle `329-08487f44` from #329 has to be resolved:

https://github.com/zold-io/zold/blob/3cd5cd12df2989c95aa02091d9f6aa5174aef5e2/test/commands/test_remote.rb#L120-L122

The puzzle was created by James C Russell on 06-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#388](https://github.com/zold-io/zold/issues/388) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#388](https://github.com/zold-io/zold/issues/388) assigned to @vl3[/z](https://www.0crat.com/u/vl3), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/2e3d9836-8df5-41b5-8093-66c506e77fed); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@vl3[/z](https://www.0crat.com/u/vl3) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by vl3** [comment]
#559

**Comment by vl3** [comment]
@0crat waiting for review #559

**Comment by 0crat** [comment]
> @0crat waiting for review #559  ([here](https://github.com/zold-io/zold/issues/388#issuecomment-439648530))

@vl3 The impediment for [#388](https://github.com/zold-io/zold/issues/388) was registered successfully by @vl3[/z](https://www.0crat.com/u/vl3)

**Comment by 0pdd** [comment]
The puzzle `329-08487f44` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#388](https://github.com/zold-io/zold/issues/388) is now out of scope

**Comment by ypshenychka** [comment]
@vl3 According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Ticket must have references to all pull requests where the problem was actually fixed

Please add reference to appropriate PR (e.g. by referencing this issue in PR's description). #559 seems to be fixing another issue.

**Comment by ypshenychka** [comment]
@vl3 According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](https://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to

Please indicate addressee in the beginning of your [message](https://github.com/zold-io/zold/issues/388#issuecomment-439648083).

**Comment by ypshenychka** [comment]
@vl3 Thanks. Please also correct your message by indicating addressee, so we could proceed with this ticket.

**Comment by vl3** [comment]
@ypshenychka I removed it.
