### ISSUE TITLE
Optimize `Enumerable#find` 

### ISSUE THREAD

**Issue by liligga** [zold-io/zold#390]
I have noticed some usage of `find` in places like [here](https://github.com/zold-io/zold/blob/master/lib/zold/wallet.rb#L136)

          !txns.find { |t| t.id == id && t.bnf == bnf }.nil?

or [here](https://github.com/zold-io/zold/blob/master/lib/zold/wallet.rb#L127)

          dup = txns.find { |t| t.bnf == txn.bnf && t.id == txn.id }

Taking into account that this project is claimed as fast cryptocurrency I think Ruby's `Array#bsearch` or `Array#bsearch_index` methods shoud be used in such cases. [Here is the doc for 2.3.3 version of Ruby of that method](https://ruby-doc.org/core-2.3.3/Array.html#method-i-bsearch) and [here as well](https://ruby-doc.org/core-2.3.3/Array.html#method-i-bsearch_index)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@liligga[/z](https://www.0crat.com/u/liligga) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by liligga** [comment]
Ok, I do realize this works with sorted arrays. What I was not sure about was if `bnf` and `id` of transactions are actually sorted. @yegor256 please close this issue if I am wrong.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#390` is not assigned, can't get performer
