### ISSUE TITLE
Travis configuration to test against newer Ruby Version

### ISSUE THREAD

**Issue by emilianodellacasa** [zold-io/zold#391]
When working on issue #306 a problem has been seen with the docker container that Rultor is using for the merge part. 

Apparently (https://github.com/yegor256/rultor/issues/1267) operators are not supported in _Gemfile_, whereas are correctly recognized by Travis.

When the above mentioned issue is solved, we should modify the Travis setting file to test everything against newer ruby versions, for example:

  - 2.4.4
  - 2.5.1
  - ruby-2.6.0-preview1

These are the available ruby versions on Travis

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@emilianodellacasa fixed in e999b8f thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#391` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
