### ISSUE TITLE
Invoice regexp is not complete

### ISSUE THREAD

**Issue by DronMDF** [zold-io/zold#392]
Prefix part of invoice contain random choised symbol sequence from public key.
RSA public key can contain special characters. '+' and '/' and '=' for padding
Check regex not pass this symbols.

```ruby
raise "Invoice is wrong: #{json}" unless json['invoice'] =~ /^[a-zA-Z0-9]{8,32}@[a-f0-9]{16}$/
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dronmdf[/z](https://www.0crat.com/u/dronmdf) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@DronMDF this is intentional. Even though the RSA key may have special symbols, the invoice can't.

**Comment by DronMDF** [comment]
@yegor256 How to generate and check it?
Select all alfanumeric syms from RSA key and use this sequence?
Ok, this is possible.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#392` is not assigned, can't get performer

**Comment by yegor256** [comment]
@DronMDF yes, something like that. The algorithm is in `Prefixes` class.
