### ISSUE TITLE
http.rb:53-58: The following two statements are seen as...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/zold#393]
The puzzle `98-ed836320` from #98 has to be resolved:

https://github.com/zold-io/zold/blob/cdb06a0b8a2f2814c2aa933756e5db4c2d7063ab/lib/zold/http.rb#L53-L58

The puzzle was created by Emiliano Della Casa on 12-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#393](https://github.com/zold-io/zold/issues/393) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `98-ed836320` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#393` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#393](https://github.com/zold-io/zold/issues/393) is now out of scope
