### ISSUE TITLE
"history" is empty in most nodes

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#395]
For some reason "history" is almost empty in the majority of nodes.

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.9`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.9`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#395` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#395](https://github.com/zold-io/zold/issues/395) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1970814094); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @yegor256[/z](https://www.0crat.com/u/yegor256) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) resigned from [#395](https://github.com/zold-io/zold/issues/395), since the job is not in scope anymore

**Comment by 0crat** [comment]
The job [#395](https://github.com/zold-io/zold/issues/395) is now out of scope

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#395` doesn't exist in WBS, can't create order
