### ISSUE TITLE
front-end threads conflict with score counting threads

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#397]
Look at this page: http://www.zold.io/health.html You see that "ping" is huge for the majority of nodes, except `b1.zold.io`, which doesn't run any score calculating threads. We should find a way to isolate our front-end threads from score threads, to make sure the front end is always fast.

**Comment by yegor256** [comment]
@oltdaniel would you be interested to take a look?

**Comment by yegor256** [comment]
It's a dup of #412

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#397` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
