### ISSUE TITLE
Wallet not found, even though it was successfully pushed (from another machine)

### ISSUE THREAD

**Issue by pawlik** [zold-io/zold#398]
I created a wallet locally, and then did 

```
$ zold --version
0.14.8
$ zold push ddbe1d024a1100d6 
b1.zold.io:80/0 accepted 1442b/eac61e/0t of ddbe1d024a1100d6 in 0.52s: 0 (0.14.8)
Push finished to 1 nodes out of 1, total score for ddbe1d024a1100d6 is 0
```

On another server (digital ocean droplet) I get the info that the wallet is unknown by the node

```
$ zold --version
0.14.8
$ zold node --invoice=ddbe1d024a1100d6
Home directory: /root
Ruby version: 2.4.4
Zold gem version: 0.14.8
Zold protocol version: 2
Network ID: zold
Node location: 178.128.192.36:4096
The wallet ddbe1d024a1100d6 is not available locally, will pull now...
b1.zold.io:80: Wallet ddbe1d024a1100d6 not found in 0s; errors=8
ERROR: No nodes out of 1 have the wallet ddbe1d024a1100d6 (RuntimeError)
```

I think, since the push was successful - new node should be able to fetch this wallet (?). The first successful push was already yesterday, and even today I can't start the node with this wallet ID.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@pawlik[/z](https://www.0crat.com/u/pawlik) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@pawlik I believe it's fixed. Try again and report a new issue if you still see the problem.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#398` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
