### ISSUE TITLE
ruby version back to 2.3.1

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#400]
Most nodes have 2.3.1. 2.3.3 is not installed there, that's why our nodes don't start.

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.11`

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#400` is not assigned, can't get performer
