### ISSUE TITLE
Default network value is "test"

### ISSUE THREAD

**Issue by emilianodellacasa** [zold-io/zold#408]
After a fresh install of zold package, I tried running a node specifying my wallet id, but the error for all nodes was:

"The wallet 25e0819b40cf7eb6 is in network 'zold', while we are in 'test' in 7s;"

At the beginning, zold command gives me following informatino regarding my node:

Home directory: /opt/zold
Ruby version: 2.3.3
Zold gem version: 0.14.15
Zold protocol version: 2
Network ID: zold

Even if I run using "--network" params, it gives me the same error

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by emilianodellacasa** [comment]
@yegor256 Here is the problem: https://github.com/zold-io/zold/blame/master/lib/zold/commands/fetch.rb#L65 

When the network parameter is not passed to the command, "test" network is used. Either we should pass the param, or change the default value to "zold"

**Comment by 0crat** [comment]
Job [#408](https://github.com/zold-io/zold/issues/408) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
The job [#408](https://github.com/zold-io/zold/issues/408) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1990755920); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @yegor256[/z](https://www.0crat.com/u/yegor256) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@emilianodellacasa fixed

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#408](https://github.com/zold-io/zold/issues/408) is now out of scope
