### ISSUE TITLE
Travis failing from time to time because of long test time

### ISSUE THREAD

**Issue by emilianodellacasa** [zold-io/zold#419]
Now that the test suite for Zold is growing, it happens from time to time that Travis gives the following error:

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

This could be due to a slow process that is not giving output, so we should modify the travis script as suggested here:

https://stackoverflow.com/questions/28746046/how-can-i-install-something-on-travis-ci-without-a-timeout/28833319#28833319

for Travis to wait more.

**Comment by oltdaniel** [comment]
@yegor256 Debugging the test cases would be a better solution, since a test case shouldn't run for more than 10minutes. Expanding the test time doesn't solves the problem.

**Comment by emilianodellacasa** [comment]
@oltdaniel There are already many issues addressing test cases problem, but I agree with you: modifying Travis configuration would be a temporary solution. My opinion is to update this issue to analyze test cases, identify the critical tests and adding a puzzle for each one (if it doesn't have one already).

Do you agree with it @yegor256?

**Comment by yegor256** [comment]
@emilianodellacasa  This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#419` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
