### ISSUE TITLE
type.rb:23-27: Right now only Score, Http, Zold::Remotes...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/zold#421]
The puzzle `394-fda9e6d8` from #394 has to be resolved:

https://github.com/zold-io/zold/blob/5999af1a206993962b15b9d6ef634627ff98b01c/lib/zold/type.rb#L23-L27

The puzzle was created by rultor on 26-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#421](https://github.com/zold-io/zold/issues/421) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `394-fda9e6d8` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#421` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#421](https://github.com/zold-io/zold/issues/421) is now out of scope
