### ISSUE TITLE
Move from MRI to JRuby 

### ISSUE THREAD

**Issue by emilianodellacasa** [zold-io/zold#429]
As stated in one of the most recent [blog posts](https://blog.zold.io/2018/07/20/why-ruby.html), Ruby as been chosen as the programming language for Zold for its clearness, easyness to deploy and compactness.

However, one of the drawbacks of MRI is its slowness and the fact that is not taking advantage of multiple cores.

However, [Jruby](http://jruby.org/) seems to overcome these limitations. In fact, Jruby is a fully threaded Java implementation of Ruby that could give Zold the following perks:

- increase performance;
- being fully threaded (as Jruby is based on JVM);
- support up to ruby 2.5;
- the possibility to use java packages inside ruby code;

Of course, before moving to JRuby we should have a strong test base to be sure that nothing breaks but that would surely benefit the whole project IMHO.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#429](https://github.com/zold-io/zold/issues/429) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by oshanz** [comment]
@emilianodellacasa title should be changed to "Move from MRI to JRuby", also 

> drawbacks of Ruby is its slowness

should change to "drawbacks of MRI is its slowness"

**Comment by emilianodellacasa** [comment]
@oshanz You are right,

**Comment by yegor256** [comment]
@emilianodellacasa I don't see any performance issues at the moment. If we see them in the future, we should move to Java natively, not Ruby+Java, I believe. Or maybe some other language, like Go.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#429` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#429](https://github.com/zold-io/zold/issues/429) is now out of scope
