### ISSUE TITLE
 The transaction with the same ID and BNF already exists

### ISSUE THREAD

**Issue by ljrossi** [zold-io/zold#435]
I make a wallet , and transfer zolds to it and from it to others wallets.

After that I make a backup of keys id_rsa and id_rsa.pub and erase them for testing porpuse.

When I copy again keys files id_rsa and id_rsa.pub i get the following ERROR and try to make a new PAY i get 

"" The transaction with the same ID and BNF already exists : 
 0002;2018-07-29T20:28:32Z;0000000019999999;Ilo7ykkN;f6512d172fe1898e;test2  ""

Is this a bug or Im missing something ?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ljrossi[/z](https://www.0crat.com/u/ljrossi) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@ljrossi I can't understand what should I do in order to reproduce it... Can you make a test?

**Comment by ljrossi** [comment]
And now it works ....

First I remove wallet   
rm  9xxxxxxxxxxxx.z
I make backup of keys
cp id* /backup/
delete keys from ssh folder
rm id_rsa*
restore keys to folder
cp -R backup/id* root/.ssh/.
pull wallet
pay

Actually I couldnt reproduce it again....  If it comes back i will try to pay atention on the steps....I think it was a wrong id_rsa file .. or I tryed to create again the wallet, or some mistake of that sort....because before that it did give me a permision error for spending on the backuped wallet.

**Comment by yegor256** [comment]
@ljrossi This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#435` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
