### ISSUE TITLE
--max-nodes for elect

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#436]
Let's add the option `--max-nodes`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.24`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.24`

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#436` is not assigned, can't get performer

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.24`
