### ISSUE TITLE
sorting of transactions is not strong enough

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#445]
It has to be more precise

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.27`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ee5f821e-71b5-4706-b3c9-61ba92e4e645, thread: pool-164-thread-1
java.lang.NumberFormatException[65] java.lang.NumberFormatException: For input string: "2018-08-04T13:41:43.89Z"
```

[0.28.15](https://github.com/zerocracy/farm): Issue: zold-io/zold#445, Action: `closed`
