### ISSUE TITLE
node - no new wallets received

### ISSUE THREAD

**Issue by oltdaniel** [zold-io/zold#448]
My node ([z.oltdaniel.tk](http://z.oltdaniel.tk:4096)) is not receiving any new wallets. It is listed in [b1.zold.io](http://b1.zold.io) and should receive some randomly pushed wallets, but my wallet count is at 4 since a week, which have been all fetched manually

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@oltdaniel it seems that the problem is that your score is too low (2). Other nodes will only discover you when your score is 4+. Below that number, they simply ignore you and don't add to their lists of remotes.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#448` is not assigned, can't get performer
