### ISSUE TITLE
Tax payment spread out among several remote nodes

### ISSUE THREAD

**Issue by llorllale** [zold-io/zold#450]
[Taxes](https://github.com/zold-io/zold/blob/de24951af760c7003b5ea96077f20c597d3c9399/lib/zold/commands/taxes.rb#L102-L121) are being paid out to several remote nodes. This contradicts the whitepaper (emphasis mine):

> In order to pay taxes **the owner of the wallet must select a remote node** from
the network with a score of 16 or more.  Then, it has to take the invoice
from the score, request the node to lock the score for a minute, and send the
payment of 1 ZLD or less to that node.  The score with exactly 16 suffixes
has to be placed into the details of the transaction, prefixed by
TAXES

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@llorllale This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
This job is not in scope
