### ISSUE TITLE
Wrong max_queue parameter value in AsyncEntrance

### ISSUE THREAD

**Issue by baybatu** [zold-io/zold#452]
in https://github.com/zold-io/zold/blob/1087688e10b43865d014c930864875971c0163c1/lib/zold/node/async_entrance.rb#L68

FixedThreadPool is initialized with `THREADS` constant for `max_queue` parameter. Instead, it must be created with already defined `MAX_QUEUE` constant for bigger queue size.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@baybatu fixed, thanks!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#452` is not assigned, can't get performer
