### ISSUE TITLE
show load average

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#463]
Let's show it in the front

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#463` is not assigned, can't get performer

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.35`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.36`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.36`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@3e076050-65c0-41af-834d-8d7ba1effd0f, thread: AsyncProc-5
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:zold-io/zold#463] declared for identity constraint of element "blanks".
```

[0.30.4](https://github.com/zerocracy/farm): CID: [2281249063](https://www.0crat.com/CAZPZR9FS/2281249063), Type: "Close job", Author: "yegor256"

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#463` is not assigned, can't get performer
