### ISSUE TITLE
empty remotes - every remote will be droped

### ISSUE THREAD

**Issue by oltdaniel** [zold-io/zold#468]
At some point of time, the nodes will drop every remote. _(Observed on the `wts.zold.io` node and my own one)_

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@oltdaniel can you explain how to reproduce this?

**Comment by yegor256** [comment]
@oltdaniel This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
This job is not in scope
