### ISSUE TITLE
Cannot create a new wallet - ERROR: Permission denied @ fptr_finalize_flush

### ISSUE THREAD

**Issue by alekseysotnikov** [zold-io/zold#469]
Here is a log
> F:\zold>zold --version
> 0.14.38
> 
> F:\zold>zold create fd848c68c7c6aea6
> ERROR: Permission denied @ fptr_finalize_flush - F:/zold/.zoldata/locks/fd848c68c7c6aea6 (Errno::EACCES)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@alekseysotnikov[/z](https://www.0crat.com/u/alekseysotnikov) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#469](https://github.com/zold-io/zold/issues/469) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Thanks for your contribution, @alekseysotnikov[/z](https://www.0crat.com/u/alekseysotnikov)! If you would be a member of [the project](https://www.0crat.com/p/CAZPZR9FS), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by yegor256** [comment]
@alekseysotnikov I can't reproduce it. Looks like it's a local problem with permissions. Are you sure this directory is write-accessible?

**Comment by alekseysotnikov** [comment]
Yes. All CRUD commands works fine in the directory. Moreover, the folder `.zoldata` created by Zold.

**Comment by yegor256** [comment]
@alekseysotnikov This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
The job [#469](https://github.com/zold-io/zold/issues/469) is now out of scope
