### ISSUE TITLE
Add Documentation on a per class/module/method basis

### ISSUE THREAD

**Issue by liligga** [zold-io/zold#470]
Add documentation Inside source code for each method like in Rails for instance. Good starting point for this purpose is [YARD](https://github.com/lsegal/yard) which generates it.
This task seems to be pretty big though, so maybe it would be better to divide it into separate subtasks per class

- age
- amount
- atomic_file
etc

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@liligga[/z](https://www.0crat.com/u/liligga) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#470](https://github.com/zold-io/zold/issues/470) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @liligga[/z](https://www.0crat.com/u/liligga)

**Comment by dapi** [comment]
Will be nice to describe classes in head of it

**Comment by yegor256** [comment]
@liligga this task is indeed too big, we can't implement it. We should go class by class, when information is indeed required. When you see a specific place where information is missing, create a ticket.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#470` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#470](https://github.com/zold-io/zold/issues/470) is now out of scope
