### ISSUE TITLE
X-Zold-Score format parsing error

### ISSUE THREAD

**Issue by DronMDF** [zold-io/zold#474]
This is example request...

```sh
curl -v --header "X-Zold-Score: 3/6: 2018-08-26T19:49:13Z 37.230.116.39 4096 RxLYPMuU@cc53e22229564de6 8QzKabk PdT1ZY6 5CS9Ciz" b2.zold.io:4096
```

Cause error
```
Dry::Struct::Error: [Zold::Score.new] "RxLYPMuU@cc53e22229564de6@8QzKabk" (String) has invalid type for :invoice violates constraints (format?(/^[a-zA-Z0-9]{8,32}@[a-f0-9]{16}$/, "RxLYPMuU@cc53e22229564de6@8QzKabk") failed)
	/var/lib/gems/2.3.0/gems/dry-struct-0.5.0/lib/dry/struct/class_interface.rb:208:in `rescue in new'
	/var/lib/gems/2.3.0/gems/dry-struct-0.5.0/lib/dry/struct/class_interface.rb:202:in `new'
	/var/lib/gems/2.3.0/gems/zold-0.14.38/lib/zold/score.rb:89:in `parse_text'
	/var/lib/gems/2.3.0/gems/zold-0.14.38/lib/zold/node/front.rb:100:in `block (2 levels) in <class:Front>'
	/var/lib/gems/2.3.0/gems/zold-0.14.38/lib/zold/node/front.rb:393:in `check_header'
* Closing connection 0
	/var/lib/gems/2.3.0/gems/zold-0.14.38/lib/zold/node/front.rb:96:in `block in <class:Front>'
```

This is strange, because server response contain X-Zlod-Score in same format:
```
X-Zold-Score: 9/6: 2018-08-19T12:20:17Z b2.zold.io 4096 kiG9w0BA@912ecc24b32dbe74 adcbd9 ed5c77 bf0f6 869ae5 437b6a 17e0300 1768685 237cd1 115919f
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dronmdf[/z](https://www.0crat.com/u/dronmdf) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#474](https://github.com/zold-io/zold/issues/474) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @dronmdf[/z](https://www.0crat.com/u/dronmdf)

**Comment by yegor256** [comment]
@DronMDF This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#474` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#474](https://github.com/zold-io/zold/issues/474) is now out of scope

**Comment by DronMDF** [comment]
@yegor256 Thank's
