### ISSUE TITLE
pull #473 - C extension windows support

### ISSUE THREAD

**Issue by oltdaniel** [zold-io/zold#475]
Required by https://github.com/zold-io/zold/pull/473

### Notes
The C extension is only made for unix systems. There a few things left that need to be solved in order to make this new extension work on every system.

### Todo

- [ ] `Process#fork` is not supported on windows systems ([see here](https://ruby-doc.org/core-2.1.2/Process.html#method-c-fork))
- [ ] The Rake task `:compile` is using `clang` to build a shared library. The command used is for unix only and needs to be modified for windows systems.

**Comment by yegor256** [comment]
@oltdaniel is it a bug or what is it? I didn't get it...

**Comment by oltdaniel** [comment]
It is an issue for the pull request adding the C Extension.

**Comment by yegor256** [comment]
@oltdaniel how a pull request may have an issue? :) Let's deal with the pull request issues inside the pull request, please

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#475` is not assigned, can't get performer
