### ISSUE TITLE
Timestamp in logs

### ISSUE THREAD

**Issue by emilianodellacasa** [zold-io/zold#478]
Right now the log file is really messy and when searching for an issue it is difficult to investigate basing on time.

In the log file the timestamp should be included in the beginning of the line, it should be used the standard linux log format

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by yegor256** [comment]
@emilianodellacasa implemented, via `--pretty` argument

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#478` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#478](https://github.com/zold-io/zold/issues/478) is now out of scope
