### ISSUE TITLE
Remote update command is not working

### ISSUE THREAD

**Issue by emilianodellacasa** [zold-io/zold#480]
I have noticed that my node didn't have any remote but b1.zold.io so I tried a _zold remote update_ command but it yielded:

b1.zold.io:80: JSON is empty, can't parse in 0s

However, if I call _b1.zold.io:80/remotes_ I can see the correct JSON

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@emilianodellacasa this is the problem:

```
RuntimeError: JSON is empty, can't parse
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.14.39/lib/zold/json_page.rb:39:in `to_hash'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.14.39/lib/zold/gem.rb:43:in `last_version'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.14.39/lib/zold/commands/remote.rb:229:in `block in update'
	/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.14.39/lib/zold/remotes.rb:193:in `block (2 levels) in iterate'
```

**Comment by 0crat** [comment]
The job [#480](https://github.com/zold-io/zold/issues/480) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/2760722623); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by emilianodellacasa** [comment]
@yegor256 Itt is surely related to the http call to rubygems

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.40`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.40`

**Comment by 0crat** [comment]
Job was finished in 4 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#480](https://github.com/zold-io/zold/issues/480) is now out of scope

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.40`

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.40`
