### ISSUE TITLE
wallet.rb is too slow

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#484]
It reads the file and parses it multiple times.

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.43`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.43`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.43`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#484` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
