### ISSUE TITLE
Lost transactions

### ISSUE THREAD

**Issue by DronMDF** [zold-io/zold#498]
Example:

Wallet d6a26bb10d56746b have one transactions from 221255bc9af7baec:
```
06b3;2018-10-09T10:42:00Z;00000000028f5c28;Y2NQ9rGl;221255bc9af7baec;31b5baf2-0645-4825-af23-e2f0efa0e64b;
```
Wallet 221255bc9af7baec does not have this transactions.

This creates a situation where the recipient’s wallet can dispose of money that it has not received.
Incoming transaction must be recognized as invalid and must be removed from the wallet.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dronmdf[/z](https://www.0crat.com/u/dronmdf) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@DronMDF 
This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
This job is not in scope
