### ISSUE TITLE
--disable-pull and --disable-push

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#499]
Let's make it possible to disable pull and push

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.53`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.53`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.53`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#499` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
