### ISSUE TITLE
show node current traffic

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#501]
Let's collect the traffic metrics and show them in the front JSON

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.1`

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.2`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#501` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
