### ISSUE TITLE
Why it is should stay as run time dependency?

### ISSUE THREAD

**Issue by SergeyKutsko** [zold-io/zold#502]
https://github.com/zold-io/zold/blob/e4332805ab78db66eb1157485ba9190048c5e3a0/zold.gemspec#L60

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@SergeyKutsko dup of #346

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#502` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
