### ISSUE TITLE
Use compact instead of reject(&:nil?)

### ISSUE THREAD

**Issue by SergeyKutsko** [zold-io/zold#504]
https://github.com/zold-io/zold/blob/e4332805ab78db66eb1157485ba9190048c5e3a0/lib/zold/tax.rb#L89

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@SergeyKutsko fixed in 6510404 thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#504` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
