### ISSUE TITLE
Dry out #get and #put methods as they have identicall parts

### ISSUE THREAD

**Issue by SergeyKutsko** [zold-io/zold#505]
https://github.com/zold-io/zold/blob/e4332805ab78db66eb1157485ba9190048c5e3a0/lib/zold/http.rb#L74-L79

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@SergeyKutsko I don't understand what do you want to replace with what?

**Comment by SergeyKutsko** [comment]
We have same code in get and put methods:
`def get
      _**http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      http.read_timeout = Http::READ_TIMEOUT
      http.open_timeout = Http::CONNECT_TIMEOUT
      path = uri.path
      path += '?' + uri.query if uri.query
      Timeout.timeout(Http::READ_TIMEOUT + Http::CONNECT_TIMEOUT) do**_
        http.request_get(path, headers)
      end
    rescue StandardError => e
      Error.new(e)
    end

    def put(body)
      **_http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      http.read_timeout = Http::READ_TIMEOUT
      http.open_timeout = Http::CONNECT_TIMEOUT
      path = uri.path
      path += '?' + uri.query if uri.query
      Timeout.timeout(Http::READ_TIMEOUT + Http::CONNECT_TIMEOUT) do_**
        http.request_put(
          path, body,
          headers.merge(
            'Content-Type': 'text/plain',
            'Content-Length': body.length.to_s
          )
        )
      end
    rescue StandardError => e
      Error.new(e)
    end`

we can dry it: 

`def request
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = uri.scheme == 'https'
    http.read_timeout = Http::READ_TIMEOUT
    http.open_timeout = Http::CONNECT_TIMEOUT
    path = uri.path
    path += '?' + uri.query if uri.query
    Timeout.timeout(Http::READ_TIMEOUT + Http::CONNECT_TIMEOUT) do
       yield(path, headers, body)
    end
rescue StandardError => e
      Error.new(e)
end`

`def get
   request do |path, headers|
      http.request_get(path, headers)
   end
end`

`def put
   request do |path, headers, body|
      http.request_put(
          path, body,
          headers.merge(
            'Content-Type': 'text/plain',
            'Content-Length': body.length.to_s
          )
        )
   end
end`

**Comment by 0crat** [comment]
Job [#505](https://github.com/zold-io/zold/issues/505) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @sergeykutsko[/z](https://www.0crat.com/u/sergeykutsko)

**Comment by yegor256** [comment]
@SergeyKutsko This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#505` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#505](https://github.com/zold-io/zold/issues/505) is now out of scope
