### ISSUE TITLE
Propose to replace list.map { |r| r[:score] }.max  || 0 by max_score = list.empty? ? 0 : list.max_by { |r| r[:score] }[:score]

### ISSUE THREAD

**Issue by SergeyKutsko** [zold-io/zold#506]
https://github.com/zold-io/zold/blob/e4332805ab78db66eb1157485ba9190048c5e3a0/lib/zold/remotes.rb#L124-L126

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@SergeyKutsko I don't get it... Can you please explain what you want in the description of the ticket, not in the title? :)

**Comment by SergeyKutsko** [comment]
@yegor256 I propose to replace this line of code:
`max_score = list.map { |r| r[:score] }.max || 0 `
by:
`max_score = list.empty? ? 0 : list.max_by { |r| r[:score] }[:score]`

**Comment by 0crat** [comment]
Job [#506](https://github.com/zold-io/zold/issues/506) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @sergeykutsko[/z](https://www.0crat.com/u/sergeykutsko)

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.31`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#506` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#506](https://github.com/zold-io/zold/issues/506) is now out of scope
