### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by SergeyKutsko** [zold-io/zold#509]
```
bin/zold --ignore-this-stupid-option --halt-code=test --ignore-global-config --trace --network=test --no-colors --dump-errors node --trace --invoice=NOPREFIX@ffffffffffffffff --host=localhost --port=60127 --bind-port=60127 --threads=0 --standalone
```
Time: 2018-10-30T14:25:43Z
Home directory: /home/serg/projects/zold
Ruby version: 2.3.0
Zold gem version: 0.0.0
Zold protocol version: 2
Network ID: test
Node location: localhost:60127
Local address: http://localhost:60127/
Remote nodes (6): b1.zold.io:80, b2.zold.io:4096, 159.203.63.90:4096, 167.99.77.100:4096, 159.203.19.189:4096, 138.197.140.42:4096
Wallets at: /home/serg/projects/zold
Running in standalone mode! (will never talk to other remotes)
Zero-threads farm won't score anything!
1 scores pre-loaded, the best is: 0/6: 2018-10-30T14:25:43Z localhost 60127 NOPREFIX@ffffffffffffffff
Farm started with 0 threads at localhost:60127, strength is 6
Added Zold::Routines::Spread to the metronome
Metronome started (use --no-metronome to disable it)
Starting up the web front at http://localhost:60127...
Routine Zold::Routines::Spread #0 done in 0ms
Stopping the metronome with 1 threads: Zold::Routines::Spread-0
Thread Zold::Routines::Spread-0 finished in 904ms
Metronome stopped in 904ms, 0 failures
Terminating the farm with 0 threads...
Attempting to terminate the thread "cleanup"...
It's time to stop the cleanup thread (10 != 600, alive=false)...
Thread "cleanup" finished in 100ms
Farm stopped in 100ms
Stopping async entrance, pool length is 8, queue length is 0
Async entrance terminated peacefully
Waiting for spread entrance to finish...
Spread entrance finished, thread killed
/home/serg/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': incompatible library version - /home/serg/.rvm/gems/ruby-2.3.0/gems/puma-3.12.0/lib/puma/puma_http11.so (LoadError)
	from /home/serg/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/serg/.rvm/gems/ruby-2.3.0/gems/puma-3.12.0/lib/puma/server.rb:15:in `<top (required)>'
	from /home/serg/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/serg/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/serg/.rvm/gems/ruby-2.3.0/gems/puma-3.12.0/lib/puma/runner.rb:1:in `<top (required)>'
	from /home/serg/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/serg/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/serg/.rvm/gems/ruby-2.3.0/gems/puma-3.12.0/lib/puma/cluster.rb:1:in `<top (required)>'
	from /home/serg/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/serg/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/serg/.rvm/gems/ruby-2.3.0/gems/puma-3.12.0/lib/puma/launcher.rb:4:in `<top (required)>'
	from /home/serg/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/serg/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/serg/.rvm/gems/ruby-2.3.0/gems/puma-3.12.0/lib/rack/handler/puma.rb:15:in `config'
	from /home/serg/.rvm/gems/ruby-2.3.0/gems/puma-3.12.0/lib/rack/handler/puma.rb:62:in `run'
	from /home/serg/.rvm/gems/ruby-2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1525:in `start_server'
	from /home/serg/.rvm/gems/ruby-2.3.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1459:in `run!'
	from /home/serg/projects/zold/lib/zold/commands/node.rb:251:in `block (3 levels) in run'
	from /home/serg/projects/zold/lib/zold/metronome.rb:87:in `start'
	from /home/serg/projects/zold/lib/zold/commands/node.rb:248:in `block (2 levels) in run'
	from /home/serg/projects/zold/lib/zold/node/farm.rb:115:in `start'
	from /home/serg/projects/zold/lib/zold/commands/node.rb:246:in `block in run'
	from /home/serg/projects/zold/lib/zold/node/safe_entrance.rb:49:in `block in start'
	from /home/serg/projects/zold/lib/zold/node/nodup_entrance.rb:45:in `block in start'
	from /home/serg/projects/zold/lib/zold/node/async_entrance.rb:84:in `block in start'
	from /home/serg/projects/zold/lib/zold/node/spread_entrance.rb:81:in `block in start'
	from /home/serg/projects/zold/lib/zold/node/sync_entrance.rb:51:in `block in start'
	from /home/serg/projects/zold/lib/zold/node/entrance.rb:53:in `start'
	from /home/serg/projects/zold/lib/zold/node/sync_entrance.rb:50:in `start'
	from /home/serg/projects/zold/lib/zold/node/spread_entrance.rb:59:in `start'
	from /home/serg/projects/zold/lib/zold/node/async_entrance.rb:66:in `start'
	from /home/serg/projects/zold/lib/zold/node/nodup_entrance.rb:45:in `start'
	from /home/serg/projects/zold/lib/zold/node/safe_entrance.rb:49:in `start'
	from /home/serg/projects/zold/lib/zold/commands/node.rb:243:in `run'
	from bin/zold:186:in `<main>'

**Comment by yegor256** [comment]
@SergeyKutsko please, try to pick more descriptive titles for your bug reports. Also, please, use Markdown to format the description.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#509` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
