### ISSUE TITLE
400 on PUT is not returned

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#51]
Let's return 400 on PUT if there are any errors on "merge". The client has to know that something was wrong. Let's also show the stacktrace.

**Comment by 0crat** [comment]
Job [#51](https://github.com/zold-io/zold/issues/51) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#51](https://github.com/zold-io/zold/issues/51), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
The job [#51](https://github.com/zold-io/zold/issues/51) assigned to @jedediah[/z](https://www.0crat.com/u/jedediah), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1920718796); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@jedediah[/z](https://www.0crat.com/u/jedediah) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#51` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#51](https://github.com/zold-io/zold/issues/51) is now out of scope
