### ISSUE TITLE
test_dir_items.rb:54-56: I don't understand why this test...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/zold#511]
The puzzle `507-040930f5` from #507 has to be resolved: 

https://github.com/zold-io/zold/blob/e98bc5cdaff46f0f7ac85af2bc8145549d9984ec/test/test_dir_items.rb#L54-L56

The puzzle was created by Yegor Bugayenko on 30-Oct-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#511](https://github.com/zold-io/zold/issues/511) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#511](https://github.com/zold-io/zold/issues/511) assigned to @babbarkrishan[/z](https://www.0crat.com/u/babbarkrishan), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/02ca6e9a-a8cf-4339-a388-2d343ee01ef6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@babbarkrishan[/z](https://www.0crat.com/u/babbarkrishan) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The job [#511](https://github.com/zold-io/zold/issues/511) assigned to @vl3[/z](https://www.0crat.com/u/vl3), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/16af0d51-ea3b-45cb-ab8d-6873b1761054); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@vl3[/z](https://www.0crat.com/u/vl3) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by vl3** [comment]
@0crat wait

**Comment by vl3** [comment]
@0crat  waiting for review #579

**Comment by 0crat** [comment]
> @0crat waiting for review #579  ([here](https://github.com/zold-io/zold/issues/511#issuecomment-442288603))

@vl3 Job [#511](https://github.com/zold-io/zold/issues/511) is already on hold

**Comment by 0pdd** [comment]
The puzzle `507-040930f5` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vl3[/z](https://www.0crat.com/u/vl3), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#511](https://github.com/zold-io/zold/issues/511) is now out of scope

**Comment by ypshenychka** [comment]
@vl3 According to our [QA rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues

Please add link to issue in corresponding commits.

**Comment by ypshenychka** [comment]
@vl3 ping

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @vl3[/z](https://www.0crat.com/u/vl3)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
