### ISSUE TITLE
score is not growing up in some nodes

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#513]
Let's investigate and fix

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#514](https://github.com/zold-io/zold/issues/514) is still not solved.

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.5`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#513` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#514](https://github.com/zold-io/zold/issues/514) is solved here.
