### ISSUE TITLE
front.rb:430-432: This method is temporarily disabled...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/zold#514]
The puzzle `513-3d9ea123` from #513 has to be resolved: 

https://github.com/zold-io/zold/blob/4938e9b0612d924793300fa23a4834fcfd683461/lib/zold/node/front.rb#L430-L432

The puzzle was created by Yegor Bugayenko on 31-Oct-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#514](https://github.com/zold-io/zold/issues/514) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#514](https://github.com/zold-io/zold/issues/514) assigned to @vl3[/z](https://www.0crat.com/u/vl3), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/f7d453ef-bd55-412d-9684-c438d5e3ee5d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@vl3[/z](https://www.0crat.com/u/vl3) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@vl3 I would suggest to introduce a new method `Wallets.count` and implement it differently in `Wallets` and `TreeWallets`. In `Wallets` it will just count files in a directory, while in `TreeWallets` it should use `find . -name "*.z* | wc -l`

**Comment by vl3** [comment]
@0crat wait
PR submitted, waiting for review

**Comment by 0crat** [comment]
> @0crat wait PR submitted, waiting for review ([here](https://github.com/zold-io/zold/issues/514#issuecomment-445085777))

@vl3 The impediment for [#514](https://github.com/zold-io/zold/issues/514) was registered successfully by @vl3[/z](https://www.0crat.com/u/vl3)

**Comment by yegor256** [comment]
@vl3 I believe you forgot to remove the `todo` puzzle from the source code

**Comment by 0pdd** [comment]
The puzzle `513-3d9ea123` has disappeared from the source code, that's why I closed this issue.

**Comment by yegor256** [comment]
@vl3 I did it already in b04b9b3 You should have created a new PR, yes.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vl3[/z](https://www.0crat.com/u/vl3), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#514](https://github.com/zold-io/zold/issues/514) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vl3[/z](https://www.0crat.com/u/vl3)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
