### ISSUE TITLE
too many taxes are paid in one go

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#520]
We pay too much in each increment

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.9`

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.9`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#520` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
