### ISSUE TITLE
Failed to open TCP connection

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#521]
Take a look: https://travis-ci.org/zold-io/zold/jobs/449935947

For some reason:

```
ERROR: The node localhost:54864 is not responding, 599:Failed to open TCP connection to localhost:54864 (Connection refused - connect(2) for "localhost" port 54864) (RuntimeError)
/home/travis/build/zold-io/zold/lib/zold/commands/remote.rb:181:in `add'
/home/travis/build/zold-io/zold/lib/zold/commands/remote.rb:133:in `run'
/home/travis/build/zold-io/zold/bin/zold:194:in `<main>'
```

The node was started correctly. There is absolutely no functional reason for this failure. Why than?

Same here: https://travis-ci.org/zold-io/zold/jobs/449935949

**Comment by 0crat** [comment]
Job [#521](https://github.com/zold-io/zold/issues/521) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#521` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#521](https://github.com/zold-io/zold/issues/521) is now out of scope
