### ISSUE TITLE
Error with zold pay command

### ISSUE THREAD

**Issue by strogiyotec** [zold-io/zold#524]
I got the following error when I try to run zold pay command

```
zold pay 2b9c9766af8def83 99eb8855a001dea9 1.0 'almat' --trace
ERROR: no implicit conversion of nil into String (TypeError)
/var/lib/gems/2.3.0/gems/zold-0.15.0/lib/zold/commands/clean.rb:57:in `join'
/var/lib/gems/2.3.0/gems/zold-0.15.0/lib/zold/commands/clean.rb:57:in `block in run'
/var/lib/gems/2.3.0/gems/zold-0.15.0/lib/zold/commands/clean.rb:56:in `each'
/var/lib/gems/2.3.0/gems/zold-0.15.0/lib/zold/commands/clean.rb:56:in `run'
/var/lib/gems/2.3.0/gems/zold-0.15.0/lib/zold/commands/pull.rb:43:in `run'
/var/lib/gems/2.3.0/gems/zold-0.15.0/lib/zold/commands/invoice.rb:66:in `invoice'
/var/lib/gems/2.3.0/gems/zold-0.15.0/lib/zold/commands/invoice.rb:58:in `run'
/var/lib/gems/2.3.0/gems/zold-0.15.0/lib/zold/commands/pay.rb:76:in `run'
/var/lib/gems/2.3.0/gems/zold-0.15.0/bin/zold:195:in `<top (required)>'
/usr/local/bin/zold:23:in `load'
/usr/local/bin/zold:23:in `<main>'

```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@strogiyotec[/z](https://www.0crat.com/u/strogiyotec) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
The job [#524](https://github.com/zold-io/zold/issues/524) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/8f03fe68-2776-4811-ab3a-6cda3d202357); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#524` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @strogiyotec[/z](https://www.0crat.com/u/strogiyotec)

**Comment by yegor256** [comment]
@strogiyotec This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
The job [#524](https://github.com/zold-io/zold/issues/524) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
