### ISSUE TITLE
we don't kill processes on reboot

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#526]
Farming processes are not killed on reboot, let's fix.

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.12`

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#526](https://github.com/zold-io/zold/issues/526) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
