### ISSUE TITLE
A node is not been ever able to get into the list of remotes

### ISSUE THREAD

**Issue by denis-konovalyenko** [zold-io/zold#530]
[My node](http://91.211.13.180:4096) has not been ever able to get either into [the list of remotes](https://wts.zold.io/remotes) or to appear on [the health page](http://www.zold.io/health.html) since it was started 2-3 days ago for the first time.

I am wondering whether this is an abnormal situation or there is something I am not aware of?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by denis-konovalyenko** [comment]
@yegor256, for some reasons (I am not aware of what that might be) the node has been being shown on the health page for 2 days. Closing the ticket for now.
