### ISSUE TITLE
--threads for PUSH and FETCH

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#537]
Let's make it possible to configure the amount of threads to use in PUSH and FETCH, when many wallets are provided in the command line. Maybe we can use https://github.com/junegunn/parallelize

**Comment by 0crat** [comment]
Job [#537](https://github.com/zold-io/zold/issues/537) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @emilianodellacasa

**Comment by 0crat** [comment]
> @0crat assign @emilianodellacasa  ([here](https://github.com/zold-io/zold/issues/537#issuecomment-439368049))

@yegor256 The job [#537](https://github.com/zold-io/zold/issues/537) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/e0f4229d-15db-4ca9-bb42-cf4bd149c1a0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by emilianodellacasa** [comment]
@0crat wait - PR submitted, waiting for review

**Comment by 0crat** [comment]
> @0crat wait - PR submitted, waiting for review ([here](https://github.com/zold-io/zold/issues/537#issuecomment-441294663))

@emilianodellacasa The impediment for [#537](https://github.com/zold-io/zold/issues/537) was registered successfully by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by emilianodellacasa** [comment]
@yegor256 PR #569 has been merged, please close this issue

**Comment by yegor256** [comment]
@emilianodellacasa thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#537](https://github.com/zold-io/zold/issues/537) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/zold-io/zold/issues/537#issuecomment-443680163))

@ypshenychka There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@0fcab520-2251-43c3-ae56-6631ec564b80, thread: AsyncProc-5
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath 'text()' not found in '<param name="payment_id"/>': Index (0) is out of bounds (size=0)
```

[0.38.5](https://github.com/zerocracy/farm): CID: [b7a00e2b-ed59-483a-af13-f84a4b65e329](https://www.0crat.com/footprint/CAZPZR9FS/b7a00e2b-ed59-483a-af13-f84a4b65e329), Type: "Pay cash"

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
