### ISSUE TITLE
avoid duplicate farmer processes

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#541]
Let's avoid them

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.20`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.20`

**Comment by 0crat** [comment]
Job was finished in 10 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#541](https://github.com/zold-io/zold/issues/541) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
