### ISSUE TITLE
memory leakage?

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#542]
Nodes are consuming too much memory

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.21`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.21`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#542` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.21`

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.21`
