### ISSUE TITLE
Install the New Relic Ruby agent

### ISSUE THREAD

**Issue by SergeyKutsko** [zold-io/zold#545]
In order to have better information about ruby application it is beter to install tools to make it easier.

Good start https://docs.newrelic.com/docs/agents/ruby-agent/installation/install-new-relic-ruby-agent

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@SergeyKutsko we have no control over our nodes, can't install anything there. We can only add something to our Ruby code. Any ideas?

**Comment by 0crat** [comment]
This job is not in scope

**Comment by SergeyKutsko** [comment]
@yegor256 gem 'newrelic_rpm' is piece of ruby code.

**Comment by yegor256** [comment]
@SergeyKutsko yes, but we will need to install NewRelic agent to the system
