### ISSUE TITLE
add network name into the score

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#55]
The score has to include the name of the network.

Also the version. Let's make sure we reject if versions don't match.

**Comment by 0crat** [comment]
Job [#55](https://github.com/zold-io/zold/issues/55) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#55](https://github.com/zold-io/zold/issues/55), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by SergeyKutsko** [comment]
@yegor256 Now this task realted to another repo as you extracted Score to separate gem, right?

**Comment by SergeyKutsko** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait  ([here](https://github.com/zold-io/zold/issues/55#issuecomment-437571054))

@SergeyKutsko The impediment for [#55](https://github.com/zold-io/zold/issues/55) was registered successfully by @sergeykutsko[/z](https://www.0crat.com/u/sergeykutsko)

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@SergeyKutsko correct

**Comment by 0crat** [comment]
>  @0crat refuse ([here](https://github.com/zold-io/zold/issues/55#issuecomment-441345581))

@yegor256 The user @sergeykutsko[/z](https://www.0crat.com/u/sergeykutsko) resigned from [#55](https://github.com/zold-io/zold/issues/55), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#55` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#55](https://github.com/zold-io/zold/issues/55) is now out of scope
