### ISSUE TITLE
Errno::ENOTEMPTY: Directory not empty @ dir_s_rmdir

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#553]
```
TestZold#test_redeploy_on_upgrade:
Errno::ENOTEMPTY: Directory not empty @ dir_s_rmdir - /tmp/d20181115-24050-gfvo3u
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:1337:in `rmdir'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:1337:in `block in remove_dir1'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:1348:in `platform_support'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:1336:in `remove_dir1'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:1329:in `remove'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:691:in `block in remove_entry'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:1386:in `ensure in postorder_traverse'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:1386:in `postorder_traverse'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:689:in `remove_entry'
    /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/tmpdir.rb:95:in `mktmpdir'
    /home/r/repo/test/test_zold.rb:40:in `block (2 levels) in <class:TestZold>'
```

Happens sometimes, no always.

**Comment by 0crat** [comment]
Job [#553](https://github.com/zold-io/zold/issues/553) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @emilianodellacasa

**Comment by 0crat** [comment]
> @0crat assign @emilianodellacasa  ([here](https://github.com/zold-io/zold/issues/553#issuecomment-439366551))

@yegor256 The job [#553](https://github.com/zold-io/zold/issues/553) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/e71b8ed5-fb12-4b51-b449-8125a05cb193); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by emilianodellacasa** [comment]
@yegor256 I updated my code with the last commits and I cannot reproduce this anymore, you can close this issue

**Comment by emilianodellacasa** [comment]
@yegor256 you are right, I will check it

**Comment by emilianodellacasa** [comment]
@yegor256 I created PR #564

**Comment by emilianodellacasa** [comment]
@0crat wait - pull request created, waiting for approval or rejection

**Comment by 0crat** [comment]
> @0crat wait - pull request created, waiting for approval or rejection ([here](https://github.com/zold-io/zold/issues/553#issuecomment-440956178))

@emilianodellacasa The impediment for [#553](https://github.com/zold-io/zold/issues/553) was registered successfully by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by emilianodellacasa** [comment]
@yegor256 PR has been merged, please close this

**Comment by emilianodellacasa** [comment]
@dapi I tried with current master and couldn't reporoduce it, try updating and if you still see this error please open another issue

**Comment by dapi** [comment]
@emilianodellacasa well, today I can't reproduce it too..

**Comment by yegor256** [comment]
@emilianodellacasa thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#553](https://github.com/zold-io/zold/issues/553) is now out of scope

**Comment by ypshenychka** [comment]
@dapi According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](https://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to

Please correct your [message](https://github.com/zold-io/zold/issues/553#issuecomment-441382490)  by indicating an addressee in the beginning.

**Comment by dapi** [comment]
@emilianodellacasa no reproducing with current master

**Comment by ypshenychka** [comment]
@dapi Please respond to my above remark and make appropriate correction.

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
