### ISSUE TITLE
Farmers::Fork

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#554]
Let's create a new implementation of a farmer, which will use [Ruby fork](https://ruby-doc.org/core-2.1.2/Process.html#method-c-fork).

**Comment by yegor256** [comment]
@emilianodellacasa interested?

**Comment by yegor256** [comment]
@0crat assign @emilianodellacasa

**Comment by 0crat** [comment]
> @0crat assign @emilianodellacasa  ([here](https://github.com/zold-io/zold/issues/554#issuecomment-439362909))

@yegor256 The job [#554](https://github.com/zold-io/zold/issues/554) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/f338347c-8b43-4244-a7a9-c4c7d97d0dce); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by emilianodellacasa** [comment]
@yegor256 Created PR #567

**Comment by emilianodellacasa** [comment]
@0crat wait - PR submitted, waiting for review

**Comment by 0crat** [comment]
> @0crat wait - PR submitted, waiting for review ([here](https://github.com/zold-io/zold/issues/554#issuecomment-441294703))

@emilianodellacasa The impediment for [#554](https://github.com/zold-io/zold/issues/554) was registered successfully by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by emilianodellacasa** [comment]
@yegor256 PR has been merged, please close this issue

**Comment by yegor256** [comment]
@emilianodellacasa thanks!

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
