### ISSUE TITLE
memory leakage (continued)

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#558]
We tried to fix it in #548 but failed.

We are still leaking memory. Our nodes are pretty small and should be able to run with a very small memory footprint, like 30-40Mb, not more. However, they consume 2Gb+.

**Comment by yegor256** [comment]
@0crat assign @emilianodellacasa

**Comment by 0crat** [comment]
> @0crat assign @emilianodellacasa  ([here](https://github.com/zold-io/zold/issues/558#issuecomment-439371542))

@yegor256 The job [#558](https://github.com/zold-io/zold/issues/558) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/e6a11ead-8628-41dd-b23b-ac4a472683c2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by emilianodellacasa** [comment]
@yegor256 by analyzing the working node, we had the following output 

retained memory by gem
-----------------------------------
  22064071  open3
  16548545  zold-0.16.27
    310503  rubygems
    168770  mustermann-1.0.2
    103066  uri
     96972  sinatra-2.0.4
     72303  resolv
     55030  rack-2.0.4
     49112  erb
     44737  eventmachine-1.2.7
     35789  optparse
     24744  thin-1.7.2
     19872  tilt-2.0.8
     18816  delegate
     17448  daemons-1.2.6
     13869  time
     13536  slop-4.6.2
     12560  rack-protection-2.0.4
     11152  forwardable
      6712  zold-score-0.2.2

meaning that the vast majority of memory is retained by open3 gem (and by us, but that is for sure).

Issue #554 should solve this problem, so I guess you can close this one

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@emilianodellacasa thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#558](https://github.com/zold-io/zold/issues/558) is now out of scope

**Comment by ypshenychka** [comment]
@emilianodellacasa Since there was no solution provided, I can't evaluate this ticket as 'good'. However you spent some time on investigation, so I guess I can mark it as 'acceptable'. Agree?

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
