### ISSUE TITLE
show summary trust level at the end of FETCH

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#56]
Let's show at the end of FETCH what was the total score.

**Comment by 0crat** [comment]
Job [#56](https://github.com/zold-io/zold/issues/56) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Job [#56](https://github.com/zold-io/zold/issues/56) is not in the agenda of @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job [#56](https://github.com/zold-io/zold/issues/56) is not in the agenda of @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), can't inspect

**Comment by 0crat** [comment]
The job [#56](https://github.com/zold-io/zold/issues/56) is now out of scope

**Comment by ypshenychka** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zold-io/zold/issues/56#issuecomment-439364144))

@ypshenychka This is what I know about this job in [CAZPZR9FS](https://www.0crat.com/p/CAZPZR9FS), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#56](https://github.com/zold-io/zold/issues/56) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 2days
  * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CAZPZR9FS?q=%7Bjob%3A%27gh%3Azold-io%2Fzold%2356%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@paulodamaso ping

**Comment by paulodamaso** [comment]
@ypshenychka you are right, I did not even touched this issue

**Comment by ypshenychka** [comment]
@paulodamaso thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
