### ISSUE TITLE
Add pragma to each file: frozen_string_literal: true. To reduce memory usage. 

### ISSUE THREAD

**Issue by SergeyKutsko** [zold-io/zold#561]
frozen_string_literal: true

Follow guide: https://samsaffron.com/archive/2018/02/16/reducing-string-duplication-in-ruby

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@SergeyKutsko we have them already

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#561` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
