### ISSUE TITLE
let's show availability at REMOTE command

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#57]
Let's show availability for each node

**Comment by 0crat** [comment]
Job [#57](https://github.com/zold-io/zold/issues/57) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zold-io/zold/issues/57#issuecomment-401928845))

@yegor256 This is what I know about this job in [CAZPZR9FS](https://www.0crat.com/p/CAZPZR9FS), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#57](https://github.com/zold-io/zold/issues/57) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) for [5days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CAZPZR9FS?q=%7Bjob%3A%27gh%3Azold-io%2Fzold%2357%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by yegor256** [comment]
@emilianodellacasa this is your job apparently...

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by emilianodellacasa** [comment]
@yegor256 I have been assigned like 20 issues like that, if you see there is no comment about first assignment.

I have already created an issue for it https://github.com/zerocracy/farm/issues/1312 hope it will be taken care of soon

**Comment by yegor256** [comment]
@emilianodellacasa yes, this seems to be a bug on our side, sorry.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#57](https://github.com/zold-io/zold/issues/57), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
The score of @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) -480 is too low and will be reset: +480 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/zold/issues/57#issuecomment-437852021))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#57](https://github.com/zold-io/zold/issues/57), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The job [#57](https://github.com/zold-io/zold/issues/57) assigned to @tsuhachev[/z](https://www.0crat.com/u/tsuhachev), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/ea1745a6-3ba5-4f3e-bd94-790a1d43ba85); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@tsuhachev I fixed it already, don't bother

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/zold/issues/57#issuecomment-438579687))

@yegor256 The user @tsuhachev[/z](https://www.0crat.com/u/tsuhachev) resigned from [#57](https://github.com/zold-io/zold/issues/57), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#57` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#57](https://github.com/zold-io/zold/issues/57) is now out of scope
