### ISSUE TITLE
Appveyor build is broken: libcurl is not found

### ISSUE THREAD

**Issue by dapi** [zold-io/zold#574]
https://ci.appveyor.com/project/yegor256/zold-jhx6b/builds/20528112/job/y8x1po291wrq3d4v

![screen shot 2018-11-26 at 17 14 37](https://user-images.githubusercontent.com/31139/49019352-c9f1e480-f19e-11e8-8f23-3e3d8658bf7a.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dapi[/z](https://www.0crat.com/u/dapi) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#574](https://github.com/zold-io/zold/issues/574) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @dapi[/z](https://www.0crat.com/u/dapi)

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#574` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#574](https://github.com/zold-io/zold/issues/574) is now out of scope
