### ISSUE TITLE
unique TAX transactions

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#58]
Let's make sure tax payments are unique. The node has to provide `/tax-bill` entry point, where any client can submit a request for the tax payment and the node has to reserve the score and return back the payment text.

**Comment by 0crat** [comment]
Job `gh:zerocracy/zold#58` is not assigned, can't get start time

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
