### ISSUE TITLE
Include operating system on / API

### ISSUE THREAD

**Issue by emilianodellacasa** [zold-io/zold#587]
For better debugging and statistics, we should include the operating system on which the node is running on the main API "/", and we should also show it in the health page.

**Comment by yegor256** [comment]
@emilianodellacasa I believe we do this already: https://github.com/zold-io/zold/blob/master/lib/zold/node/front.rb#L203 What else do you think we should add?

**Comment by emilianodellacasa** [comment]
@yegor256 You are right, sorry for that

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#587` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
