### ISSUE TITLE
'zold remote reset' does not work.

### ISSUE THREAD

**Issue by DronMDF** [zold-io/zold#588]
```sh
$ zold remote reset
wrong number of arguments (given 0, expected 1) (ArgumentError)
$ zold remote update
The list of remotes is empty, run 'zold remote reset'!
$ zold --version
0.17.1
```
I tried to delete the .zoldata directory, it did not affect the situation.

tracing:
```sh
$ zold --trace remote reset
wrong number of arguments (given 0, expected 1) (ArgumentError)
ArgumentError: wrong number of arguments (given 0, expected 1)
	/var/lib/gems/2.5.0/gems/zold-0.17.1/lib/zold/commands/remote.rb:178:in `defaults'
	/var/lib/gems/2.5.0/gems/zold-0.17.1/lib/zold/commands/remote.rb:175:in `reset'
	/var/lib/gems/2.5.0/gems/zold-0.17.1/lib/zold/commands/remote.rb:138:in `run'
	/var/lib/gems/2.5.0/gems/zold-0.17.1/lib/zold/commands/thread_badge.rb:41:in `run'
	/var/lib/gems/2.5.0/gems/zold-0.17.1/bin/zold:210:in `block in <top (required)>'
	/var/lib/gems/2.5.0/gems/zold-0.17.1/bin/zold:274:in `<top (required)>'
	/usr/local/bin/zold:23:in `load'
	/usr/local/bin/zold:23:in `<main>'
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dronmdf[/z](https://www.0crat.com/u/dronmdf) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by emilianodellacasa** [comment]
@DronMDF I could reproduce it with version 0.17.1

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @dronmdf[/z](https://www.0crat.com/u/dronmdf)

**Comment by 0crat** [comment]
The job [#588](https://github.com/zold-io/zold/issues/588) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/f9a7704f-03fe-40c7-91e5-52c48abbf743); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#588](https://github.com/zold-io/zold/issues/588) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
