### ISSUE TITLE
remove Gemfile.lock from .gitignore and add it to repo

### ISSUE THREAD

**Issue by dapi** [zold-io/zold#594]
All developers and CI must have identical environment

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dapi[/z](https://www.0crat.com/u/dapi) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by dapi** [comment]
here `zold.gemspecs` versions must be specified in soft manner (equal or more)

**Comment by dapi** [comment]
Hm.. May be I’m wrong. Ignoring `Gemfile.lock` in gems is popular solution: https://github.com/rubocop-hq/rubocop/blob/master/.gitignore

**Comment by dapi** [comment]
That is OK. close issue

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#594` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
