### ISSUE TITLE
Turn off appvyour build status publication in commits/PR and remove badge from README

### ISSUE THREAD

**Issue by dapi** [zold-io/zold#595]
Deny appveyor to publish his build status until it be totally fixed and windows supported.

This if why:

![screen shot 2018-11-30 at 11 47 14](https://user-images.githubusercontent.com/31139/49278390-b2b04100-f495-11e8-93c5-cb3a26ea2a31.png)

We can’t find broken commit and understand with PR is really breaks it.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dapi[/z](https://www.0crat.com/u/dapi) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@dapi we don't want to completely reject Windows. We need to find a way to build Zold for Windows. That's why Appveyor will stay.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#595` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
