### ISSUE TITLE
Use attribute getter/setters instead for direct instance variable access

### ISSUE THREAD

**Issue by dapi** [zold-io/zold#598]
This method:

```ruby
def intitialize(param:)
  @param = param
end

def perform
  do_some_interesting param
end

private

attr_reader :param
```

is preferable then direct access: `@param`

Reasons:

1. Catching typo mistake in early stages (if you wire `@parm` you will get `nil`, but in you write `parm` you will get `NameError`.
2. You describe class attributes in humanized way. Probably attributes will be public, or it have writes
3. Easy to maintain and add memoization, overwrite attributes behaviour in inherited objects and so on.
4. Deny to youself to accidentally rewrite attribute's value.
5. code looks better in IDE (instance variables are always emits to do warning for developers

**Comment by dapi** [comment]
In my experience - direct access to instance variables in ruby is much more evil than attributes accessor.

That is why I recommend to use attribute accessors in such cases.

**Comment by yegor256** [comment]
@dapi won't do that, sorry. We are against getters/setters.
