### ISSUE TITLE
One class - one human readable procedure (style guides and refactoring discus)

### ISSUE THREAD

**Issue by dapi** [zold-io/zold#599]
Guys, let's discuss some refactoring methods. 

Now: https://github.com/dapi/zold/blob/feature/refactor_example/lib/zold/commands/fetch.rb
Was: https://github.com/zold-io/zold/blob/master/lib/zold/commands/fetch.rb

diff: https://github.com/dapi/zold/pull/10

1. Use constants for constants ;)
2. Inherit all commands from base class.
3. Use attribute accessor or (better) use `virtus` (or similar Plain Old Ruby implementation gem's) to describe value objects and service class attributes in humanized and self validates manner.
4. Class must contains description in the head.
5. Class must describe only his self logic and human readable manner. This logic is what described in class header.

The developer looks in to class it must see main logic, and that deeps into if he needs it.

Here are still many issues in example, but I think it shows main approach to code.

Issues that I see:

1. We don't see from code where and how saved best wallet
2. Probably to separate class to  Command (procedures which are used from code) and CommanLine - command line (arguments) descriptions class.
3. Use benchmark where you want to menchmark.
4. Use `logger` instead of `log` because it's typically for ruby application and contains 'Logger' object.

thanks

Glad to see you words about it )

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dapi[/z](https://www.0crat.com/u/dapi) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@dapi you know that inheritance is evil, right? https://www.yegor256.com/2016/09/13/inheritance-is-procedural.html

**Comment by dapi** [comment]
@yegor256 Yes. I now pros and cons of inheritance and know when and how to not use it. 

There are 3 steps of inheritance usage (like any other rules):

1. Inheritance everywhere.
2. Inheritance nowhere.
3. Inheritance somewhere.

In any case in my example inheritance is not need to get all pros of suggested code organisations and styles. 

And yes, often, inheritance is better way then `prepend`. `prepend` typically used to get some monkey patch alternatives for external gems. And inheritance often better than have 20-lines of similar `extends` that is used in most other classes and unpredictable overrides methods of each other

I prefer to mark (if it possible) classes with similar interface as inherited from on base class. Even the base class is empty. Also to have base class is useful to get example of class usage and inheritance rules. Thinking about it like about interface.

So I does not accept/believe in evilness of any technology or methodology.

I prefer to know how technology helps to get goals in short way and its side effects.

**Comment by yegor256** [comment]
@dapi the code in your example looks not clear for me. For example, I don't understand who is calling `command_line_options`, when and why? Also, it's an immutable class? I prefer to think about objects as something that is initialized via constructors and then called via methods. Public methods. Your class doesn't have a single public method. How am I supposed to understand where are the entry points?

So, the bottom line -- no inheritance in this project please :) It's for losers.

**Comment by yegor256** [comment]
@dapi This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#599` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
