### ISSUE TITLE
the Farm should ignore the score if it's not strong enough

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#601]
Let's filter them out

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.4`

**Comment by 0crat** [comment]
The job [#601](https://github.com/zold-io/zold/issues/601) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
