### ISSUE TITLE
NoDupEntrance should keep the history

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#602]
Let's make it smarter

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.5`

**Comment by 0crat** [comment]
Job was finished in 8 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#602](https://github.com/zold-io/zold/issues/602) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
