### ISSUE TITLE
Need add nginx to serve http and https same port. 

### ISSUE THREAD

**Issue by SergeyKutsko** [zold-io/zold#603]
https://github.com/zold-io/zold/issues/140

**Comment by yegor256** [comment]
@SergeyKutsko use PDD if you need to break your task into smaller increments: https://www.yegor256.com/2010/03/04/pdd.html

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#603` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
