### ISSUE TITLE
Why do we reduce score to 16 before publicity it in headers?

### ISSUE THREAD

**Issue by dapi** [zold-io/zold#604]
What for do we have reducing to 16 here?

https://github.com/zold-io/zold/blob/master/lib/zold/node/front.rb#L126

This line  `headers[Http::SCORE_HEADER] = score.reduced(16).to_s` is added by this issue - https://github.com/zold-io/zold/issues/115 (auto detection of new nodes doesn't work) 

and this commit - https://github.com/zold-io/zold/commit/53f5da36ddc25164f08b064c58d49954e2f1f58b#diff-fbd0fd8df6537872afc530c2c969b414R81

**Comment by 0crat** [comment]
@dapi[/z](https://www.0crat.com/u/dapi) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#604` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @dapi[/z](https://www.0crat.com/u/dapi)

**Comment by yegor256** [comment]
@dapi see 7010661 Did I answer your question?

**Comment by dapi** [comment]
It explains. But why 16? Why not 24 or not 8? Is here some mathematic basis or HTTP header length limitation?

**Comment by dapi** [comment]
Some times I met reducing to 4. Why we not reduce to 4 here?

**Comment by yegor256** [comment]
@dapi right, see: ed80062

**Comment by yegor256** [comment]
@dapi and this: f069736

**Comment by yegor256** [comment]
@dapi  This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!
