### ISSUE TITLE
What goals of this project?

### ISSUE THREAD

**Issue by dapi** [zold-io/zold#605]

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dapi[/z](https://www.0crat.com/u/dapi) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@dapi check the white paper: http://papers.zold.io/wp.pdf

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#605` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
