### ISSUE TITLE
Can't get non-exclusive access to the file .zoldata/remotes because of the lock 

### ISSUE THREAD

**Issue by denis-konovalyenko** [zold-io/zold#608]
```
[zold@dmz1 ~]$ zold -v
0.17.5
```
```
[zold@dmz1 ~]$ zold pull e560c4fb95684c6d
Traceback (most recent call last):
	10: from /home/zold/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
	 9: from /home/zold/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
	 8: from /home/zold/.rvm/gems/ruby-2.5.3/bin/zold:23:in `<main>'
	 7: from /home/zold/.rvm/gems/ruby-2.5.3/bin/zold:23:in `load'
	 6: from /home/zold/.rvm/gems/ruby-2.5.3/gems/zold-0.17.5/bin/zold:177:in `<top (required)>'
	 5: from /usr/home/zold/.rvm/gems/ruby-2.5.3/gems/zold-0.17.5/lib/zold/remotes.rb:131:in `all'
	 4: from /usr/home/zold/.rvm/gems/ruby-2.5.3/gems/futex-0.4.3/lib/futex.rb:73:in `open'
	 3: from /usr/home/zold/.rvm/gems/ruby-2.5.3/gems/futex-0.4.3/lib/futex.rb:73:in `open'
	 2: from /usr/home/zold/.rvm/gems/ruby-2.5.3/gems/futex-0.4.3/lib/futex.rb:75:in `block in open'
	 1: from /usr/home/zold/.rvm/gems/ruby-2.5.3/gems/futex-0.4.3/lib/futex.rb:75:in `loop'
/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/futex-0.4.3/lib/futex.rb:82:in `block (2 levels) in open': #9566-sh/main e/zold/.rvm/gems/ruby-2.5.3/gems/zold-0.17.5/lib/zold/remotes.rb:131:in `all'
	 4: from /usr/home/zold/.rvm/gems/ruby-2.5.3/gems/futex-0.4.3/lib/futex.rb:73:in `open'
	 3: from /usr/home/zold/.rvm/gems/ruby-2.5.3/gems/futex-0.4.3/lib/futex.rb:73:in `open'
	 2: from /usr/home/zold/.rvm/gems/ruby-2.5.3/gems/futex-0.4.3/lib/futex.rb:75:in `block in open'
	 1: from /usr/home/zold/.rvm/gems/ruby-2.5.3/gems/futex-0.4.3/lib/futex.rb:75:in `loop'
/usr/home/zold/.rvm/gems/ruby-2.5.3/gems/futex-0.4.3/lib/futex.rb:82:in `block (2 levels) in open': #9566-sh/main can't get non-exclusive access to the file /usr/home/zold/.zoldata/remotes because of the lock at /usr/home/zold/.zoldata/remotes.lock, after 16011ms of waiting: #7627-ex/Zold::Routines::Reconnect-0:Remote (RuntimeError)
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@denis-konovalyenko it seems that you are sharing the same directory with the running node:

```
#9566-sh/main can't get non-exclusive access to the file 
/usr/home/zold/.zoldata/remotes because of the lock at 
/usr/home/zold/.zoldata/remotes.lock, after 16011ms of waiting: 
#7627-ex/Zold::Routines::Reconnect-0:Remote
```

The process 9566 tries to lock the file, while the process 7627 is using it now.

**Comment by denis-konovalyenko** [comment]
@yegor256 , thank you for the clarification!

Indeed, the pull was issuing from the same directory where the node was running at the same time, however, that had not happened before (lucky node and me). Would not it be better if this limitation is being documented somewhere? E.g.: "please be aware that a client operation might cause the denial of it if the client is sharing the same directory with the running node", or "do not run the client and the server from the same directory".

**Comment by pavulon18** [comment]
so how should I go about fixing this on my machine, since I am getting the same (or similar) error message?

**Comment by denis-konovalyenko** [comment]
@pavulon18 , the workaround would be to launch the server and the client processes from different directories.

**Comment by yegor256** [comment]
@denis-konovalyenko This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#608` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
