### ISSUE TITLE
more accurate wallet age calculation

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#61]
Let's calculate wallet "age" as a difference between the oldest transaction and the most recent one (not the current time, as it's done now).

**Comment by 0crat** [comment]
Job [#61](https://github.com/zerocracy/zold/issues/61) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#61](https://github.com/zerocracy/zold/issues/61); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job [#61](https://github.com/zold-io/zold/issues/61) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @oltdaniel

**Comment by 0crat** [comment]
> @0crat assign @oltdaniel ([here](https://github.com/zold-io/zold/issues/61#issuecomment-394475882))

@yegor256 The job [#61](https://github.com/zold-io/zold/issues/61) assigned to @oltdaniel[/z](https://www.0crat.com/u/oltdaniel), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1551966516); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by oltdaniel** [comment]
@yegor256 What if the wallet has a single transaction? Still no age

**Comment by oltdaniel** [comment]
@yegor256 Using the new formula, the whole system is broken, since it returns 0 when a single transaction is set. Could you help calculating the numbers for the test cases?

**Comment by 0crat** [comment]
@oltdaniel[/z](https://www.0crat.com/u/oltdaniel) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The job [#61](https://github.com/zold-io/zold/issues/61) assigned to @sandiks[/z](https://www.0crat.com/u/sandiks), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1660677698); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by sandiks** [comment]
i changed method
 def age
      list = txns
      list.empty? ? 0 : (Time.now - list.min_by(&:date).date) / 60
    end
with line
list.empty? ? 0 : (list.max_by(&:date).date - list.min_by(&:date).date) / 60

is it good decision?
This method doesn't have a test method, 
I need to add a test method?

**Comment by yegor256** [comment]
@oltdaniel everything has to be tested, of course. As for the change, I doubt it will work, but let's try

**Comment by oltdaniel** [comment]
@yegor256 Every test case for the wallet or amount calculation, fails with the new formula and format in hours instead of seconds.

**Comment by 0crat** [comment]
@sandiks[/z](https://www.0crat.com/u/sandiks) this job was assigned to you 7days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @sandiks[/z](https://www.0crat.com/u/sandiks) resigned from [#61](https://github.com/zold-io/zold/issues/61), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @sandiks[/z](https://www.0crat.com/u/sandiks)

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#61](https://github.com/zold-io/zold/issues/61), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
The job [#61](https://github.com/zold-io/zold/issues/61) assigned to @jedediah[/z](https://www.0crat.com/u/jedediah), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1920668672); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@jedediah[/z](https://www.0crat.com/u/jedediah) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@yegor256 this seems to be fixed

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @jedediah[/z](https://www.0crat.com/u/jedediah), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#61](https://github.com/zold-io/zold/issues/61) is now out of scope

**Comment by ypshenychka** [comment]
@jedediah ping

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
