### ISSUE TITLE
Remotes.add() with a reason

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#613]
Let's add a `reason` to `Remotes.add()` and let's store it in the list of remotes (in the CSV). This will help us understand why certain remote got into the list and when.

Look what we have now (port 16534 is a total strange):

<img width="404" alt="screen shot 2018-12-04 at 10 49 20 am" src="https://user-images.githubusercontent.com/526301/49426689-56f5f880-f7b2-11e8-8352-1ae7e453e9ec.png">

**Comment by 0crat** [comment]
Job [#613](https://github.com/zold-io/zold/issues/613) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.8`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#613` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#613](https://github.com/zold-io/zold/issues/613) is now out of scope
