### ISSUE TITLE
Choice between Zold::Score#to_s and to_text

### ISSUE THREAD

**Issue by dapi** [zold-io/zold#616]
Some times used to_s, some times used to_text. Which one is right and better?

```
lib/zold/http.rb:      headers[Http::SCORE_HEADER] = @score.reduced(4).to_text if @score.valid? && !@score.expired? && @score.value > 3
lib/zold/node/front.rb:      headers[Http::SCORE_HEADER] = score.reduced(Front::MIN_SCORE).to_s
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dapi[/z](https://www.0crat.com/u/dapi) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@dapi fixed, we are using `to_s` only now.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#616` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
