### ISSUE TITLE
How to force remote nodes to push me all their wallets?

### ISSUE THREAD

**Issue by dapi** [zold-io/zold#618]
Is there any described way?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dapi[/z](https://www.0crat.com/u/dapi) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@0crat assign @emilianodellacasa

**Comment by yegor256** [comment]
@emilianodellacasa let's introduce a new HTTP entry point called `/wallets`. It should return names of all wallets in plain text, separated by `\n`. You just do `@wallets.all`.

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @dapi[/z](https://www.0crat.com/u/dapi)

**Comment by emilianodellacasa** [comment]
@0crat wait - PR #657 created, waiting to be merged

**Comment by 0crat** [comment]
> @0crat wait - PR #657 created, waiting to be merged ([here](https://github.com/zold-io/zold/issues/618#issuecomment-450348370))

@emilianodellacasa The impediment for [#618](https://github.com/zold-io/zold/issues/618) was registered successfully by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by emilianodellacasa** [comment]
@yegor256 PR has been merged, please close this issue

**Comment by yegor256** [comment]
@emilianodellacasa it's not mine

**Comment by emilianodellacasa** [comment]
@yegor256 you are right, sorry

**Comment by emilianodellacasa** [comment]
@dapi please close this issue, PR has been merged

**Comment by dapi** [comment]
👍

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#618](https://github.com/zold-io/zold/issues/618) is now out of scope

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zold-io/zold/issues/618#issuecomment-451913636))

@g4s8 This is what I know about this job in [CAZPZR9FS](https://www.0crat.com/p/CAZPZR9FS), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#618](https://github.com/zold-io/zold/issues/618) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CAZPZR9FS?q=%7Bjob%3A%27gh%3Azold-io%2Fzold%23618%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)
