### ISSUE TITLE
score 8

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#619]
See https://github.com/zold-io/zold-score/issues/24

Let's use the new lib.

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.0`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#619` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
