### ISSUE TITLE
X-Zold-Accept-Protocols support

### ISSUE THREAD

**Issue by dapi** [zold-io/zold#625]
I think will be better to write full client name to version, like a: `X-Zold-Version: Zold 0.1.2` and `X-Zold-Version: Zoldy 2.3.4`

And, it is important, available node to support different protocols: `X-Zold-Accept-Protocols: 2,3,SOME-1` etc

**Comment by yegor256** [comment]
@dapi we will introduce a new header `X-Zold-Repo`. For the default one it will be `zold-io/zold`. For your own implementation provide your own.

**Comment by 0crat** [comment]
The job [#625](https://github.com/zold-io/zold/issues/625) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/2b5d1e5e-cc75-4283-bef0-462b7a05c440); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#625` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @dapi[/z](https://www.0crat.com/u/dapi)

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.6`

**Comment by yegor256** [comment]
@dapi done, thanks

**Comment by 0crat** [comment]
Job was finished in 3 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#625](https://github.com/zold-io/zold/issues/625) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
