### ISSUE TITLE
Gc fails when file not found

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#627]
```
Routine Zold::Routines::Gc #1 failed in 1m
RuntimeError: Wallet file '/root/4/4/8/b/448b451bc62e8e16.z' is absent
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.4/lib/zold/txns.rb:41:in `fetch'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.4/lib/zold/txns.rb:64:in `fetch'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.4/lib/zold/wallet.rb:204:in `txns'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.4/lib/zold/commands/routines/gc.rb:50:in `block (2 levels) in exec'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.4/lib/zold/sync_wallets.rb:61:in `block (2 levels) in acq'
	/usr/local/rvm/gems/ruby-2.5.1/gems/futex-0.6.2/lib/futex.rb:101:in `block in open'
	/usr/local/rvm/gems/ruby-2.5.1/gems/futex-0.6.2/lib/futex.rb:75:in `open'
	/usr/local/rvm/gems/ruby-2.5.1/gems/futex-0.6.2/lib/futex.rb:75:in `open'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.4/lib/zold/sync_wallets.rb:60:in `block in acq'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.4/lib/zold/cached_wallets.rb:63:in `block in acq'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.4/lib/zold/tree_wallets.rb:64:in `acq'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.4/lib/zold/cached_wallets.rb:61:in `acq'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.4/lib/zold/sync_wallets.rb:59:in `acq'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.4/lib/zold/commands/routines/gc.rb:50:in `block in exec'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.4/lib/zold/commands/routines/gc.rb:48:in `each'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.4/lib/zold/commands/routines/gc.rb:48:in `exec'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.4/lib/zold/metronome.rb:73:in `block (3 levels) in start'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.4/lib/zold/metronome.rb:70:in `loop'
	/usr/local/rvm/gems/ruby-2.5.1/gems/zold-0.18.4/lib/zold/metronome.rb:70:in `block (2 levels) in start'
```

**Comment by 0crat** [comment]
The job [#627](https://github.com/zold-io/zold/issues/627) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/44e0a4ec-b5d3-4ebd-ad0a-4dfa2ac73ea3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#627` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.5`

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#627](https://github.com/zold-io/zold/issues/627) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
