### ISSUE TITLE
BUG api rest of wts - negative balance check

### ISSUE THREAD

**Issue by blackout314** [zold-io/zold#630]
i have 0.256 zold
i sent a pay with rest api of 20 zold
i see my balance with negative zold -19,xx

**Comment by yegor256** [comment]
@blackout314 fixed in https://github.com/zold-io/wts.zold.io/commit/0ca2e23a6dd59a371f87428bded1d8b11b8b06d7

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#630` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
