### ISSUE TITLE
--shallow for the merge

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#642]
Let's make merge operation non-shallow by default.

**Comment by yegor256** [comment]
@rultor release, tag is `0.20.0`

**Comment by 0crat** [comment]
Job was finished in 10 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#642](https://github.com/zold-io/zold/issues/642) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
