### ISSUE TITLE
Let's update Copyright notice to 2019.

### ISSUE THREAD

**Issue by fabriciofx** [zold-io/zold#659]
Let's update Copyright notice to 2019.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@fabriciofx fixed in ef8001ae6b25ed1f9953a9baf9a7b2b98814f36f thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#659` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
