### ISSUE TITLE
No comments for bnf abbreviation 

### ISSUE THREAD

**Issue by strogiyotec** [zold-io/zold#660]
As I'm new in Zold project , I can't understand some abbreviation , I'm interesting in "bnf" word from constructor of "txn". As I see from code it's a wallet id 
```
def initialize(id, date, amount, prefix, bnf, details)
```
All other parameters are clear enough beside of bnf. What does this abbreiation mean ?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@strogiyotec[/z](https://www.0crat.com/u/strogiyotec) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@strogiyotec some documentation added in 7639377 thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#660` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
