### ISSUE TITLE
don't deploy to Heroku

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#662]
Let's stop that and kill b1.zold.io

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.2`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#662` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
