### ISSUE TITLE
Node starting but no web part available, doesn't show up on the list

### ISSUE THREAD

**Issue by YoMe2** [zold-io/zold#666]
http://prntscr.com/m6jsga

zold remote reset doesn't help

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@yome2[/z](https://www.0crat.com/u/yome2) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@YoMe2 it's fixed in de4c306 thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#666` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
