### ISSUE TITLE
Wrong command in ubuntu installation

### ISSUE THREAD

**Issue by ammaratef45** [zold-io/zold#667]
In section Ubuntu 16.04 the command `source /etc/profile.d/rvm.sh` didn't work with me,

Instead, I was able to run `source /home/ammar/.rvm/scripts/rvm`

I got it from the output of rvm installation as following

> * To start using RVM you need to run `source /home/ammar/.rvm/scripts/rvm`
    in all your open shell windows, in rare cases you need to reopen all shell windows.

Maybe you need to fix it or add a tip that the user should search for the right command in the output of previous command (just in case someone didn't notice or bother himself to read the commands output)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by ammaratef45** [comment]
@yegor256 
forgot the mention the file
https://github.com/zold-io/zold/blob/master/INSTALL.md

**Comment by yegor256** [comment]
@ammaratef45 I suspect that you were not running the script from `root` user, like the documentation suggests. That's why the command didn't work for you.

**Comment by ammaratef45** [comment]
@yegor256 yes that is right
why should I run sudo while I'm root? that confused me

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#667` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by yegor256** [comment]
@ammaratef45 you are not running as root, because of this message: `To start using RVM you need to run source /home/ammar`. You are running as `ammar`.
