### ISSUE TITLE
RESTful API Documentation?

### ISSUE THREAD

**Issue by amihaiemil** [zold-io/zold#668]
Where is the API's documentation?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@amihaiemil in the White Paper

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#668` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
