### ISSUE TITLE
Memory usage keeps increasing

### ISSUE THREAD

**Issue by oshanz** [zold-io/zold#673]
It's a [known issue](https://bugs.ruby-lang.org/issues/14759) that Glibc malloc creates too many arenas and leads to fragmentation which some times user complain as memory leaks or linux OOM killed the zold. solutions we have are

   - Reduce threads count.
   - [Change MALLOC_ARENA_MAX](https://devcenter.heroku.com/articles/tuning-glibc-memory-behavior)
   - switch to jemalloc. you do not need to compile Ruby with jemalloc. [you can dynamically load it with LD_PRELOAD](https://github.com/jemalloc/jemalloc/wiki/Getting-Started)

since zold is a gem, may be we can update our documentation to recomamnd "set this environment variable in user dynos, systemd unit files or however you start zold with MALLOC_ARENA_MAX = 2" in case of memory issue.

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.2`

**Comment by yegor256** [comment]
@oshanz I added the environment variable in 10561c3 Let's see how it behaves now

**Comment by yegor256** [comment]
@oshanz the problem is gone. Either thanks to this change or #672 Anyway, thanks to you!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#673` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
