### ISSUE TITLE
 Keyword 'Max' in Wallet class

### ISSUE THREAD

**Issue by strogiyotec** [zold-io/zold#675]
It's not clear to me how tid is calculated in method sub
```
 prefix, target = invoice.split('@')
      tid = max + 1
      raise 'Too many transactions already, can\'t add more' if max > 0xffff
```
What does 'max' means ? How it was calculated ?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@strogiyotec fixed in 4d3e261 thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#675` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
