### ISSUE TITLE
The startup message is not informattive on the errors

### ISSUE THREAD

**Issue by denis-konovalyenko** [zold-io/zold#678]
When I am starting my node:
```
[zold@dmz1 ~]$ zold --verbose node --nohup --host 91.211.13.180 --invoice=e560c4fb95684c6d
```
the following message is printed to my console:
```
Gem location: /home/zold/.rvm/gems/ruby-2.5.3/gems/zold-0.22.3
Home directory: /usr/home/zold/app-in-mem
Remote nodes: 16 total
Network: zold (main net)
Memory footprint at start is 23Mb
There are 4 threads in the 'hands' pool
Can't detect operating system: i586-freebsd11.2
Can't detect operating system: i586-freebsd11.2
Process ID 45260 saved into ""
45260
Memory footprint at the end is 26Mb
Failed in in 2.24s
```
Could you please clarify the following:
1. What are the causes of the fact that my OS is not detected properlly? Maybe, there are some limitiations or something else preventing the software to work as expected. Would not it be better to state this and exit with giving an option for the user to continue forcfully running the node (via additional `--force-node-running`, for instance).
2. What exactly has failed in the last line, as the node starts working after that?

My OS is:
```
FreeBSD dmz1 11.2-RELEASE-p5 FreeBSD 11.2-RELEASE-p5 #0: Tue Nov 27 17:06:40 UTC 2018     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  i386
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.4`

**Comment by yegor256** [comment]
@denis-konovalyenko  This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#678` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
