### ISSUE TITLE
Server reboot if other node have highter version

### ISSUE THREAD

**Issue by DronMDF** [zold-io/zold#679]
other server reply (GET /remotes)
```json
{..., "version"=>"5.5.5"}
```

zold log:
```
127.0.0.1:4096/0: their version 5.5.5 is higher than mine 0.22.4, reboot!   (use --never-reboot to avoid this from happening)
```
Highter version is not reason for reboot, if other server have alternative implementation.
Need to check X-Zold-Repo.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dronmdf[/z](https://www.0crat.com/u/dronmdf) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@DronMDF fixed in 6b3860b thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#679` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
