### ISSUE TITLE
Wrong TAX formula in White Paper

### ISSUE THREAD

**Issue by strogiyotec** [zold-io/zold#684]
White paper contains wrong description for Age field
```
A
is  the  total  age  of  the  wallet,  which  is  calculated  as  the  difference  in
hours  between  the  time  of  the  newest  and  the  oldest  transactions  in  the
wallet
```
Should be 
```
between current time and oldest txn in wallet
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@strogiyotec[/z](https://www.0crat.com/u/strogiyotec) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@strogiyotec fixed in https://github.com/zold-io/papers/commit/21a09ae49fefcd52473cb7bf9c8342faf37c66e0

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#684` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
