### ISSUE TITLE
translated to multiple languages

### ISSUE THREAD

**Issue by AlexisGarra** [zold-io/zold#688]
https://wts.zold.io
это все на английском языке, это не удобно.
я дал ссылку испанцу и он не захотел регистрировать кошелек и тоже произошло с руским.
вы их просто потеряли и руского и испанца. мне кажеться это легко написать https://wts.zold.io/home на 5 языках, если проблема на всех

**Comment by yegor256** [comment]
@AlexisGarra согласен, переведем

**Comment by yegor256** [comment]
@AlexisGarra решили не делать этого, только время потратим.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#688` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
