### ISSUE TITLE
!Рестарт!

### ISSUE THREAD

**Issue by AlexisGarra** [zold-io/zold#690]
я потерял все zld после рестарта, получения нового ключа  и после подтверждения кошелька.
меня даже не предупредило не одно всплывающее окно о том что я все потерял.
и хорошо , что сегодня еще zld не стоит 1000$ за 1zld. я потерял не 17500$  а всего лишь 17.5;$ 
Это не правильно

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@alexisgarra[/z](https://www.0crat.com/u/alexisgarra) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by AlexisGarra** [comment]
И все таки, я считаю, что потерял 17.5 zld именно из-за несовершенства системы, созданной Вами. Логическим  это не правильно, на примере : если поменять замок в доме, то вещи в доме не исчезнут. 
К тому же, я раньше делал рестарт кошелька и деньги не исчезали, и что же сейчас произошло ? И что будет в будущем?
Заметьте, что номер кошелька изменился,. но Акк на котором были средства был и остался @alexiszolotov
средства были  на двух кошельках
Обратите внимание,. что сегодня эта претензия на 17$ , и  как бы решалась претензия при курсе 1zld= 10000$ ?

**Comment by yegor256** [comment]
@AlexisGarra исправлено в https://github.com/zold-io/wts.zold.io/issues/120

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#690` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
