### ISSUE TITLE
пропали средства

### ISSUE THREAD

**Issue by AlexisZolotov** [zold-io/zold#691]
После рестарта кошелькa, без предупреждения исчезли все средства в размере 11,5 zld

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@alexiszolotov[/z](https://www.0crat.com/u/alexiszolotov) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@AlexisZolotov рестарт для этого и нужен, чтобы создать новый кошелек. Средства остались в старом кошельке. Я добавлю сообщение предупреждающее.

**Comment by yegor256** [comment]
@AlexisZolotov исправлено в https://github.com/zold-io/wts.zold.io/issues/120

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#691` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
