### ISSUE TITLE
исчезли средства

### ISSUE THREAD

**Issue by tomjons** [zold-io/zold#694]
после обновления кошелька исчезли 6 zld с аккаунта. Прошу разобраться и вернуть средства.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@tomjons[/z](https://www.0crat.com/u/tomjons) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@tomjons что такое "обновление кошелька"? PULL? если был Restart, то эта ошибка исправлена вот здесь: https://github.com/zold-io/wts.zold.io/issues/120

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#694` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by AlexisGarra** [comment]
restart
