### ISSUE TITLE
Run zold remote update within web wallet 

### ISSUE THREAD

**Issue by strogiyotec** [zold-io/zold#695]
![image](https://user-images.githubusercontent.com/20584185/52432265-39d40200-2b34-11e9-80fc-5acfa06b502f.png)
How can i fix it ?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@strogiyotec see https://github.com/zold-io/wts.zold.io/commit/6fdc8280cd4f313611329140e30400a2083a605b

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#695` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
