### ISSUE TITLE
Error "Can't get the gap from blockchain.com" is shown on Buy\Sell

### ISSUE THREAD

**Issue by ypshenychka** [zold-io/zold#703]
I'm receiving "Can't get the gap from blockchain.com" error when trying to click on Buy\Sell at https://wts.zold.io/home.

![image](https://user-images.githubusercontent.com/11703257/52838684-32949180-30fc-11e9-8c16-e5e296c2f53d.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ypshenychka it seems to be a temporary network issue, just reload the page. I added some extra comments here: https://github.com/zold-io/wts.zold.io/commit/449d8a1cc2705e763ebe2dd5bb1c487f929393c1

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#703` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
