### ISSUE TITLE
REMOTE SELECT should pick more reliable nodes

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#710]
Now we pick the largest scores, but this leads to isolation of a large part of the network. Let's pick the most reliable ones.

**Comment by yegor256** [comment]
@rultor release, tag is `0.23.10`

**Comment by yegor256** [comment]
@rultor release, tag is `0.23.10`

**Comment by yegor256** [comment]
@rultor release, tag is `0.23.11`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#710` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
