### ISSUE TITLE
Timestamp should be more detailed

### ISSUE THREAD

**Issue by ypshenychka** [zold-io/zold#712]
I've tried to sell zold, but got an error "At the moment we can send only one payment per day, sorry".
However on my transactions list last payment was made "1d" ago. We should show more detailed timestamp in this grid, since it's not clear why I can't do my payment now.
![image](https://user-images.githubusercontent.com/11703257/53041308-51907c00-348c-11e9-917f-c4bb83e8ef02.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ypshenychka this bug belongs to the WTS: https://github.com/zold-io/wts.zold.io/issues BTW, you can move the mouse over the text and you will see the exact date.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#712` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
