### ISSUE TITLE
Strange content of farm file

### ISSUE THREAD

**Issue by strogiyotec** [zold-io/zold#713]
I run the following command
``` 
zold node --invoice=c0137b2c4348998a --host=localhost --strength=6
```
This is the content of farm file
```
6 5c6d8088 localhost 1000 JdbZ3CIe c0137b2c4348998a Fdo7IP jVA6YM
```
According to white paper hash should end with 6 trailing zeros 

This is hash formula
```
def hash
      raise 'Score has zero value, there is no hash' if @suffixes.empty?
      @suffixes.reduce(prefix) do |pfx, suffix|
        OpenSSL::Digest::SHA256.new("#{pfx} #{suffix}").hexdigest
      end
    end
```
Prefix is 
```
2019-02-20T16:30:58+00:00 localhost 1000 JdbZ3CIe@c0137b2c4348998a
```
Now I add first suffix to it
```
2019-02-20T16:30:58+00:00 localhost 1000 JdbZ3CIe@c0137b2c4348998a Fdo7IP
```
SHA-256 hash is 
```
31C0693BA638F5960C65B558962E8AA49AF542C458CC7FFC4AF1E84E79B4188A
```
As you see no zeros . What did I miss ?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@strogiyotec[/z](https://www.0crat.com/u/strogiyotec) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@strogiyotec here:

```
2019-02-20T16:30:58+00:00 localhost 1000 JdbZ3CIe@c0137b2c4348998a
```

Time format is wrong. Should be ISO 8601: `2019-02-20T16:30:58Z`

**Comment by strogiyotec** [comment]
@yegor256 Thank you
```
2019-02-20T16:30:58Z localhost 1000 JdbZ3CIe@c0137b2c4348998a Fdo7IP
```
Hash is 
```
B8746BCCB7275F5E6204E194DBE2B28A56E3F0CDD093D67DE7C39D060AA3D8D3
```
Still wrong

**Comment by yegor256** [comment]
@strogiyotec the format of the prefix is: 

```
"#{@time.utc.iso8601} #{@host} #{@port} #{@invoice}"
```

See https://github.com/zold-io/zold-score/blob/master/lib/zold/score.rb#L257

**Comment by yegor256** [comment]
@strogiyotec the port should be in 10-digit format, not hex. Maybe it's a typo in White Paper. Don't hesitate to submit a bug there.

**Comment by yegor256** [comment]
@strogiyotec works now?

**Comment by strogiyotec** [comment]
@yegor256 No
```
2019-02-20T16:30:58Z localhost 3E8 JdbZ3CIe@c0137b2c4348998a Fdo7IP
```
Hash is
```
DBE00B9F1E054B02FBF35C0E456BEC8DF0792B022D1E9BC546572723A0D0C9F3
```
Where 
2019-02-20T16:30:58Z - time in ISO
localhost - host
3E8 - port in hex
JdbZ3CIe@c0137b2c4348998a - invoice
Fdo7IP - first suffix

**Comment by strogiyotec** [comment]
I have tried this option
```zold node --invoice=ba1b5e0cc4393536 --strength=2 --host=127.0.0.1
```
This is the content of farm file 
```
2 5c960e27 127.0.0.1 1000 cRagM1Ey ba1b5e0cc4393536 QV322W
```
5c960e27=2019-03-23T10:44:55Z(time)
1000=4097(port)
Prefix is 
```
2019-03-23T10:44:55Z 127.0.0.1 4096 cRagM1Ey@ba1b5e0cc4393536
```
Suffix is **QV322W**
**SHA-256(prefix sufix) = c16e57b843dd8bc32a7a66e1189b2718155a9b61f4a8cfec355eeea658f02d00**

Now it work

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#713` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
