### ISSUE TITLE
Why my node is in the ignore node list and how to it get out of there

### ISSUE THREAD

**Issue by denis-konovalyenko** [zold-io/zold#715]
My node has been experiencing this situation for a month or so already (the informational message in the log get lost for some reasons):
```
91.211.13.180:4096 won't be added since it's in the --ignore-node list
```

My questions are why it was put there and what I can do to clear this record out?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@denis-konovalyenko this message doesn't mean that your node is ignored. This means that your node doesn't add itself to its own list of nodes, that's why this `--ignore-node` option is used for. You don't see your node in the /health page?

**Comment by denis-konovalyenko** [comment]
@yegor256 , thanks for the clarifications! And your assumption is correct, I have not seen my node on the `health` page since it was relaunched after solving a hardware problem (that was more than a month ago, I believe). The score my node usually gets is 8, if it helps to make another 100% guess. :)

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#715` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
