### ISSUE TITLE
It looks like Amount does not support accurate decimal arithmetic

### ISSUE THREAD

**Issue by denis-konovalyenko** [zold-io/zold#718]
It happened that related to the API issue [#44](https://github.com/amihaiemil/zold-java-client/issues/44) had risen. And this one is opened due to the fact that the arithmetic operations do not use [BigDecimal](https://ruby-doc.org/stdlib-2.5.3/libdoc/bigdecimal/rdoc/BigDecimal.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@denis-konovalyenko but we use integers everywhere in Zold. We don't use double or float. Each number is in zents, and it's integer. I don't see how this bug is relevant to this repo.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#718` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
