### ISSUE TITLE
Define an election process for hosting bonus sharing

### ISSUE THREAD

**Issue by emilianodellacasa** [zold-io/zold#719]
Right now it is not really clear how hosting bonus is distributed among hosts: sometimes hosts with higher scores are skipped and scores with very low scores get the bonus.

For the sake of transparency and accountability, we should develop an election process like the one on Zerocracy to decide who gets the hosting bonus. Then, we should add a link somewhere for everyone to revise this election process.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@emilianodellacasa it's fixed, you can see full logs now

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#719` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by emilianodellacasa** [comment]
@yegor256 Cool, thanks!
