### ISSUE TITLE
too many remotes

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#724]
There are too many remotes in each node, let's make sure they keep their pools to a certain limit.

**Comment by yegor256** [comment]
@rultor release, tag is `0.24.5`

**Comment by yegor256** [comment]
@rultor release, tag is `0.24.5`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#724` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by yegor256** [comment]
@rultor release, tag is `0.26.7`
