### ISSUE TITLE
failed PULL on MERGE must not crash the entire copy

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#726]
Now that's exactly what's happening

**Comment by yegor256** [comment]
@rultor release, tag is `0.26.8`

**Comment by yegor256** [comment]
@rultor release, tag is `0.26.8`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#726` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
