### ISSUE TITLE
Impossible to convert ZLD to BTC

### ISSUE THREAD

**Issue by emilianodellacasa** [zold-io/zold#727]
I tried to convert ZLD to BTC, wts said it was ok but in the log it appeared the following message:

ERROR: UserError: We didn't manage to find your wallet in any of visible Zold nodes (zonuses). You should try to PULL again. If it doesn't work, most likely your wallet c21b99be1e280a5e is lost and can't be recovered. If you have its copy locally, you can push it to the network from the console app, using PUSH command. Otherwise, go for the RESTART option in the top menu and create a new wallet. We are sorry to see this happening! No nodes out of 20 have the wallet c21b99be1e280a5e; run 'zold remote update' and try again

However, c21b99be1e280a5e is not my wallet

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@emilianodellacasa this bug belongs to WTS: https://github.com/zold-io/wts.zold.io/issues

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#727` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
