### ISSUE TITLE
push when too many local copies

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#730]
Let's push wallet to the network if they have too many local copies

**Comment by yegor256** [comment]
@rultor release, tag is `0.26.11`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#730` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by yegor256** [comment]
@rultor release, tag is `0.26.12`
