### ISSUE TITLE
queue overflow is still there

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#735]
The queue is still too busy...

**Comment by yegor256** [comment]
@rultor release, tag is `0.26.18`

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.26`

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.27`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#735` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
