### ISSUE TITLE
/journal

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#736]
Let's keep a journal for each wallet, with all changes that happen there.

**Comment by yegor256** [comment]
@rultor release, tag is `0.26.16`

**Comment by yegor256** [comment]
@rultor release, tag is `0.26.16`

**Comment by yegor256** [comment]
@rultor release, tag is `0.26.16`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#736` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
