### ISSUE TITLE
JournaledEntrance is mixing all wallets in one log

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#737]
We should split them up

**Comment by yegor256** [comment]
@rultor release, tag is `0.26.17`

**Comment by yegor256** [comment]
@rultor release, tag is `0.26.17`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#737` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
