### ISSUE TITLE
--trusted

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#738]
Let's make it possible to trust a list of wallets, during merge, to avoid endless recursion.

**Comment by yegor256** [comment]
@rultor release, tag is `0.26.19`

**Comment by yegor256** [comment]
@rultor release, tag is `0.26.19`

**Comment by yegor256** [comment]
@rultor release, tag is `0.26.19`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#738` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
