### ISSUE TITLE
--trusted-file

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#739]
Let's make it possible to list all trusted wallets in a temporary file

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.20`

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.20`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#739` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
