### ISSUE TITLE
trusted overflow

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#740]
We put too many of them there

**Comment by yegor256** [comment]
@rultor release, tag is `0.26.21`

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.21`

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.21`

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.21`

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.21`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#740` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
