### ISSUE TITLE
Zold is telling that will pay PayPal fees, but don't

### ISSUE THREAD

**Issue by paulodamaso** [zold-io/zold#749]
Zold web wallet interface is telling us that will pay the fees on my retrieval:
>You will receive exactly $xxx, we will pay PayPal fees.

But looking at paypal ledger:
```
Zerocracy development, TID 9e01xxxxxxbe64:5
Purchase details
Item amount$ 0,00
Estimated fee-negative $ 18,30
Total$ 262,88
```

Looks like I'm being charged for the fees

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by ebercamargo** [comment]
@paulodamaso this happened me too, I thought it would be normal, but it's not ...

**Comment by yegor256** [comment]
@paulodamaso please submit it here: https://github.com/zold-io/wts.zold.io/issues

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#749` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
