### ISSUE TITLE
Double spending

### ISSUE THREAD

**Issue by g4s8** [zold-io/zold#75]
How to prevent double spending without general ledger? User has X Zold, he can send and push X Zold to wallet-1 using node-1 then delete last transaction and send same amount to wallet-2 using node-2, all these operations user can do in a few seconds, so wallet-2 will receive X Zold and wallet-1 also will receive X Zold

Usually blockchain solves these issues, but looks like Zold doesn't have it.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C91QJT4CF) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C91QJT4CF) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@g4s8 it's better to split problems into tickets. As for the "double spending" problem, did you check the subsection "Double spending attack" in the white paper?

**Comment by g4s8** [comment]
@yegor256 yes, but it says:
> This will happen, but very soon one part of the network will dominate the
other one, and one of the transactions will be rejected from the wallet, after
a number of merge operations in all nodes of the network.

I think it assumes that each node should know about each wallet and each transaction, or am I wrong? If yes, it also looks like "general ledger" just structured in other way.

**Comment by yegor256** [comment]
@g4s8 yes, it is a "general ledger", but it's spread among many files. And it's very possible that not all nodes will keep all wallets on board. It's not necessary and won't happen often.

**Comment by yegor256** [comment]
@g4s8 I believe this is fixed. If you still have questions, please submit it to zold-io/papers repository

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#75` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by g4s8** [comment]
@yegor256 thanks
