### ISSUE TITLE
Apply recommended community standards.

### ISSUE THREAD

**Issue by aivinog1** [zold-io/zold#750]
As described in this page: https://github.com/zold-io/zold/community the project now is not fully compatible with open source standards. May be worth to apply those standards that developers can integrate in the project more quickly?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@aivinog1[/z](https://www.0crat.com/u/aivinog1) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@aivinog1 done, thanks for bringing this up

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#750` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
