### ISSUE TITLE
How to add all available remote node

### ISSUE THREAD

**Issue by strogiyotec** [zold-io/zold#752]
I have a question about ``` remote ``` command , as I see from source code of remote.rb the only way to add new remote node is to manually provide host and port of new remote . Does zold provide some way to add all available remote nodes that I miss in my remote file ?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@strogiyotec[/z](https://www.0crat.com/u/strogiyotec) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by strogiyotec** [comment]
I have seen an answer , you need to use zold remote update

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#752` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
