### ISSUE TITLE
Recursive Error 65280 when alias param contains wrong character

### ISSUE THREAD

**Issue by emilianodellacasa** [zold-io/zold#754]
Wehn starting a zold node I used a character that wasn't permitted. 

The log file contains a legit error message, however zold doesn't terminate correctly: instead, it keeps on failing with following error message:

```
Alias should be a 4 to 16 char long alphanumeric string: edc_2 (RuntimeError)
Nothing else left to read from #1603
Exit code of process #1603 is 65280, was alive for 1.4s: <command>
RuntimeError: Exit code is 65280
        /var/lib/gems/2.5.0/gems/zold-0.29.27/lib/zold/commands/node.rb:410:in `block (2 levels) in nohup'
        /var/lib/gems/2.5.0/gems/zold-0.29.27/lib/zold/commands/node.rb:407:in `loop'
        /var/lib/gems/2.5.0/gems/zold-0.29.27/lib/zold/commands/node.rb:407:in `block in nohup'
        /var/lib/gems/2.5.0/gems/zold-0.29.27/lib/zold/commands/node.rb:395:in `fork'
        /var/lib/gems/2.5.0/gems/zold-0.29.27/lib/zold/commands/node.rb:395:in `nohup'
        /var/lib/gems/2.5.0/gems/zold-0.29.27/lib/zold/commands/node.rb:210:in `run'
        /var/lib/gems/2.5.0/gems/zold-0.29.27/lib/zold/commands/thread_badge.rb:41:in `run'
        /var/lib/gems/2.5.0/gems/zold-0.29.27/bin/zold:210:in `block in <top (required)>'
        /var/lib/gems/2.5.0/gems/zold-0.29.27/bin/zold:280:in `<top (required)>'
        /usr/local/bin/zold:23:in `load'
        /usr/local/bin/zold:23:in `<main>'Started process #1620 from process #1599: 
```

In that case, I think the process should just stop

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@emilianodellacasa well, this is by design. If you start it with `--nohup`, it restarts itself on __any__ failure.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#754` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
