### ISSUE TITLE
The node 0.0.0.0:4096 is not responding

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#762]
```
DEBUG: RuntimeError: The node 0.0.0.0:4096 is not responding, 599:
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.28/lib/zold/commands/remote.rb:374:in `ping'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.28/lib/zold/commands/remote.rb:215:in `add'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.28/lib/zold/commands/remote.rb:288:in `block (4 levels) in update'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.28/lib/zold/commands/remote.rb:286:in `each'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.28/lib/zold/commands/remote.rb:286:in `block (3 levels) in update'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.28/lib/zold/commands/remote.rb:318:in `update_one'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.28/lib/zold/commands/remote.rb:280:in `block (2 levels) in update'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.28/lib/zold/remotes.rb:223:in `block in iterate'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.28/lib/zold/hands.rb:88:in `block (3 levels) in exec'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.28/lib/zold/hands.rb:85:in `loop'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.28/lib/zold/hands.rb:85:in `block (2 levels) in exec'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.28/lib/zold/hands.rb:56:in `block (2 levels) in start'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.28/lib/zold/endless.rb:45:in `block (2 levels) in run'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.28/lib/zold/verbose_thread.rb:41:in `run'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.28/lib/zold/endless.rb:44:in `block in run'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.28/lib/zold/endless.rb:43:in `loop'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.28/lib/zold/endless.rb:43:in `run'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.28/lib/zold/hands.rb:55:in `block in start'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.28/lib/zold/thread_pool.rb:49:in `block (2 levels) in add'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.28/lib/zold/verbose_thread.rb:41:in `run'
	/app/vendor/bundle/ruby/2.6.0/gems/zold-0.29.28/lib/zold/thread_pool.rb:47:in `block in add'
```

**Comment by 0crat** [comment]
The job [#762](https://github.com/zold-io/zold/issues/762) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1ab8f104-47e6-421f-9912-b2c85a1cc2af); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#762` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.29`

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#762](https://github.com/zold-io/zold/issues/762) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
