### ISSUE TITLE
Masqueraded host 0.0.0.0

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#763]
```
# Logfile created on 2019-05-21 17:11:51 +0200 by logger.rb/61378
push(b90674163a61d9d5, 3666 bytes): starting...
Time: 2019-05-21T15:11:51Z
Zold gem version: 0.29.29
D: No need to fetch b90674163a61d9d5 from 84.201.144.83:4096/0, it's the same content as copy #1
D: No need to fetch b90674163a61d9d5 from 80.211.47.94:4096/1, it's the same content as copy #2
D: No need to fetch b90674163a61d9d5 from 185.43.211.141:4096/2, it's the same content as copy #1
D: No need to fetch b90674163a61d9d5 from 3.18.62.3:4096/3, it's the same content as copy #1
D: No need to fetch b90674163a61d9d5 from 80.211.40.161:4096/4, it's the same content as copy #1
D: No need to fetch b90674163a61d9d5 from 85.235.66.93:4096/5, it's the same content as copy #2
D: No need to fetch b90674163a61d9d5 from 3.19.47.160:4096/6, it's the same content as copy #2
D: No need to fetch b90674163a61d9d5 from 37.194.10.30:4096/7, it's the same content as copy #1
D: No need to fetch b90674163a61d9d5 from 157.230.101.165:4096/8, it's the same content as copy #2
D: No need to fetch b90674163a61d9d5 from 178.238.225.176:4096/9, it's the same content as copy #2
D: 0.0.0.0:4096/10 failed to fetch b90674163a61d9d5, trying again (attempt no.1): Masqueraded host 0.0.0.0 as b2.zold.io: 8 5ce3d1a1 b2.zold.io 1000 DpTOG8hC 912ecc24b32dbe74 ZesBCJ
```

**Comment by 0crat** [comment]
The job [#763](https://github.com/zold-io/zold/issues/763) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/c4007784-89f0-4949-971f-51a925980235); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.30`

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.30`

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#763](https://github.com/zold-io/zold/issues/763) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
