### ISSUE TITLE
Let's think about monitoring system.

### ISSUE THREAD

**Issue by aivinog1** [zold-io/zold#768]
**Is your feature request related to a problem? Please describe.**
For example, this issue: #767 has not fixed after many hours. And this can be found much earlier (before actual users faces this problem).

**Describe the solution you'd like**
I was thinking about some monitoring system, that can see that connection is opened (for example do a simple `select`). If the DB connection is closed(timeout, whatever) needs to inform user on the page that for now has a connection issues.

**Describe alternatives you've considered**
As an alternative (or an addition) the app can create an issue on Github from some technical user or some bot when connection is broken. If do this in a addition to the previous solution we can post a link to the issue in the warning page.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@aivinog1[/z](https://www.0crat.com/u/aivinog1) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@aivinog1 we already have a Telegram chat for that: https://t.me/zold_wts

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#768` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
