### ISSUE TITLE
Bonus not distributed every hour

### ISSUE THREAD

**Issue by scristalli** [zold-io/zold#774]
According to https://blog.zold.io/2018/08/14/hosting-bonuses.html:

> Every hour wts.zold.io server (you can see its source code) selects the best 8 nodes out of those it can see and pays them 1 ZLD, distributing equally.

However, in the Telegram channel only 2 bonuses have been notified today.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@scristalli[/z](https://www.0crat.com/u/scristalli) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by scristalli** [comment]
@yegor256, is this in scope? Is it an issue of the bot not notifying every distribution, or are the distributions not happening?

**Comment by yegor256** [comment]
@scristalli we distribute bonuses only when we have enough funds for that. However, this may not be the case every hour. See this paper for more details: http://papers.zold.io/fin-model.pdf
