### ISSUE TITLE
let's show checksum in the JSON front

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#776]
let's do it

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.32`

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.32`

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.32`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#776` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
