### ISSUE TITLE
Which tool/plugin/gem is using for license injection/maintenance within the project files?

### ISSUE THREAD

**Issue by dgroup** [zold-io/zold#782]
I think this information should be present in the contribution guide.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dgroup[/z](https://www.0crat.com/u/dgroup) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@dgroup there is no plugin. We just copy paste the license header from file to file

**Comment by dgroup** [comment]
Found this gem https://github.com/barrydrink/LicenceInjector
but due to poor documentation its isn't easy to use.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#782` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by dgroup** [comment]
RubyMine by default has no 'Copyright' plugin, however after installation and restart it became available.
https://plugins.jetbrains.com/plugin/88-copyright/
