### ISSUE TITLE
Difference between bind-port and port options

### ISSUE THREAD

**Issue by HDouss** [zold-io/zold#786]
It is not clear what the difference between these two options are when starting a node: bind-port and port. In addition, the log is wrong or confusing.
I can start a node by:
`zold node --threads 0 --invoice xx@xx --host 127.0.0.1 --standalone --port 80 --bind-port 8080`
and I see: 
`Starting up the web front at http://127.0.0.1:80...`
but I can only make requests to http://127.0.0.1:8080

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@hdouss[/z](https://www.0crat.com/u/hdouss) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@HDouss I added more details, in cdbf74a Better now?

**Comment by HDouss** [comment]
@yegor256 yes it is better. Thanks.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#786` is not assigned, can't get performer
