### ISSUE TITLE
new release is necessary

### ISSUE THREAD

**Issue by davvd** [zold-io/zold#797]
The latest release is more than two years old. A new one would be great to have.

**Comment by 0crat** [comment]
You @davvd[/z](https://www.0crat.com/u/davvd) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by davvd** [comment]
@rultor release tag = `0.29.34`

**Comment by davvd** [comment]
@rultor release tag = `0.29.34`

**Comment by davvd** [comment]
@rultor release tag = `0.29.34`

**Comment by davvd** [comment]
@rultor release tag = `0.29.34`

**Comment by davvd** [comment]
@rultor release tag = `0.29.34`

**Comment by davvd** [comment]
@rultor release tag = `0.29.34`

**Comment by davvd** [comment]
@rultor release tag = `0.29.34`

**Comment by davvd** [comment]
@rultor release tag = `0.29.34`

**Comment by davvd** [comment]
@rultor release tag = `0.29.34`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#797` is not assigned, can't get performer
