### ISSUE TITLE
http.rb needs a better implementation

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#81]
Let's implement it with something more low-level. Now it's very difficult to configure. For example, timeout doesn't work and sometimes it stays waiting for a minute before throwing an exception. I'm not sure, but most likely Ruby has some other HTTP client, which is better.

Sometimes we are even getting this one:

```
ERROR: undefined method `closed?' for nil:NilClass
Did you mean?  clone (NoMethodError)
/Users/yegor/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http/response.rb:331:in `stream_check'
/Users/yegor/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http/response.rb:200:in `read_body'
/Users/yegor/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http/response.rb:227:in `body'
/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.9.8/lib/zold/commands/push.rb:69:in `block in push'
/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.9.8/lib/zold/commands/push.rb:59:in `each'
/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.9.8/lib/zold/commands/push.rb:59:in `push'
/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.9.8/lib/zold/commands/push.rb:52:in `block in run'
/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.9.8/lib/zold/commands/push.rb:51:in `each'
/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.9.8/lib/zold/commands/push.rb:51:in `run'
/Users/yegor/.rvm/gems/ruby-2.3.3/gems/zold-0.9.8/bin/zold:166:in `<top (required)>'
/Users/yegor/.rvm/gems/ruby-2.3.3/bin/zold:22:in `load'
/Users/yegor/.rvm/gems/ruby-2.3.3/bin/zold:22:in `<main>'
```

**Comment by 0crat** [comment]
Job [#81](https://github.com/yegor256/zold/issues/81) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#81](https://github.com/yegor256/zold/issues/81); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c1247f40-4c56-45a0-880c-9418d4621a65, thread: pool-231-thread-1
java.lang.Thread[-2] java.lang.OutOfMemoryError: unable to create new native thread
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: zold-io/zold#81, Action: `assigned`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.45`

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#81` is not assigned, can't get performer
