### ISSUE TITLE
skip already existing wallet IDs

### ISSUE THREAD

**Issue by davvd** [zold-io/zold#819]

**Comment by davvd** [comment]
@rultor release tag = `0.31.6`

**Comment by davvd** [comment]
@rultor release tag = `0.31.6`

**Comment by davvd** [comment]
@rultor release tag = `0.31.6`

**Comment by davvd** [comment]
@rultor stop

**Comment by davvd** [comment]
@rultor release tag = `0.31.6`

**Comment by davvd** [comment]
@rultor release tag = `0.31.6`

**Comment by davvd** [comment]
@rultor release tag = `0.31.6`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#819` is not assigned, can't get performer
