### ISSUE TITLE
Zold node cli command lacks feedback

### ISSUE THREAD

**Issue by biboran** [zold-io/zold#82]
`zold node` cli command should have some sort of continuous or queryable feedback. Right now it's not clear if launching `zold node` is sufficient to be a participant in the network (yegor256/zold/issues/80) and what progress in security rating computation or taxes collection is achieved.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@biboran[/z](https://www.0crat.com/u/biboran) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C91QJT4CF) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@biboran make sense, thanks, we should add more logs there

**Comment by 0crat** [comment]
The job [#82](https://github.com/yegor256/zold/issues/82) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C91QJT4CF/1481146036); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)com.zerocracy.Par@10cadc5a

**Comment by 0crat** [comment]
Job `gh:yegor256/zold#82` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @biboran[/z](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c1247f40-4c56-45a0-880c-9418d4621a65, thread: pool-232-thread-1
java.lang.Thread[-2] java.lang.OutOfMemoryError: unable to create new native thread
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: zold-io/zold#82, Action: `assigned`

**Comment by yegor256** [comment]
@biboran  This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#82` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
