### ISSUE TITLE
GZIP all traffic

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#86]
Let's use GZIP for all inbound and outbound traffic.

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#86](https://github.com/yegor256/zold/issues/86); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job [#86](https://github.com/zold-io/zold/issues/86) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @oltdaniel

**Comment by 0crat** [comment]
> @0crat assign @oltdaniel ([here](https://github.com/zold-io/zold/issues/86#issuecomment-394111780))

@yegor256 The job [#86](https://github.com/zold-io/zold/issues/86) assigned to @oltdaniel[/z](https://www.0crat.com/u/oltdaniel), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1531940267); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by oltdaniel** [comment]
@yegor256 That would require `use Rack::Deflater` after the following line https://github.com/zold-io/zold/blob/master/lib/zold/node/front.rb#L39

**Comment by 0crat** [comment]
@oltdaniel[/z](https://www.0crat.com/u/oltdaniel) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @oltdaniel[/z](https://www.0crat.com/u/oltdaniel) resigned from [#86](https://github.com/zold-io/zold/issues/86), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @oltdaniel[/z](https://www.0crat.com/u/oltdaniel)

**Comment by oltdaniel** [comment]
@yegor256 This is implemented, but eatch the test case numbers, because if the content grows, it will fail.

**Comment by yegor256** [comment]
@oltdaniel thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#86` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#86](https://github.com/zold-io/zold/issues/86) is now out of scope
