### ISSUE TITLE
dry-types

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#98]
Let's get rid of type checks everywhere in the code and migrate to http://dry-rb.org/gems/dry-types/ (or similar solution)

**Comment by 0crat** [comment]
Job [#98](https://github.com/yegor256/zold/issues/98) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#98](https://github.com/yegor256/zold/issues/98); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job [#98](https://github.com/zold-io/zold/issues/98) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#98](https://github.com/zold-io/zold/issues/98) assigned to @mulev[/z](https://www.0crat.com/u/mulev), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1651867589); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@mulev[/z](https://www.0crat.com/u/mulev) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @mulev[/z](https://www.0crat.com/u/mulev) resigned from [#98](https://github.com/zold-io/zold/issues/98), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#98](https://github.com/zold-io/zold/issues/98) assigned to @sandiks[/z](https://www.0crat.com/u/sandiks), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1760728287); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
The job [#98](https://github.com/zold-io/zold/issues/98) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1781431142); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by emilianodellacasa** [comment]
@yegor256 Refactoring the whole code to dry-types require a great deal of work because there are many loosely coupled classes. I started by refactoring _score_ class but then another problem came in the _http_ class and others. 

Since I have spent the budget of 30 minutes right now, I ask for 1 hour more to complete the task leaving with a stable code base (all test green) then I will add a _todo_ to proceed with the refactoing of the other classes.

**Comment by yegor256** [comment]
@0crat boost 4x

**Comment by 0crat** [comment]
> @0crat boost 4x ([here](https://github.com/zold-io/zold/issues/98#issuecomment-402134328))

@yegor256 Boost 4x was set for [#98](https://github.com/zold-io/zold/issues/98)

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by emilianodellacasa** [comment]
@yegor256 PR #347

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zold-io/zold/issues/98#issuecomment-402635393))

@g4s8 This is what I know about this job in [CAZPZR9FS](https://www.0crat.com/p/CAZPZR9FS), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#98](https://github.com/zold-io/zold/issues/98) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) for [8days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) will get 100% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 60 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
    * @mulev[/z](https://www.0crat.com/u/mulev): User was resigned from the ticket
    * @sandiks[/z](https://www.0crat.com/u/sandiks): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CAZPZR9FS?q=%7Bjob%3A%27gh%3Azold-io%2Fzold%2398%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
The user @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) resigned from [#98](https://github.com/zold-io/zold/issues/98), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -60 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
The job [#98](https://github.com/zold-io/zold/issues/98) assigned to @mgrassotti[/z](https://www.0crat.com/u/mgrassotti), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1881839451); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by emilianodellacasa** [comment]
@yegor256 please assign this task back to me

**Comment by yegor256** [comment]
@0crat assign @emilianodellacasa

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zold-io/zold/issues/98#issuecomment-403779732))

@g4s8 This is what I know about this job in [CAZPZR9FS](https://www.0crat.com/p/CAZPZR9FS), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#98](https://github.com/zold-io/zold/issues/98) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
    * @mulev[/z](https://www.0crat.com/u/mulev): User was resigned from the ticket
    * @sandiks[/z](https://www.0crat.com/u/sandiks): User was resigned from the ticket
    * @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CAZPZR9FS?q=%7Bjob%3A%27gh%3Azold-io%2Fzold%2398%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat assign @emilianodellacasa  ([here](https://github.com/zold-io/zold/issues/98#issuecomment-403504386))

@yegor256 The job [#98](https://github.com/zold-io/zold/issues/98) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1911045120); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zold-io/zold/issues/98#issuecomment-403785070))

@g4s8 This is what I know about this job in [CAZPZR9FS](https://www.0crat.com/p/CAZPZR9FS), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#98](https://github.com/zold-io/zold/issues/98) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) for [22min](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
    * @mulev[/z](https://www.0crat.com/u/mulev): User was resigned from the ticket
    * @sandiks[/z](https://www.0crat.com/u/sandiks): User was resigned from the ticket
    * @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa): User was resigned from the ticket
    * @mgrassotti[/z](https://www.0crat.com/u/mgrassotti): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CAZPZR9FS?q=%7Bjob%3A%27gh%3Azold-io%2Fzold%2398%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by emilianodellacasa** [comment]
@yegor256 past boost has been lost (created an issue for that), could you please do it again? Thanks

**Comment by emilianodellacasa** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@0crat boost 4x

**Comment by 0crat** [comment]
> @0crat boost 4x ([here](https://github.com/zold-io/zold/issues/98#issuecomment-404193928))

@yegor256 Boost 4x was set for [#98](https://github.com/zold-io/zold/issues/98)

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#393](https://github.com/zold-io/zold/issues/393), [#394](https://github.com/zold-io/zold/issues/394) are still not solved.

**Comment by emilianodellacasa** [comment]
@yegor256 PR https://github.com/zold-io/zold/pull/347 has been closed, please close this issue

**Comment by emilianodellacasa** [comment]
@yegor256 ping

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zold-io/zold/issues/98#issuecomment-405658820))

@g4s8 This is what I know about this job in [CAZPZR9FS](https://www.0crat.com/p/CAZPZR9FS), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#98](https://github.com/zold-io/zold/issues/98) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) for [7days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) will get 100% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 60 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
    * @mulev[/z](https://www.0crat.com/u/mulev): User was resigned from the ticket
    * @sandiks[/z](https://www.0crat.com/u/sandiks): User was resigned from the ticket
    * @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa): User was resigned from the ticket
    * @mgrassotti[/z](https://www.0crat.com/u/mgrassotti): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CAZPZR9FS?q=%7Bjob%3A%27gh%3Azold-io%2Fzold%2398%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by yegor256** [comment]
@emilianodellacasa thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#98](https://github.com/zold-io/zold/issues/98) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +76 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#393](https://github.com/zold-io/zold/issues/393), [#421](https://github.com/zold-io/zold/issues/421) are still not solved; solved: [#394](https://github.com/zold-io/zold/issues/394).

**Comment by 0pdd** [comment]
@yegor256 all 3 puzzles are solved here: [#393](https://github.com/zold-io/zold/issues/393), [#394](https://github.com/zold-io/zold/issues/394), [#421](https://github.com/zold-io/zold/issues/421).
