### ISSUE TITLE
malware threat

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold#99]
What if we change the code (intentionally or by mistake) and our users will lose their ZLD? Let's explain this situation in the White Paper and find a reasonable answer.

**Comment by 0crat** [comment]
Job [#99](https://github.com/yegor256/zold/issues/99) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#99](https://github.com/yegor256/zold/issues/99); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@yegor256 we'll do it in the papers repo

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#99` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
